### ISSUE TITLE
Incorrect Rootana Text Output (number of analysed channels)

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#1]
In the rootana text output, it states the number of channels that will be analysed.

In the `MODULES` file, if `analyse_channels=all`, then this output incorrectly states that rootana `Will analyse 1 of 28 channels`.

This isn't a major bug but may cause confusion (also I can now test the issues system :) )

Cheers
Andy

**Comment by benkrikler** [comment]
This should now be fixed so I'm closing this issue. (Got to love that github picks up the commit message!! ).
