### ISSUE TITLE
ComandLine.cpp is diddilng memory

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#102]
When I try to run main.cpp, if I don't use the -m option I get the error: `Problem opening modules file: H\ufffd!`

This filename looks to be some memory junk.  I'm not exactly sure what happened yet but tracing back  to CommandLine.cpp the char array is a static filled using sprintf so, frankly, anything could be going on, up to and including plagues of frogs.  
1. Has anyone made a recent change to this?
2. Is there any good reason we are using sprintf in 2014?

(Also I notice that there does not appear to be a MODULES file for me to target... shouldn't a default have been created somewhere in the build?)

**Comment by litchfld** [comment]
Found it!  In CommandLine.h:

``` C++
typedef struct {
  char *infile;
  char *outfile;
  // ...
} ARGUMENTS; 
// Aside: we can just do struct ARGUMENTS { ...}; since this is C++ 
```

but in CommandLine.cpp:

``` C++
int analyze_command_line (int argc, char **argv, ARGUMENTS& arguments)
{
  // Inialise the arguments to be consistently meaningless
  arguments.infile="";
  arguments.outfile="";
  //...
```

**This does not do what you might think!**  It sets (for example) the pointer-to-char `arguments.infile` to the location in memory of the string literal `""` which is most likely an array-of-char-of-length 1, in static storage.  Writing anything longer than a char (1 byte) into this pointer is an array out-of-bounds error.  In this function body it's not really an issue, because the only thing that might happen is that we subsequently set the pointer to the start of an element of `argv`. But at the end we call `check_arguments`:

[**EDITED** from here onward]

``` C++
int check_arguments(ARGUMENTS& arguments){
  //...
  if(strcmp(arguments.mod_file,"")==0){
    sprintf(mod_file,"MODULES");
    arguments.mod_file=mod_file;
```

**OH NOES!** This is sort of doing the right thing - not writing on memory but reassigning the pointer.  The problem is the initial comparison, because this particular pointer was never set, the string isn't necessarily equal to `""`  I'm not sure why this isn't universally a problem, but the compiler is free to initialise the pointer how it likes, different versions of gcc may or not get lucky and be right by accident.

Moral of the story: **I _fear_ C string operations, and you should too.**

Possible fixes:
1. We initialise that variable so it does pass the check.
2. We use `std::string`, which behaves the way you expect.  This has the knock-on effect that we have, at least, to convert all uses of `ARGUMENTS::mod_file` to `ARGUMENTS::mod_file.c_str()`. There are variants to this, but all the sane ones change the interface of `ARGUMENTS`.

Which one do people prefer?

**Comment by litchfld** [comment]
Looked at it again, the problem exists but isn't quite how I said. Read again from **EDITED**

**Comment by jrquirk** [comment]
I support the string. I also support removing `typedef` in favor of the clearer modern `struct`.

**Comment by litchfld** [comment]
Well call it a go then. I'll finish up the feature when I get in.  AFAICT the only place that needs changing in response is main.cpp, which makes sense. I'll make the corresponding change there, but if you are using (rootana version of) arguments somewhere this will break it. Sorry about that.

**Comment by litchfld** [comment]
The feature branch should be complete now.  I'll probably merge it back in to develop after the meeting, but I don't want to start now in case git give me merge conflicts.

**Comment by litchfld** [comment]
Merged.

**Comment by AndrewEdmonds11** [comment]
Are you sure this is merged, Phill? 

I'm trying to finish off a feature branch but when I pull in develop there was only one commit added (3a118ab5793f3538cbc1145c4fa6f4b42349a1bd). Looking at the network graph also looks like it's not there. Do you need to push your merged develop branch up to GitHub?

**Comment by litchfld** [comment]
I  thought I had, but apparently not. Try again now.

**Comment by AndrewEdmonds11** [comment]
Yep, that's done it. Cheers
