### ISSUE TITLE
PulseCandidateFinder: set parameter values through modules file

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#103]
It would be nice to set the parameter values for the PulseCandidateFinder through the modules themselves since different parameter values may be needed for each generator.

**Comment by AndrewEdmonds11** [comment]
@benkrikler, I'm thinking of the best way to store the parameter values in the PulseCandidateFinder class. I want to use a map of channel name (a string) to a parameter value (double or maybe just int) and know you've done something similar for selecting generators on a channel by channel basis.

However, looking in the MakeAnalysedPulses code, there doesn't seem to be any map. From what I gather, you just have a vector of channels to analyse (`fChannelsToAnalyse`) and a vector of generators (`fGenerators`) and you add the detector to the generator in `AddGenerator()`.

This doesn't seem like it would work with the PulseCandidateFinder and I know that searching through a map can be slow (especially if I want to get the parameter value for each pulse). Is there a nice way to do this?

**Comment by AndrewEdmonds11** [comment]
So, I think I found a way to do this in the above commit:

```
PulseCandidateFinder::PulseCandidateFinder(modules::options* opts) {
  fRiseValues[IDs::kMuSc] = opts->GetInt("muSc", 300);
  std::cout << "muSc Rise Value = " << fRiseValues[IDs::kMuSc] << std::endl;
}
```

This is for one channel but I can loop through them all in the IDs enum. (Or can I? If I want different default values then is it possible?)

**Comment by AndrewEdmonds11** [comment]
This now done. Just one thing that I wasn't sure how to do but is non-urgent, is that it would be nice for the debug output to print the module name that is using this instance of a PulseCandidateFinder.

Anyway, closing....

**Comment by benkrikler** [comment]
Looks like you beat me to it, but using the `modules::options` class is the simplest way to get options in.  For TAP_generator there's also a specialisation called `TAPGeneratorOptions` of this class that it might make sense to use instead, although at this point I think they're essentially identical.

> This doesn't seem like it would work with the PulseCandidateFinder and I know that searching through a map can be slow

The method setting up these parameters is only called once, so I wouldn't worry about the speed of setting this up and a map is definitely convenient.

> This is for one channel but I can loop through them all in the IDs enum. (Or can I? If I want different default values then is it possible?)

I would have a list of default values then loop over all options passed to the config and if any match a channel name, use that value instead.  If this sort of thing is common then I can look at factoring out the code from MakeAnalysedPulses into something we can reuse.

One question:  this isn't a standalone module right? It's a class that the generators can use, no?  If so, I'm not sure why this class will need to handle multiple channels.  Just have each instance of `PulseCandidateFinder` handle one channel and let each generator make an instance for itself.  Each instance would only need up to two options then:  one for the name of a channel and optionally another for the start and / or stop criteria for the finder.  If the second option is not provided, then an internal, static map could be used to provide a default value depending on the channel name given.   This is sort of thing is how the generators work: once class, but many instances, each instance handling only a single channel.  It's the MakeAnalysedPulses module that needs to know of many channels, but that's it.

**Comment by AndrewEdmonds11** [comment]
> One question: this isn't a standalone module right? It's a class that the generators can use, no? If so, I'm not sure why this class will need to handle multiple channels.

You're right. I didn't think about doing it the way you describe but I can imagine it would be more difficult for people to use in their modules if they have to create a new one for each channel. Currently, they just need:

``` c++
PulseCandidateFinder* fPulseCandidateFinder = new PulseCandidateFinder(opts);
```

and then everything's ready for it to be passed a TPI and to get canidates from.

At the moment, each channel is individually looked for in the constructor of PulseCandidateFinder, which isn't pretty but is probably good enough. (I did manage to loop through for the debug output however :))

**Comment by benkrikler** [comment]
> Currently, they just need:
> 
> ```
> PulseCandidateFinder* fPulseCandidateFinder = new PulseCandidateFinder(opts);
> ```
> 
> and then everything's ready for it to be passed a TPI and to get canidates from.

But then why does fPulseCandidateFinder need to handle multiple channels?  Is it going to be used elsewhere other than in the generators?  A generator only handles one channel so it would never need more than this from the pulse finder.

**Comment by AndrewEdmonds11** [comment]
> But then why does fPulseCandidateFinder need to handle multiple channels? 

Oh right, I didn't realise we had one generator per channel. I thought we had one generator which was wen through each channel.

> Is it going to be used elsewhere other than in the generators? A generator only handles one channel so it would never need more than this from the pulse finder.

It's also being used by PulseCandidateFinder_InvestigateParameters, so it's not just for generators.

I think I'll still leave it as it is but keep in mind that there is a better way if we need to optimise.

**Comment by litchfld** [comment]
> One question: this isn't a standalone module right? It's a class that the generators can use, no? If so, I'm not sure why this class will need to handle multiple channels. Just have each instance of PulseCandidateFinder handle one channel and let each generator make an instance for itself. 

THIS.  
I imagined you would have a constructor that takes a detector / bank identifier, and look up the appropriate parameters form the `modules::options` class, e.g. something like:

``` C++
//not sure if Identifier should be a string or a IDs::somthing;
PulseCandidateFinder::PulseCandidateFinder(Identifier id, module::options& opts)
  : fIdentifier(id),
    fRiseThreshold( opts.GetInt(id, 300) ),
    //etc...
{
//do anything complicated here.
} 
```

**Comment by AndrewEdmonds11** [comment]
I see what you're saying and it would make more sense since there is a generator per channel but then how do you handle different channels needing different defaults? Do it in

``` C++
{
//do anything complicated here.
}
```

**Comment by benkrikler** [comment]
Thanks Phill, that's exactly what I was describing.  

> how do you handle different channels needing different defaults?

Probably simplest to write a `GetDefaultParameterValue` method which takes a channel ID and returns the default value using a big switch block.  Make it static in the `PulseCandidateFinder` class and call it from the constructor.  You could add a static map as well, and fill it only once, which would be faster if this is being used very often, but given it's not likely to get called more than once or twice (23 times max), for simplicity I think the first method would be fine.

**Comment by AndrewEdmonds11** [comment]
Cool. I'll reopen the issue then.

**Comment by benkrikler** [comment]
[Woops, it seems ctrl-enter submits the comment so it posted early...]

On second thoughts, the code might be neater with a std::map that's static.

In the header file:

``` c++
private:
void GetDefaultCriteria(const IDs::channel &  ch  , double& start, double& stop); 

typedef std::pair<double,double> StartStopValues;
static std::map<IDs::channel , StartStopValues > fDefaultValues;
```

In the implementation:

``` c++
void PulseCandidateFinder::GetDefaultCriteria(const IDs::channel &  ch  , double& start, double& stop){
   if(fDefualtValues.empty()){
        fDefualtValues[IDs::channel(kMuSc,kNotApplicable)]=std::make_pair(100,200);
        fDefualtValues[IDs::channel(kGe,kFast)]=std::make_pair(150,20);
        ///// fill all the other ones
    }
    start= fDefaultValues[ch].first;
    stop fDefaultValues[ch].second;
}
```

**Comment by AndrewEdmonds11** [comment]
So, I'm getting an odd linker error when I try to use the static map for the default values. Here's the error:

```
obj/PulseCandidateFinder.o: In function `std::_Rb_tree<IDs::channel, std::pair<IDs::channel const, int>, std::_Select1st<std::pair<IDs::channel const, int> >, std::less<IDs::channel>, std::allocator<std::pair<IDs::channel const, int> > >::lower_bound(IDs::channel const&)':
/unix/muons/users/edmonds/AlCap/AlcapDAQ/analyzer/rootana/src/TAP_generators/utils/PulseCandidateFinder.cpp:278: undefined reference to `PulseCandidateFinder::fDefaultParameterValues'
/unix/muons/users/edmonds/AlCap/AlcapDAQ/analyzer/rootana/src/TAP_generators/utils/PulseCandidateFinder.cpp:278: undefined reference to `PulseCandidateFinder::fDefaultParameterValues'
obj/PulseCandidateFinder.o: In function `std::map<IDs::channel, int, std::less<IDs::channel>, std::allocator<std::pair<IDs::channel const, int> > >::empty() const':
/unix/muons/users/edmonds/AlCap/AlcapDAQ/analyzer/rootana/src/TAP_generators/utils/PulseCandidateFinder.cpp:278: undefined reference to `PulseCandidateFinder::fDefaultParameterValues'
collect2: error: ld returned 1 exit status
make: *** [rootana] Error 1
```

And here's what I do:

``` c++
// In PulseCandidateFinder.h
 private:
  /// The channel and parameter value to use
  IDs::channel fChannel;
  int fParameterValue;

  static std::map<IDs::channel, int> fDefaultParameterValues;
  void SetDefaultParameterValues();

// In PulseCandidateFinder.cpp
/// SetDefaultParameterValues()
/// Sets the default parameter values if they haven't been set yet
void PulseCandidateFinder::SetDefaultParameterValues() {

  // Set all the default values for the fast channels
  fDefaultParameterValues[IDs::channel("muSc")] = 300;
  fDefaultParameterValues[IDs::channel("muScA")] = 100;
  fDefaultParameterValues[IDs::channel("NDet")] = 100;
  etc.
```

The line it complains about is the very last line of PulseCandidateFinder.cpp. I'm certain that I'm using the static member wrong but I haven't managed to work out the correct way by googling it. Any help?

**Comment by thnam** [comment]
I think it relates to this:
http://stackoverflow.com/questions/19336236/static-map-as-class-member-in-c
You need to put 

```
std::map<IDs::channel, int> fDefaultParameterValues; 
```

somewhere at global scope or it will not be found

**Comment by AndrewEdmonds11** [comment]
Thanks, Nam. So what I needed to do was declare the map outside of any method:

``` c++
// In PulseCandidateFinder.cpp
/// Need to declare this outside of any method
std::map<IDs::channel, int> PulseCandidateFinder::fDefaultParameterValues;

/// SetDefaultParameterValues
/// Sets the default parameter values
void PulseCandidateFinder::SetDefaultParameterValues() {

  // Set all the default values for the fast channels
  fDefaultParameterValues[IDs::channel("muSc")] = 300;
  fDefaultParameterValues[IDs::channel("muScA")] = 100;
  fDefaultParameterValues[IDs::channel("NDet")] = 100;

  fDefaultParameterValues[IDs::channel("Ge-F")] = 40;
```

**Comment by AndrewEdmonds11** [comment]
This now done in the above commits. Closing...

**Comment by litchfld** [comment]
Yup.  The static declaration in the class says that the class has _access to_ such-and-such variable in the static memory area, (which has one instance per program - hence shared by all instances of the class).  But this does not define the variable, otherwise a new copy would come into being every time the compiler saw the header. So there must be a single definition outside the class which will cause the compiler to provide that piece of memory in the program. 

See [C++FAQlite](http://www.parashift.com/c++-faq/explicit-define-static-data-mems.html). In particular note the follow-up 10.13, which is one of the most specific loopholes written into C++98;
