### ISSUE TITLE
PulseCandidateFinder: parameter values based on sigma above noise

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#104]
After the meeting today, Mark suggested that it would be good to set the parameter values based on the number of sigma a sample is above noise.

This is similar to how the pulse finding was done a while ago. I will think of a way so that parameter values can be based on either the number of sigma or just a normal number.

**Comment by AndrewEdmonds11** [comment]
At the moment, I'm adding a `GetRMSNoise()` function to the `PulseCandidateFinder_InvestigateParameters` module and it occurs to me that maybe one of the following is true:
- that it should be in another class somewhere 
  - I would guess TPulseIsland but we don't want to change this too much in case it breaks the online version of alcapana

or
- we should use the RMS noise we calculate for the LLDQ plots
  - except it's not stored in TSetupData and isn't on a pulse-by-pulse basis

While we discuss this, I'll just implement a function in `PulseCandidateFinder_InvestigateParameters` and then we can always copy it elsewhere if needs be.

**Comment by AndrewEdmonds11** [comment]
As of commit e0c07c3eecf430557bcbfe9e6c45a31109296625, I fill a histogram (per channel) with the RMS of the first 5 samples in each pulse and print the 1-sigma, 3-sigma and 5-sigma values. These are. therefore, averaged over all the pulses in the run.

Continuing along this path would mean if you want to use these n-sigma values, you would have to put them into the modules file by hand.

Ideally, what would be good is if you just set the number of sigma you want and then the pulse finder uses that value. 

This is confusing me a bit since this can be done in two ways:
- store the average RMSs somewhere and then read them in again
- just use the RMS of each individual pulse

These seem conceptually different but I can't think of the consequences. Naively, I think the first method is safer and the second method is easier to implement and run.

**Comment by AndrewEdmonds11** [comment]
I've just talked to Phill about this and we think the best way to do this is to store the RMSs in a text file (and in future a database, I guess) to be read in by the PulseCandidateFinder.

At the moment, I am calculating the RMS noises in PulseCandidateFinder_InvestigatePulses but I think this should be separated into a new module that I'll put in src/plotters/. 

This module will both produce the histograms and write the text file with the 1-sigma value in each channel. Should we decide on a standard location for this? I want to say yes but then we might lock ourselves into using text files when we actually should be using a database.

**Comment by jrquirk** [comment]
Are you averaging the RMS from each pulse, or taking the first 5 samples of all pulses and just taking the RMS of _all_ of those?

**Comment by AndrewEdmonds11** [comment]
So for each pulse, I take the first 5 samples and get the RMS of those and put that into a histogram. So I think the first one...?

**Comment by jrquirk** [comment]
We should histogram the RMS vs  average of the first 5 samples. I'm thinking since some of the detectors are riding on long wavelength oscillations, if the RMS was stable we'd have a good basis for a pedestal-dependent software threshold.

We can include the sqlite code if we want to start using a database. It's only a couple of megabytes.

**Comment by AndrewEdmonds11** [comment]
Ok, that's essentially noise vs pedestal, right? I can easily add that to the new module

**Comment by litchfld** [comment]
> We can include the sqlite code if we want to start using a database. It's only a couple of megabytes.

That's not a bad idea at all. Now that we expect people to use a distributed version of ROOT it is not such a big deal to provide SQLite too, and for AlCap Scale that's a much nicer solution than a full server.

**Comment by AndrewEdmonds11** [comment]
Does this "number of sigma" only make sense for the slow pulse algorithm? Or can it also be used by the fast pulse one?

I want to say no because the noise has nothing to do with the difference between consecutive samples

**Comment by litchfld** [comment]
Sort of.

If each sample is uncorrelated then a given sample (in the absence of signal) is distributed: 
![img](http://www.sciweavers.org/tex2img.php?eq=S_i%20%5Csim%20G%5Cleft%28%20%5Cmu_%5Cmathrm%7Bped%7D%2C%20%5Csigma_%5Cmathrm%7Bped%7D%20%5Cright%29&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0)
Then the difference between (any) two samples is:
![img](http://www.sciweavers.org/tex2img.php?eq=S_i%20-%20S_%7Bi-1%7D%20%26%5Csim%26%20G%5Cleft%28%20%5Cmu_%5Cmathrm%7Bped%7D%2C%20%5Csigma_%5Cmathrm%7Bped%7D%20%5Cright%29%20-G%5Cleft%28%20%5Cmu_%5Cmathrm%7Bped%7D%2C%20%5Csigma_%5Cmathrm%7Bped%7D%20%5Cright%29%20%5C%5C%0A%26%5Csim%26%20G%5Cleft%28%200%2C%20%5Cfrac%7B%5Csigma_%5Cmathrm%7Bped%7D%7D%7B%5Csqrt%7B2%7D%7D%20%5Cright%29&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0) 

But that ignores correlations.  If adjacent samples are correlated the sigma is smaller, if they are anti-correlated it is larger.  We could possibly apply a global fudge factor _k_ to account for that.  But even if we don't it's probably reasonable to assume it's still useful: Ratios should (to first order)  be independent of _k_ and the value can be derived from histograms of noise selected vs cut value.

**Comment by AndrewEdmonds11** [comment]
As of the commit above, this is done with text files. 

PlotPedestalAndNoise exports the mean pedestals and noises for each channel to a text file and PulseCandidateFinder reads them in.

In your modules file, if you specify the option `n_sigma=5` then the default values will be overruled and the pulse finder will set the parameter value to 5*noise.

Next, I will try and do this via an sqlite database. I'll start a new feature branch for this but, @jrquirk , is there a risk that I could screw things up with what you're doing?

**Comment by jrquirk** [comment]
Nope, just make your own database and we can merge them if we want later.

**Comment by litchfld** [comment]
I'd suggest we never merge them - they fill different roles.  If we were using a MySQL server you'd for sure make them different DBs; in SQLite different files makes perfect sense.

**Comment by AndrewEdmonds11** [comment]
This is now done with an sqlite database (see issue #119). There's nothing left for this issue so I'm going to close it
