### ISSUE TITLE
Wildcard checks

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#109]
I'm finding the logic of combining wildcards for Bank Selections and [Iterators](http://alcap-org.github.io/doxygen/AlcapDAQ/develop/classBankIter.html) more convoluted than I expected.  

To make things smoother I'm going to add methods like:

``` C++
bool IDs::channel::isWildCard();
bool IDs::generator::isWildCard();
bool IDs::source::isWildCard();
```

to allow me to quickly determine if I need to be careful about 'selecting' a particular ID.
I'm also going to add some unit tests for this. @benkrikler, will this (particularly adding unit test files) collide with anything you are doing?

**Comment by litchfld** [comment]
I finished this, and the new stuff is in develop as of aec27a3128361ff446e8370a25a6178fb71b9196 .  

Unfortunately it seems a push has exposed that @benkrikler has been working on some ID classes at the same time.  Sorry Ben, you may have to merge these, although hopefully git will be able to do it automagically.

**Comment by benkrikler** [comment]
Thanks for the heads up. I'll merge this in to what I'm doing...
