### ISSUE TITLE
Memory issues when looking through raw data tree files

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#11]
I have been checking the memory usage, as I have mentioned earlier.  The program is a very simple one that reads the TGlobalData tree copies it to a new file and adds friend trees with simple integer branches.

It seems that the virtual memory usage grows in the first ~200 events to around 2GiB, sometimes larger, and then drops back to about 400MiB after another few hundred events, where it then stays.  The physical memory usage stays at a few hundred MiB all the time:

E 000    R/V(MiB) 060   /  191    tc/tu(ms) 60   / 68
E 050    R/V(MiB) 145   / 1381   tc/tu(ms) 2150 / 3605
E 100    R/V(MiB) 267   / 2497   tc/tu(ms) 2110 / 3399
E 150    R/V(MiB) 358   / 2591   tc/tu(ms) 2149 / 3625
E 200    R/V(MiB) 420   / 2662   tc/tu(ms) 1940 / 3256
E 250    R/V(MiB) 196   /  307    tc/tu(ms) 2160 / 3622
E 300    R/V(MiB) 256   /  378    tc/tu(ms) 1939 / 3256
E 350    R/V(MiB) 323   /  448    tc/tu(ms) 2110 / 3574
E 400    R/V(MiB) 382   /  518    tc/tu(ms) 2359 / 4125
E 450    R/V(MiB) 173   /  284    tc/tu(ms) 1660 / 2643
E 500    R/V(MiB) 255   /  378    tc/tu(ms) 2509 / 4245

So as long as the job does not break any hard limits on the node this is fine, but i don't really understand why it should need so much resources initially. My guess is that this is memory fragmentation caused by a lot of vector::push_back() but i'm not sure.  In particular there does not appear to be any such issue if one starts half way through the file which is odd.  

I don't propose to investigate this any further for now, but this remains as a record in case the problem becomes more urgent.

**Comment by jrquirk** [comment]
And to the record I send it.
