### ISSUE TITLE
Fix the definition of a TDetectorPulse

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#111]
Similar to the discussion we had over TAnalysedPulses we need to fix the contents of TDetectorPulses and what we understand these objects to mean.

**Comment by AndrewEdmonds11** [comment]
Here's what I've always thought the idea was:
- a TDetectorPulse represents a detector, this it means it will contain either
  - two TAnalysedPulses (one for a a fast and one for a slow channel), or 
  - a fast channel only (for the scintillators)
- pairing up of these pulses would depend on the time correlation between the two
- we would use them like this:

``` c++
TDetectorPulse* SiL2;
SiL2->GetTime(); // would return the time of the fast TAP (if this is the one that gives us better resolution) 
```

Another thing to think about is do we want to convert the four thin Si channels into one? i.e. Do we have SiL1-1-F, SiL1-2-F, SiL1-3-F and SiL1-4-F become SiL1-F and we have SiL1-F and SiL1-S as the TDetectorPulse? Or do we keep them separate and have TDetectorPulses of SiL1-1, SiL1-2- etc. that we combine later

**Comment by thnam** [comment]
If we raise thresholds on fast silicon channels to remove noise, the number of fast pulses would be much fewer than that of slow pulses. That means another TAP type with just slow channel; or we can just discard the slow ones and count that as inefficiency.

**Comment by benkrikler** [comment]
I put this up intending to comment straight away but got pulled away.  What Andy describes is exactly how I viewed them and how they are implemented currently.

The current contents of a TDP is:

``` cpp
  TAnalysedPulse* fFastPulse;
  TAnalysedPulse* fSlowPulse;
  std::string fDetName;
  bool fCheckedForPileUp;
  bool fPileUpSafe;
```

Those last fields I added recently, the main intention was to flag whether a pulse has been created by a generator that checks for pile-up and if so, whether or not this pulse is known to not suffer from it.  This pile-up refers to multiple TAPs on one channel (most likely the fast one) that could correspond well to the TAP on the other, not whether or not a TAP came from a waveform that is suspected to be pile-up.

The `fDetector` field can be replaced by a `IDs::source` similarly to what we have in a TAP.

`GetTime()` returns the time of the fast pulse if there is one, else the slow.  The reverse is true for `GetAmplitude`.  There are also Getters to get these values by specifying the fast or slow chanel:

There is no mention of energy in this class, and I have similar getters for the integral, as for the amplitude.  Perhaps I should remove the amplitude and integral methods in favour of just `GetEnergy`.  For now, with no calibration constants, this would just be the amplitude or integral.

Related to this:  where in the chain does calibration sit?  Between TAPs -> TDPs or within TDPs themselves, or otherwise?

**Comment by benkrikler** [comment]
@litchfld, if TDPs just contain pointers to the parent TAPs, does that cause a persistency issue?

**Comment by litchfld** [comment]
> @litchfld, if TDPs just contain pointers to the parent TAPs, does that cause a persistency issue?

Possibly.  The model I had in mind was that all stages were more or less equivalent from the point of view of processing.  As described this certainly breaks that assumption because TDPs are useless on their own. But that is not very broken... it presumably just means that writing out a TDP forces the writing out of the TAP.  

What I am not sure about is if the default streamers do a sensible thing in this case.  If you have a pointer-to object you can either write that object out as if it were a member (I/O equivalent to a deep copy) or a reference (I/O equivalent of a shallow copy).  ROOT can do both i think, but i've never needed to know exactly what it does in either case.

For instance, if I save a TDP to file does it force the associate TAP to be written as well? Of course that means everything has to stay in memory, until the end of the event, but does it also mean I mustn't write the TAP to buffer (`TTree::Fill()`) until the end of the event?   And does writing out two TDP that both refer to the same TAP work ok? And how does the read operation work?  

I don't think any of these are insurmountable, I just have never looked into streamers close enough. I know there is a TRef Class that works round some of the trickier use cases, but I don't know if this counts as tricky or not...

**Comment by litchfld** [comment]
I wondered (and perhaps this is too sophisticated an analysis): if you have a TDP that has two contributing TAPs you essentially are doing a function of two variables, eg for time:
`t[d] = fn( t[f], t[s] )`
and for energy:
`E[d] = fn( E[f], E[s] )`.
We are assuming that these functions are simple: 
`fn(E[f], E[s]) --> E[s]`
for example. But they might not be, so you might want to store the result, if it doesn't cost much space.

**Comment by litchfld** [comment]
> Related to this: where in the chain does calibration sit? Between TAPs -> TDPs or within TDPs themselves, or otherwise?

If it sits in the TDP it implies the TDP must 'know' the generator that was used for the TAP. If my TAP algorithm uses  [_average of N bins_] to estimate energy, that could be subtly different from [_max bin_], and wildly different form [_integral_] or [_template fit_]. Time offsets are possibly even worse, depending on whether you care about time precision down to the level at which timewalk effects are.
So I guess I assumed that either: 
- Some calibration would most naturally come in the TAP generator (but that we would effectively have all calibration constants =1 for now). 
- We would very quickly decide on a combination of TAP generators and configs for all pulses.

**Comment by litchfld** [comment]
As for referring back to the TAPs, could we store the parent channel/generator/config (i.e. branch name), and offsets then just fill the pointers the first time they are used?

**Comment by litchfld** [comment]
> If we raise thresholds on fast silicon channels to remove noise, the number of fast pulses would be much fewer than that of slow pulses. That means another TAP type with just slow channel; or we can just discard the slow ones and count that as inefficiency.

There will always be some that don't match---probably in both directions---although I would hope that with the right thresholds the vast majority do match (because we want that the vast majority of pulses are at least from the detector, even if they are not signal.)

**Comment by benkrikler** [comment]
This is completed now.  TDPs follow very closely the approach for making TAPs. One TDP contains:
- A pointer to a fast channel's TAP 
- The ID of this fast TAP
- The source of this fast TAP
- The above 3 fields for a corresponding slow channel
- Methods to get any of the TAP fields of the parent TAP.  For energy, amplitude, integral and pedestal this defaults to using the slow channel. For timing it defaults to the fast.

The fact we store the TAPs as pointers may cause grief when we write the TDPs out, so when that point comes we may want to get clever or swap the pointers to TRefs or something.  With both the source and TAP IDs we should have enough information to read the TDPs back into rootana but it might be tough to access things from a tree in the current form.

MakeDetectorPulses saw quite a few changes including switching gDetectorPulseMap to use source IDs as the key rather than strings.  At the moment the only generator is the one based on Phill's algorithm.  MakeDetectorPulses can only handle a single generator at a time, but as soon as we have more than one I will change this to behave similarly to MakeAnalysedPulses.

There is also a new plotter to characterize TDPs which includes plotting amplitudes for fast and slow channels together.

The CreateModule.sh script can now also make TDP generators.
