### ISSUE TITLE
Q&A readytalk session Wednesday 25th June

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#112]
I'm putting this ticket up to help me prepare a bit and to give us all some idea of what we need to cover. If whilst looking through the [walkthrough](https://github.com/alcap-org/AlcapDAQ/wiki/rootana-create-module) you find things you'd like me to cover, feel free to mention them on this ticket.

**Comment by benkrikler** [comment]
Erm, so, a bit embarrassing, but I forgot that I'd promised to go with my gran to the hospital on Wednesday so would we be able to reschedule?  Tuesday, Thursday or Friday would work for me, as would Monday, though I'm not sure if that gives enough time for people to try things out.  Sorry for the inconvenience everyone..

**Comment by jrquirk** [comment]
Friday would work best for me, because I want to struggle through it some and it gives me something to look forward to at the end of the week. Thursday works, too. I'd prefer not Tuesday.

**Comment by thnam** [comment]
Any day is fine with me.

**Comment by benkrikler** [comment]
So are we going to have two meetings this week?  One for analysis, another for the tutorial?  Shall we say Friday for the tutorial at the time of the general meeting?

**Comment by jrquirk** [comment]
It does not matter to me, and that sounds doable.

**Comment by benkrikler** [comment]
So what's the verdict with this?  I'm really happy to run a session, but no one has got back to me.  Does this mean it's not needed or that people haven't had time to try things out?

**Comment by AndrewEdmonds11** [comment]
Sorry, we decided in the meeting that it would be Friday at the normal time.

**Comment by benkrikler** [comment]
And is this to be a Q&A session, where you fire questions at me or do you want me to prepare a demo?

**Comment by AndrewEdmonds11** [comment]
I don't think we decided. It can't hurt to have something prepared... 

What are other people expecting from this?

**Comment by thnam** [comment]
I'm not so sure myself ...
Yesterday Aji was having problem with compiling rootana.

**Comment by AndrewEdmonds11** [comment]
Aji, sent me an e-mail to say that he managed to get it working after the meeting. I'm hoping that people will have had a little play with the code beforehand but maybe other people are a lot busier than me...

**Comment by benkrikler** [comment]
> It can't hurt to have something prepared... 

...

>  but maybe other people are a lot busier than me...

I'm stretched between writing the COMET simulation, an ECAL pile-up study, this alcap work, a poster presentation on Monday and supervising two summer students right now.  I can put something together, but you need to tell me that you need this first, I'm afraid.

**Comment by AndrewEdmonds11** [comment]
Sorry, Ben. I knew you were busy but didn't realise it was that bad!

Let's just make it a Q&A session tomorrow, then. There's a walkthrough on the wiki so I don't see how much a demo would add.

Everyone get your questions ready

**Comment by litchfld** [comment]
Here are questions i came up with, i'll update as I have more:
- At what point do we have access to TGlobalData and TSetupData?  when the module is constructed, or not before BeforeFirstEntry()?

**Comment by jrquirk** [comment]
Here are questions I came up with:
- Can we pass options to TAP generators in the alias way? (I think not, which works fine, but wanted to check)
- Related to Phil's question, the TAPs will have access to gSetup through the global pointer (and are not expected to access gData directly I imagine), but the Modules get gData/gSetup; should we not be using these and just rely on the global one?
- How does one access TAPs from a module? Say, for instance, I made 3 TAPs for every TPI and wanted to plot a 3D histo of one variabe from all of them), how would I request a TAP from a certain source made form a certain TPI?

**Comment by AndrewEdmonds11** [comment]
Here are my questions, which may overlap with some of the ones above:
- what's the correct way to loop through detectors and pulses and will it change in the near future? (related to both Phill's and John's about accessing gData)
- how do we add just one variable to a TAP (e.g. just the time from a specific time algorithm) and then have the others (e.g. amplitude) filled by some other algorithm?
- what's the correct way to use the IDs::channel class?

**Comment by benkrikler** [comment]
@thnam, @dmalexan and @ajidaniel , i think you three have worked with rootana the least and could potentially benefit the most from tomorrow.  Do you have any particular questions you'd like us to cover?

For everyone else, thanks for putting things down, that helps give me a sense of where we're all at, even though I'm sure we'll find new things when we go through it tomorrow. 

One thought though:  some of these points feel more like suggestions than questions.  We shouldn't see what we have as a fixed setup, if you can think of improving things then we can always change it.  Tomorrow is about helping people use what we've got though, so perhaps if there's a suggestion for an improvement or extension then posting that as an issue on github instead might allow us to focus more on what exists already.

**Comment by thnam** [comment]
@benkrikler I have written several plotter modules, mostly adapting old code to the new framework. So far it works for me. Here are a few questions:
- Where is the dependency between rootana and alcapana? We still need to compile the latter first.
- I see that all the options from the MODULES file are parsed as string, then converted to other data types. Is there a documentation for that?
- Each of plotter module has two constructors, one takes normal parameters, and one takes an option string. Both are using the same code, except for arguments parsing. Can we just implement one, then use assignment/copying in the other?
