### ISSUE TITLE
Better Git flow

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#113]
I was getting fed up with git flow and thought I'd have a look at updating things a bit myself.  It turns out that I wasn't the first person to think this and there are many forks of the original git flow.

So I'm going to switch to this version: https://github.com/petervanderdoes/gitflow, and thought I'd let people know in case they also wanted to.  It sticks to the same git flow branching model so I don't think this should do anything to the repository history differently to the older version.

**Comment by benkrikler** [comment]
Most notably, this newer version gives us proper help commands:

```
$ git flow feature publish --help
usage: git flow feature publish [-h] [<name>]

    Publish feature branch <name> on origin.
    When <name> is omitted the current branch is used, but only if it's a feature branch.

    -h, --help            Show this help
    --showcommands        Show git commands while executing them
```

**Comment by jrquirk** [comment]
This was very helpful.
