### ISSUE TITLE
Output file directory structures

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#115]
I'm trying to tidy up the way we create directories to store things in each module.  At the moment it's preventing us from creating multiple instances of a given module.  Instead of each module creating its own directory and then needing to return to the top-level directory of the output file, I'm going to move this into the ModulesNavigator, who will now be responsible for giving each module a directory to store things in.

Questions for everyone:
1. Currently, the output file is made in main and only accessed by ROOT behind the scenes.  @litchfld, how will I be able to access the output file from the event navigator?  
2. Do we want a separate output file for histograms to the TAPs, TDPs and TMEs?  That was how alcapana worked, do we want the same approach here? Should this be optional with default being write everything to one file?
3. At the moment, I'm expecting that should we run with multiple instances of a module, both instances will share the same directory.  I could create a sub-directory for each instance but how would I name it?  If I use the options given for that instance, it could make life harder if we want to access the histograms in subsequent scripts (like the picture book macros).  If I don't make sub-directories, then each histogram or object that gets stored in the directory would need to be uniquely named compared to objects coming from any instance of the module, which could be trickier in the code.  What do we prefer? (my preference is no sub-directories by default).

**Comment by AndrewEdmonds11** [comment]
> Do we want a separate output file for histograms to the TAPs, TDPs and TMEs?

I say, no. I think it's best if we keep a single output file and not have a load floating about. We can always write ROOT macros to go into the relevant subdirectories and pull out the histograms we want.

>  I could create a sub-directory for each instance but how would I name it?

Can you use the alias name? That has to be different for each instance, right? Also, do they need to be subdirectories? Can you not name the directory with the alias name?

My only worry would be people using different aliases but this shouldn't be a problem if we use the same modules file for production (like we did for alcapana)

**Comment by litchfld** [comment]
> Currently, the output file is made in main and only accessed by ROOT behind the scenes. @litchfld, how will I be able to access the output file from the event navigator?

I hadn't though of that, but it's easy enough to provide a method:

``` C++
/// Might be in the tree file,or a different one. Could also be a subdirectory.
TDirectory* GetHitstogramTLD();
```

We could also have: 

``` C++
/// Can be in tree file or separate file, depending on string. I think ROOT has a convention for this.   
int SetHistogramTLD(const char*);
```

**Comment by litchfld** [comment]
> At the moment, I'm expecting that should we run with multiple instances of a module, both instances will share the same directory

I think the config name makes sense here - these have to be unique, and must exist. The Generator ID could also provide a method to give the appropriate name. And if you don't care you can always use `TDirectory::GetListOfDirectories()` or whatever it's called.

**Comment by jrquirk** [comment]
I like aliases/config names, too, because those have to be unique by construction.

But the modules file does not require you to use an alias, right?

**Comment by benkrikler** [comment]
Commit 40d930220673e69524f51a70f2fd4d87c681c541 implements all of this.  If only one instance of a module runs then a directory is created with the name of the module (unless the modules says in it's source code that it doens't need a directory).  If two or more instances of a module are used then a sub-directory of this is made for each instance, using the modules file alias as the sub-directory name.

I am also now storing a copy of the options given to the module as a TObjString in the modules directory (if it has one).

> But the modules file does not require you to use an alias, right?

That's true if you run with a single instance of a module.  Once you run with more than one I felt we should identify each instance so we require an alias for each module.

### Future work with the root files

My one hesitation with this fairly flexible directory structure is how it will impact future macros that handle the rootana output, in particular I'm thinking of the picture book stuff. It would be a nuisance if every change to a modules file requires a matching change in the macro. My guess though is that by that point we will be running with a standard set of MODULES files and so in reality the directory structure won't change too much. 

I think this is finished now, so I'm closing this, but as always feel free to comment still..

**Comment by jrquirk** [comment]
> I am also now storing a copy of the options given to the module as a TObjString in the modules directory 

Saving the options is a really good idea for forensic purposes. I can't believe we didn't think of this before.

We could also store the ODB in the alcapana ROOT file.

**Comment by thnam** [comment]
I was thinking the same. I couldn't find a MODULES file we used for the alcapana in the run ...

**Comment by benkrikler** [comment]
> We could also store the ODB in the alcapana ROOT file. 

Doesn't  TSetupData do this for the most important values?

**Comment by litchfld** [comment]
> My one hesitation with this fairly flexible directory structure is how it will impact future macros that handle the rootana output,

That why I thought it better to _always_ put the config string into the directory structure. At the moment a macro that looks for one specific module output must do something different if someone simply adds another version, which is weird. You'd need to do something like: 

``` C++
//I want to get "Noodle_Module" with "default" configuration.
// (Assume I am already in the histogram TLD)

TDirectory* wd = TDirectory::CurrentDirectory();
wd = wd->Cd("Noodle_Module");
if (wd.GetListOfDirectories().Size() > 0){
  wd = wd->Cd("default");
}
```

Instead of: 

``` C++
//I want to get "Noodle_Module" with "default" configuration.
// (Assume I am already in the histogram TLD)

TDirectory::CurrentDirectory()->Cd("Noodle_Module/default");
```

**Comment by litchfld** [comment]
I'm confused now about the difference between aliases and config names.
Is the alias the same as the config name stored by the Generator ID?

**Comment by benkrikler** [comment]
I think the configuration string is more likely to change than an alias, especially if we're tuning parameters with each run.  You're example is only good if we run with the default configuration, but if there were, for example, 3 parameters which were changed each run, it would be much easier to keep an alias fixed.

> I'm confused now about the difference between aliases and config names.
> Is the alias the same as the config name stored by the Generator ID? 

The Generator ID's config string is just  a string that should uniquely identify the configuration.  At the moment it's not  even being filled.  What's more, it's a generator ID, and not a Module ID.  These are implemented in much the same way, but are not the same.  Another issue with using generator options themselves is that this could contain any particular non-filename safe character.  This discussion should go on a separate issue I think.  I'll open one in a minute...

**Comment by litchfld** [comment]
One other question.  If we pull in a load of LLDQ modules, and/or write some slightly less LL ones...  Should we put them all as subdirectories of a common `data_quality` directory? I can't quite see how to do with that with the module structure at present.

We might not bother, say if the DQ modules were not usually run.
