### ISSUE TITLE
LLDQ: Check that the muScTDiffs now align with our ODB corrections

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#117]
Now that we have muScTDiff plots with the ODB time shift corrections we should check that they now all align. Nam, I think you did the muScTDiff plots before, so could you check them for us, please?

**Comment by thnam** [comment]
Sure, I am checking that.

**Comment by thnam** [comment]
It seems that the time shifts for Ge-S and Ge-F were wrong, about +9 µsec off in almost all datasets:
![screen shot 2014-06-24 at 10 39 10 pm](https://cloud.githubusercontent.com/assets/4444606/3371791/ff45ebf8-fba4-11e3-8ed3-f2793c1342d1.png)

For the Al100 dataset, it is worse: some runs were corrected, some weren't:
![screen shot 2014-06-24 at 10 40 26 pm](https://cloud.githubusercontent.com/assets/4444606/3371819/4c43650c-fba5-11e3-8657-635db20e6323.png)
![screen shot 2014-06-24 at 10 42 04 pm](https://cloud.githubusercontent.com/assets/4444606/3371822/5ddfb86a-fba5-11e3-8b48-5fb896c31042.png)

**Comment by thnam** [comment]
```
• Al50a w Ndet:
◦ Ge-F, Ge-S w time shift: seems wrong, + 9µs
◦ Sc: good
◦ SiL1, SiR1: too few hits to show any pattern
◦ SiL2, SiR2: seems good

• Al50a wo Ndet:
◦ Ge-F, Ge-S: + 9µsec
◦ Sc: ~0
◦ SiL1, SiR1: seems ok wherever a pattern is visible
◦ SiL2: good
◦ SiR2: good

• Al50b:
◦ Ge-F, Ge-S: + 9µsec
◦ others are good after time shift corrections

• Al100:
◦ p 172, 173: time shifts in Ge-F, Ge-S are not consistent
◦ SiR2, SiL2: about -2 µsec after time shift

• Si16p:
◦ Ge-F, Ge-S: +9µsec
◦ others are good

• SiR:
◦ Ge-S: #125  , +9 µsec where time shift is applied
◦ SiL1-2-F, SiL1-3-F: 1st tranche noisier?
◦ SiR2-S: -1 µsec
◦ others are good

• SiR2 1%: same problem with Ge-S, Ge-F
• SiR2 3%: same problem with Ge-S, Ge-F
```

**Comment by AndrewEdmonds11** [comment]
Thanks, Nam. 

The fact that some runs were corrected in Al100 and some weren't is strange (especially because it's different runs in the two channels).

When I edited the production scripts, I made sure that everyone's ODBCORRFILE was hard-coded to be John's.

(in batch_alcapana_prod-run-3.sge):

```
ODBCORRFILE="/gpfs/home/quirk_j/data/corr$RUN.odb"
```

However, I didn't change ODBCORRDIR but this is not used anywhere else it seems...

Any ideas, John?

**Comment by jrquirk** [comment]
I have no ideas as of yet. I'll have a look into it.

**Comment by jrquirk** [comment]
I haven't found the problem yet.
- [x] Checked the corr files against just an eyeball of the histogram, and they seemed right. Additionally reran ODB check and got the same results
- [x] Checked the timestamps on the hist files, and they all look good
- [x] Check the batch script
- [ ] Check the timeshift loading in alcapana

**Comment by jrquirk** [comment]
The corrections aren't getting loaded. We can see it in the log files. I'm looking into it further,

**Comment by jrquirk** [comment]
Also I can't check the dump files because they weren't written. Everyone is linked to my ODB directory, which is also where I have the ODB files. I've changed it so that the dump directory and all files in there are writable by anyone in the unx-alcap group.

**EDIT**: Though people should test this by typing something like `touch ~/data/odb/dump/$USER.text`. Also, any files created in my directory should still count towards your quota, so don't try anything funny to try and get me kicked off Merlin.

**Comment by jrquirk** [comment]
Simple problem. see [here](https://github.com/alcap-org/AlcapDAQ/blob/alcapana_prod_run_3.1/analyzer/batch/scripts/production-run-3/batch_alcapana_prod-run-3.sge#L63) should have an extra `corr` in there. I'll upload a fix to close this issue.

```
ODBCORRFILE="/gpfs/home/quirk_j/data/corr$RUN.odb"
```

This still doesn't completely explain why some runs had the corrections loaded and some didn't, thought it's not hard to imagine they're related.

**Comment by AndrewEdmonds11** [comment]
I think this means we have to do another alcapana run but we can discuss it in the meeting

**Comment by litchfld** [comment]
This is basically the sort of thing I was worried about when I was making a fuss about having optional correction files.  Is it possible to make things blow up immediately if the script isn't found?
