### ISSUE TITLE
Reproduce some LLDQ plots for Rootana

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#118]
In Phill's last [elog](https://muon.npl.washington.edu/elog/mu2e/Analysis-R13/138), he mentioned that anyone who wants to get some practice implementing a new module could write one of our LLDQ alcapana modules in the new rootana framework.

Here's the list of the modules with a short explanation and a link to the code, so that you have an idea of what needs doing. (Note that I've left some modules out because I don't think they'll be possible to implement in rootana but feel free to correct me):
- [MDQ_Amplitude](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/src/data_quality/MDQ_Amplitude.cpp)
  - plots the amplitude of each TPulseIsland
- [MDQ_DigitizerOverflow](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/src/data_quality/MDQ_DigitizerOverflow.cpp)
  - plots the fraction of TPulseIslands that had a sample value above the maximum possible ADC value for that digitiser
- [MDQ_IslandCounter](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/src/data_quality/MDQ_IslandCounter.cpp)
  - counts the number of TPulseIslands in each MIDAS event
- [MDQ_IslandLength](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/src/data_quality/MDQ_IslandLength.cpp)
  - plots the length of each TPulseIsland in terms of number of samples
- [MDQ_IslandTimestamp](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/src/data_quality/MDQ_IslandTimestamp.cpp)
  - plots the timestamp of each TPulseIsland in nanoseconds
- [MDQ_PulseShapes](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/src/data_quality/MDQ_PulseShapes.cpp)
  - produce the pulse persistency plot we had at the run

Feel free to sign up for the modules you want to do here

**Comment by litchfld** [comment]
I'm gonna take a crack at MDQ_IslandLength.

**Comment by litchfld** [comment]
Also i'll suggest stuff like this goes in a new directory `src/data_quality`.

**Comment by AndrewEdmonds11** [comment]
I'm just going to close this. We have most of what we want (amplitudes etc.) and can open new issues if we want something new
