### ISSUE TITLE
Trend plots for production 3 online

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#120]
I've put the latest picture book plots from Andy onto their web page:
http://www.hep.ph.ic.ac.uk/~bek07/alcap/trend_plots/production_3/by_bank.shtml
http://www.hep.ph.ic.ac.uk/~bek07/alcap/trend_plots/production_3/by_detector.shtml
http://www.hep.ph.ic.ac.uk/~bek07/alcap/trend_plots/production_3/one_plot.shtml

The old links are still active, just change production_3 to production_1 or production_2 in the URL.

The options button down the side will only effect some plots so don't be surprised if many plots seem to disappear. I can change it so that this doesn't happen, but I don't think I have time right now.

As always, requests / bugs / feedback are all welcome.

**Comment by jrquirk** [comment]
Thank you.
