### ISSUE TITLE
Uninitialised variable warnings.

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#121]
On [line 54](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/PrePulse.cpp#L54) of TAP_generators/PrePulse.cpp

My compiler emits warnings about using uninitialised variables `height`,`loc` and `start`. A quick read through makes me think there is no problem, but there's a fair chance the compiler is better at logic than I. 

I'm not sure what to put as defaults though, anyone want to take a shot?

**Comment by AndrewEdmonds11** [comment]
PrePulse is part of John's old code that I've moved into a legacy folder in my branch. So I wouldn't worry about it...

**Comment by litchfld** [comment]
OK. I'll just set them to zeros to make the compiler happy.

**Comment by jrquirk** [comment]
Before we close this issue, can I ask a related question which is just to delete all my old template fitting stuff since it's been migrated by Andy?

I'll be getting rid of, in the rootana/src/TAP_generators directory
- PrePulse
- MakeTemplate
- PulseTemplate

**Comment by AndrewEdmonds11** [comment]
So I don't think I've migrated everything yet, which is why I put it in its own subdirectory. We'll delete it when I think we have everything (I know we can always resurrect things with version control but it's just easier to have the file there...)
