### ISSUE TITLE
6.1.1 and 7.1.1) SiL1-2-F disconnected?

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#123]
I remember reading in the elog while writing the beam report that it was disconnected before these runs because it was very noisy.

I will find the relevant elog and then close this issue

**Comment by ajidaniel** [comment]
Andy, I remember that elog, it is #698 on RunPSI2013 elogbook.

**Comment by AndrewEdmonds11** [comment]
Thanks, Aji. Here's the [link](https://muon.npl.washington.edu/elog/mu2e/RunPSI2013/698) and the relevant quote is:

> The SiL1-2-F is disabled due to very bad noise
