### ISSUE TITLE
LLDQ 5.1.3 - Wrong clock frequency for Ge-S in the first tranche

### ISSUE THREAD

**Issue by thnam** [alcap-org/AlcapDAQ#125]
As mentioned in the LLDQ v.3 (5.1.3)  the clock frequency was wrong for runs from 2091 to 2103. I looked at the time difference between two consecutive pulses on the Ge-S channel:
    - in early runs:
![screen shot 2014-06-24 at 10 52 12 am](https://cloud.githubusercontent.com/assets/4444606/3366331/d3cc44f6-fb43-11e3-8e1b-f656785f0ff9.png)
- in later runs:
  ![screen shot 2014-06-24 at 10 52 43 am](https://cloud.githubusercontent.com/assets/4444606/3366330/c8fb8578-fb43-11e3-90b0-9f1105c4fbd2.png)

The peak at about 2 ms in later runs is consistent with the reset pulses observed in the run using an oscilloscope
(e.g https://muon.npl.washington.edu/elog/mu2e/RunPSI2013/403). But the peak shows up at 320 µs in the first tranche, which means the actual clock frequency should be about 6 times higher. The factor of 6 can also be seen from Figure 27 where the time stamps end at about 20 ms for the first tranche, and 120 ms for the second tranche.

Frequencies from the ODB dumps correctly reflect the factor of about 6:
    - run 2091 - 2103: 1e+08
    - run 2120 (second tranche): 1.6129e+07

But the correction file corr02091.odb (and others in the first tranche) sets the frequency for Ge-S to be 1.6129e+07 (see the SamplingFrequency [32]). I think that we can just correct the correction files (...) and rerun these 13 runs.

**Comment by thnam** [comment]
@jrquirk Could you also check corrections in runs 2091-2103.

**Comment by jrquirk** [comment]
They all look good. You can see in the [ODBCheck](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/odb_check/src/ODBCheck.cc#L207), right before outputting the corrections, the [UniqueFixes](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/odb_check/src/WireMap.cc#L74-L89) function is called.

**Comment by jrquirk** [comment]
Just for consistency, this is related to #117 and has been fixed (seemingly).
