### ISSUE TITLE
Cannot access FTP server

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#128]
I'm getting problems where I cannot connect, but not the standard "too many users connected with same name" error. Are other having the same issue?

**Comment by benkrikler** [comment]
Yes I am.  I was nervous it was my setup though.  It's pulled one or two files, but very few....
The errors I see look like:

```
--2014-06-25 23:07:24--  ftp://---------.psi.ch/----/run2013/run03202.mid
  (try: 8) => “run03202.mid”
Connecting to ---------.psi.ch|192.--.---.--|:--... connected.
Logging in as ----- ... ^[[B
Error in server response, closing control connection.
Retrying.

```

 (I've removed some of the url and ip addresses)

**Comment by AndrewEdmonds11** [comment]
So I've just checked the progress of my runs and it was running fine until run 2146 when I then get the following errors:

```
Downloading run 2146...
--2014-06-25 20:30:41--  ftp://-----------.psi.ch/--/run2013/run02146.mid
           => “run02146.mid”
Resolving archivftp.psi.ch... 192.--.---.--
Connecting to archivftp.psi.ch|192.--.---.--|:--... connected.
Logging in as mucap ...
Login incorrect.
```

which is weird because it should be using the same password as before....

**Comment by jrquirk** [comment]
I get the error Ben gets. I can't even get to the point of entering a user/passwd combo using ftp. I get error 421, which apparently is some sort of [try again later](http://en.wikipedia.org/wiki/List_of_FTP_server_return_codes) response.

**Comment by joegrange** [comment]
FWIW mine worked fine.

**Comment by AndrewEdmonds11** [comment]
So, I've tried re-running my script and I get the same error as Ben. I guess the archive is down or something

**Comment by dmalexan** [comment]
Mine worked fine for the common runs but when I started my specific runs I got 

Resolving archivftp.psi.ch... 192.33.120.36
Connecting to archivftp.psi.ch|192.33.120.36|:21... connected.
Logging in as mucap ... 
Error in server response, closing control connection.
Retrying.

Repeated about 20 times per run then moved on.

**Comment by jrquirk** [comment]
Let's pause production and give it until our respective tomorrows.

**Comment by joegrange** [comment]
I deleted and tried to re-run the common runs and now I get the same error as you folks, probably an archive issue as Andy suggests.

**Comment by thnam** [comment]
It's the same to me ...

**Comment by litchfld** [comment]
I'm trying now.  I got two of the common files, but  it takes a very long time to start the download.  Maybe one of the tape robots is on holiday?

The system doesn't seem healthy, although I suppose it could just be busy,and if it had a problem last night there might be a backlog. I'm not going to start my main batch now; I'll try the common files again in a few hours.

**Comment by ajidaniel** [comment]
Same issues here, though I get a "connection refused error"
_Downloading run 3740...
--2014-06-26 12:23:09--  ftp://archivftp.psi.ch/mu2e/run2013/run03740.mid
           => “run03740.mid”
Resolving archivftp.psi.ch... 192.33.120.36
Connecting to archivftp.psi.ch|192.33.120.36|:21... failed: Connection refused._

Will wait like everyone else...

**Comment by jrquirk** [comment]
That error looks slightly different, and may be because too many people were connected. It seems to be working now as Phil said.
