### ISSUE TITLE
Wiki: Rootana Tutorial

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#13]
When the rootana framework has been finished, we should write a tutorial on the wiki

**Comment by benkrikler** [comment]
I forgot to update this ticket last week.  There's a script in rootana/scripts which you can use to create a skeleton modules file.
Just do:

```
cd analyzer/rootana/scripts
./CreateModule.sh NameOfMyModule
```

For more help, just run with no arguments.

The skeleton is well commented so it should be a good guide to get going.

**Comment by benkrikler** [comment]
I've also updated the rootana wiki: https://github.com/alcap-org/AlcapDAQ/wiki/Rootana
which will continue to evolve.

**Comment by benkrikler** [comment]
And the first attempt at doxygen documentation is up at:
www.hep.ph.ic.ac.uk/~bek07/alcap/AlcapDAQ_documentation/rootana/html/annotated.html
Although this might move ( #54 ).

**Comment by benkrikler** [comment]
A first draft at a rootana modules tutorial is on the wiki:
https://github.com/alcap-org/AlcapDAQ/wiki/rootana-create-module
Comments and questions are more than welcome!

If anyone is thinking of beginning working with this, I might wait until the event navigator has a defined interface, before I go too far implementing anything though.

**Comment by benkrikler** [comment]
I think this can be closed.  The beginnings of the wiki is up and doxygen is building online documentation with nightly updates. 

If you have a request or find things unclear, feel free to comment this or open a new, more specific issue.
