### ISSUE TITLE
Generator IDs:  Whats the configuration string

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#130]
Two issues have been raised in other issues:
- What do we actually use as the configuration (from issue #115 )
- Can we use the alias structure for generators in the same way as for MODULES (mentioned from #112 )

The configuration strings could potentially be used as branch names which puts a limit on the range of characters that these strings can contain (issue #89).  As the configurations could conceivably require almost any character this might be too big a restriction, or else require scrubbing of the configurations before they're converted to strings.

An alternative then is to allow generators to be given an alias much like the Modules.  The aliases would provide a unique identifier within a run and be restricted to using file-name safe characters.  We could then store a map of aliases to configurations within the root file for debugging purpose.  

An alternative to aliases as a string would be to use a single int.  This might be less readable though but would be easier to implement as we don't need to change the modules file.

**Comment by benkrikler** [comment]
@litchfld's recent comment on issue #89:

> > The generator configuration strings might need more thought as we'd need to consider how we handle funny characters in the options themselves.
> 
> Easy, you ban them. Test for the presence of the banned delimiter when the module instantiates itself and if a verboten sting comes up you print an accusing message and terminate.  We ought to fix the delimiter soon though, if you change it, old files won't read in.

I think that is far too restrictive and not necessary if we use aliases.  Also, when we would then string together these configuration key-value pairs it would be very difficult or else unreadable if we do this with only filename valid characters.

**Comment by litchfld** [comment]
> The configuration strings could potentially be used as branch names which puts a limit on the range of characters that these strings can contain

Make that definitely. The branch name is not really there for the benefit of humans - it's there for the I/O to parse.

**Comment by benkrikler** [comment]
Then we don't need to restrict configuration itself to using filename safe characters, just have a method to strip or replace the bad ones.  If we don't care about them being human readable, an alias, an int or a scrubbed out configuration string are all possible.  Choosing which one depends then solely on what is less likely to change between runs.  I think that an alias is slightly more stable than the others, but do you guys agree?

**Comment by litchfld** [comment]
I think the best way is for a generator to provide a GetConfigString() method. The base class can implement this to return "default", and derived classes override this (even "default" is still allowed if it is appropriate)  

There absolutely has to be a special set of characters in order for the code to parse the constructed string.  The two options i'm aware of are 
- Having a special escape sequence, or 
- Banning the delimiter sequence 

Since a dangling escape sequence is essentially impossible, the former amounts to a banning particular digrams that begin with the escape character.

**Comment by litchfld** [comment]
Ah crossed in the ether.  From the sound of it this is just a question of viewpoint.  The config string to me is a machine readable code for the generator that just happens to be stored in a string. It's perfectly fine to have a human readable thing that co-exists, as long as there is a well defined translation from one to the other.  But the only thing that is absolutely necessary is the machine readable code.

**Comment by AndrewEdmonds11** [comment]
I'm going to close this discussion. Feel free to reopen if further questions come up
