### ISSUE TITLE
Normalisation?

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#131]
I'm just finishing off an offline version of the IslandLength DQ class and I realise there are two kinds of normalistion that we can do.  What we have so far is to simply scale histograms down by the number of muSc pulses in one run.  Another possible definition is to weight entries by the number of muSc pulses in the same event, then scale the whole histogram by the number of entries processed.  If odd things are happening this can produce a different histogram shape, but as long as there is nothing strange going on (and the number of muSc pulses per event is large) the two histograms are very similar. 

I initially did the latter because the two histograms were being filled concurrently, so that seemed the logical purpose. As it does in principle provide more information, I am inclined to leave it in, but this is a change of definition. My intention is therefore to  save three histograms for each channel:

``` C++
"<base name>"
"<base name>_EvtNorm"
"<base name>_RunNorm"
```

Is that okay with everyone?  I'll merge this back into develop and push tomorrow, if I don't get any complaints.  Even if it is a problem, a single file fix can be applied to develop.

**Comment by litchfld** [comment]
> What we have so far is to simply scale histograms down by the number of muSc pulses in one run. Another possible definition is to weight entries by the number of muSc pulses in the same event, then scale the whole histogram by the number of entries processed. 

See commit 361fdb29f4036732087b7c269c739ce5e0dec930 for details if that didn't make sense.

**Comment by litchfld** [comment]
Now in develop.

**Comment by jrquirk** [comment]
I think I might need some clarification. Correct me where I'm wrong:
1. You take the histogram from each event and normalize to the muSc hits in that event.
2. You add the histograms from all the events together.
3. You divide by the number of events.

I take no issue since we're keeping the total normalization around, but I'm just confused either with why you're doing this (declaring hits that occurred when the rates were low more important) or I'm confused with what you mean by event normalization.

**Comment by litchfld** [comment]
Yup, that's the end result, although the actual code is a bit different..  

I'm not sure that it has any obvious meaning for this variable, although it might for others.  It just seemed like a nice self consistency check, since it shouldn't matter. A run is somewhat arbitrary period to sum over, events didn't seem much less arbitrary, and it gives you some (admittedly imperfect) handle on whether there is variation on time scales <6min.
