### ISSUE TITLE
Finishing features? [rebase or merge] 

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#132]
So I was reading up on git flow, and I saw a couple of places where it is mentioned that git-flow is a merge-oriented tool.  This may (i'm still reading) explain the fact that rebasing before finishing always seems to result in two rebases, and the odd structures seen on out network graph. [Looking further I see this is a known point of debate](http://blogs.atlassian.com/2013/10/git-team-workflows-merge-or-rebase/).  I haven't digested that article yet, but I'm wondering:
- What are we all (individually) doing now?
- Should we (collectively) decide on a preference one way or the other?

**Comment by jrquirk** [comment]
I use the `gitflow feature finish` that we started with (as in, I'm not using any other gitflow scripts other than those first suggested by Volodya). And when I need to do something manually I use the `git merge` command. I've never had too much trouble backtracking, but I'm not convinced any way is better than the other so will passively adopt anything new.

**Comment by litchfld** [comment]
I think i'm going to go back to that, unless i'm really expecting trouble on the merge. In that case I think it might be better to rebase the feature branch as soon as possible, rather than waiting 'till you've finished.  So practically, branches would appear to start after the last set of conflicting changes and continue in parallel with all non-conflicting changes until they are merged back in.
