### ISSUE TITLE
data_quality directory (on file system)

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#133]
_This not anything to do with the discussion of root TDirectories_

I've just finished a redo-LLDQ module and i've put it in a subdirectory of `src/` (`src/data_quality`)  Is that okay?  It seems sensible to partition this from more analysis oriented plotters, since directories are (nearly) free and this seems like a fairly clear partition that will help avoid any overly-fat directories and provide a bit of auto-documentation.

**Comment by benkrikler** [comment]
This sounds good to me.

**Comment by litchfld** [comment]
Done
