### ISSUE TITLE
Write to the Calib DB in SetupNavigator

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#137]
As explained in issue #129, it would be good to have TSetupData (or whatever the new class is called) could read the noise values from the SQLite database created by PlotPedestalAndNoise.

Currently, there is a function in TemplateFitter (443f1e69071be45597489411827de330cfe8cab5), that does this.

**Comment by benkrikler** [comment]
I put the shell of the TSetupData replacement into the frameworks directory already.  It's a singleton called [`SetupNavigator`](http://alcap-org.github.io/doxygen/AlcapDAQ/develop/classSetupNavigator.html) to parallel Phill's EventNavigator.  At the moment its only function is to provide people with the current run number, but if you need to add something then feel free.

**Comment by AndrewEdmonds11** [comment]
Cheers. I will move the code there then.

**Comment by AndrewEdmonds11** [comment]
Done in the above commit

**Comment by AndrewEdmonds11** [comment]
Actually, just realised that we may also want the adding of these values to be done in SetupNavigator rather than PlotPedestalAndNoise so I'm going to reopen this

**Comment by AndrewEdmonds11** [comment]
Just to clarify what's going on here. Currently, we run PlotPedestalAndNoise to find out what the values of the pedestal and noise are and then add entries to the SQLite table there.

The adding of entries should be moved to SetupNavigator so that we have one object interacting with the SQLite database.

**Comment by AndrewEdmonds11** [comment]
So from Phill's comment in issue #186. It's best that we don't write directly to the Calib DB but write to a text file that will be uploaded, by hand, to the Calib DB.

John, how are things written at the moment? At some point (after you've finished), I will move the code that writes to the DB in PlotPedestalAndNoise into SetupNavigator in the same way as you

**Comment by jrquirk** [comment]
I currently write to the DB via the SetupNavigator as you say. The method can be changed to write to a text file or a temp DB or whatever of course, and the code that calls the write method won't care.

Additionally I have introduced a command line argument, -c, which is supposed to explicitly declare the intentions to write calib to a file. The problem being when running for the first time on a run, the SetupNavigator needs to know not to freak out about not finding the right tables.

I won't be merging my changes until the end of my day today, so you can merge yours if you want and I'll handle the conflicts. I modified the PlotTDiff to take an export_sql argument just like your plotter, and it does the calculation end of job.

**Comment by AndrewEdmonds11** [comment]
Cool. I don't actually have any code to merge in so will wait until you are done (or you can do it if that's easier)
