### ISSUE TITLE
Wiki: Git Tutorial

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#14]
We should have a tutorial for using git (i.e. starting and finishing feature branches, making sure the branch is deleted on GitHub when finished, rebasing etc.)

**Comment by benkrikler** [comment]
That's a good idea.  I'd also include git flow stuff I think.  Even if we
just pool the various links that would be helpful.

**Comment by AndrewEdmonds11** [comment]
I've written a first draft [here](https://github.com/alcap-org/AlcapDAQ/wiki/GitAndGitFlow). Could others read through and change anything I've got wrong/bad practices I've suggested?

**Comment by AndrewEdmonds11** [comment]
I'm closing this issue. Feel free to edit the wiki over there though
