### ISSUE TITLE
Anyone having problems SSHing into balrog?

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#140]
I'm getting this error:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The RSA host key for balrog.psi.ch has changed,
and the key for the according IP address 192.33.120.83
is unknown. This could either mean that
DNS SPOOFING is happening or the IP address for the host
and its host key have changed at the same time.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that the RSA host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
76:d9:c1:8f:ba:67:b2:ce:c1:0a:0e:da:74:a5:da:10.
Please contact your system administrator.
Add correct host key in /home/edmonds/.ssh/known_hosts to get rid of this message.
Offending key in /home/edmonds/.ssh/known_hosts:22
RSA host key for balrog.psi.ch has changed and you have requested strict checking.
Host key verification failed.
```

Anyone else getting the same thing?

**Comment by benkrikler** [comment]
I had this yesterday.  You just need to delete balrog from your ssh known hosts file.
The file is in `~/.ssh/known_hosts` and I just deleted all lines that mention balrog or merlin.

Then log back in as normal and you will get the normal questions as if you're ssh-ing into somewhere for the first time.

**Comment by thnam** [comment]
I had that too, but it was easier to fix.

**Comment by litchfld** [comment]
Well that's reassuring. Anyone know why their server ID has changed? It's normally nice to have a little plausibility check when that happens, but I don't see any indication on the PSI website.

**Comment by litchfld** [comment]
> The file is in ~/.ssh/known_hosts and I just deleted all lines that mention balrog or merlin.

If you have a hashed known_hosts file you won't be able to read it, but the error message tells you which line conflicts, e.g. in Andy's case it was line 22:

```
Offending key in /home/edmonds/.ssh/known_hosts:22
```

**Comment by benkrikler** [comment]
> If you have a hashed known_hosts file

Actually, it would be good to set this up.  How would I go about it?

**Comment by jrquirk** [comment]
I starting having the same problem a few days ago, and only with Balrog. I haven't logged into Balrog since and just always keep a Merlin connection open. You can also maybe use `ssh-keygen -R balrog.psi.ch`

**Comment by litchfld** [comment]
> >   If you have a hashed known_hosts file
> 
> Actually, it would be good to set this up. How would I go about it?

Uh... had to check the option name...  (it's not an option I set myself, but a default on the VM I sometimes use).  You need to add it to your ssh_config file:

```
Host *
    HashKnownHosts yes
```

**Comment by benkrikler** [comment]
> You need to add it to your ssh_config file:
> 
> ```
> Host *
>     HashKnownHosts yes
> ```

Nice!  I hadn't realised it was built in to ssh..  Also, for converting an old un-hashed known_hosts file, `ssh-keygen -H` does the trick.

Anyway, I'm going to close this because it seems to have been solved.  Does someone need to email PSI though or has someone done this already?

**Comment by jrquirk** [comment]
I don't think we need to email PSI. Perhaps only one of us getting this message might indicate a man in the middle, but all of us would mean probably there was a Swiss man in the middle, which seems unlikely.

**Comment by AndrewEdmonds11** [comment]
Deleting line 22 of my known_hosts file worked for me.
