### ISSUE TITLE
Gaussian fit generator

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#141]
I've just added a gaussian fit generator.  It fits a gaussian plus a linear pedestal:

```
double functions::gauss_lin(double *x, double *par) {
    // parameters:
    // 0: constant (pedestal)
    // 1: gradient
    // 2: Gauss amplitude
    // 3: Gauss mean
    // 4: Gauss width
    Double_t arg=(x[0]-par[3])/par[4];
    Double_t gauss1=par[2]*TMath::Exp(-0.5*arg*arg)/(2.5066283*par[4]);
    // function=gauss+constant background
    return gauss1+par[0] + par[1]*x[0];
}
```

I'm also storing the parameter errors, chi2 and fit convergence status on a TAP specialisation called: TGaussFitAnalysedPulse (original, huh?).  

The fit parameters are initialised to values that can be passed through the config file but for the moment the following code set the default values:

```
        fMean=opts->GetDouble("time",200);
        fWidth=opts->GetDouble("width",60);
        fAmplitude=opts->GetDouble("amplitude",200);
        fPedestal=opts->GetDouble("pedestal",0);
        fGradient=opts->GetDouble("gradient",0);
```

I'm pretty sure these need properly optimising, and could in principle be hooked into the sqlite database in the future.

I've also got it plotting via ExportPulse and an overload of `TAnalysedPulse::Draw` (which is virtual so that we can draw specialised pulses).  It only draws pulses for TPIs that don't converge at the moment but so far the ones I've looked seem reasonable that it should converge, especially with my dodgy initial values.
![pulse_nb81_sir2_f_9_4](https://cloud.githubusercontent.com/assets/4083697/3480630/a823ec5a-0363-11e4-9ea9-15e5a7d5a2f4.png)

Unfortunately I'm not going to have much more time to play with this before Wednesday, but it's already on develop if anyone wanted to look at refining it.  I think the linear pedestal could be the most interesting part in checking for pedestal variation over the timescale of a pulse.  We can cut out the pulses that don't converge by checking the fit status and plot that for each channel this is used on.  So if anyone wants to take over from here and look at refining and tuning this generator a bit then please be my guest.

**Comment by benkrikler** [comment]
I had another chance to look at this this morning.  Seems i wasn't actually writing out the recovered fitted time.

Looking through some of the pulses some thinks fit well, others not so much, which is by no means a surprise (for some reason I'm having a tough time getting the TAP fit to draw over the TPI due to the x-axis aligning badly, the plots below are not in global time but number of samples).

![c1](https://cloud.githubusercontent.com/assets/4083697/3526104/57835bea-0779-11e4-912a-c6b7b0ac0e7e.png)
which is clearly only fitting reasonably well because of the high gradient on the linear pedestal function.

![c2](https://cloud.githubusercontent.com/assets/4083697/3526106/5abb9584-0779-11e4-93f3-8ccef082b1aa.png)
which seems like a reasonable fit.

Perhaps this generator would be more useful for production if we just switch off the gaussian part of the fit and use just a linear function instead.  It would be nice to then mask out the pulse itself, but Im not sure the best way to decide what region to look at then...

**Comment by AndrewEdmonds11** [comment]
I'm going to close this. Feel free to reopen if you so wish.
