### ISSUE TITLE
MakeAnalysedPulses adds an element to TGlobalData::fPulseIslandToChannelMap

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#143]
While trying to print out a summary in the TemplateCreator module in the AfterLastEntry() function I was doing this:

``` c++
StringPulseIslandMap::const_iterator it;

// Loop over each detector
for(it = gData->fPulseIslandToChannelMap.begin(); it != gData->fPulseIslandToChannelMap.end(); ++it){
  std::string bankname = it->first;
  std::string detname = setup->GetDetectorName(bankname);

  int& n_fit_attempts = fNFitAttempts[detname]; // number of pulses we try to fit to
  int& n_successful_fits = fNSuccessfulFits[detname];
  std::cout << "TemplateCreator: " << detname << ": " << n_fit_attempts << " fits attempted with " << n_successful_fits << " successful (" << ((double)n_successful_fits/(double)n_fit_attempts)*1\
00 << "%)" << std::endl;
}
```

and it was crashing.

I managed to track it down to the fact that `bankname` was "" and `GetDetectorName()` couldn't handle it for some reason.

This element of the map doesn't cause problems anywhere else because it doesn't exist. The size of the map is 30 in BeforeFirstEntry() and ProcessEntry() and 31 in AfterFirstEntry().

Commenting out the other modules in my MODULES file (MakeAnalysedPulses, MakeDetectorPulses and ExportPulse) it seems MakeAnalysedPulses is the culprit.

I can't see in MakeAnalysedPulses where the problem might be coming in but, for the time being, I can just run without it and take out this piece of code above when we come to the production run on Wednesday. (I know Ben is busy between then and now and won't have time to look at it so there's no rush)

**Comment by jrquirk** [comment]
I couldn't reproduce the problem, but it's possible that [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/MakeAnalysedPulses.cpp#L103-L104) a bad detname is found, but then [GetBankName](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/src/common/TSetupData.cpp#L5-L12) returns "", which then [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/MakeAnalysedPulses.cpp#L107) creates an entry in gData with key "". A way to test this would be to change

```
thePulseIslands=&gData->fPulseIslandToChannelMap[bankname];
```

to

```
thePulseIslands=&gData->fPulseIslandToChannelMap.at(bankname);
```

And it will throw an exception if that's a problem. Or you can change the GetBankName to throw an error.

**Comment by litchfld** [comment]
Johns answer looks very plausible - map<>::operator[] is dangerous for just that reason. Unfortunately, map<>::at() isn't strictly part of C++03, although it is a common extension.  One has to do 

``` C++
StringPulseIslandMap::iterator tmp_iter = gData->fPulseIslandToChannelMap.find(bankname);
if (tmp_iter == gData->fPulseIslandToChannelMap.end() ) continue;
thePulseIslands = &(*tmp_iter)
```

Or 

``` C++
if (gData->fPulseIslandToChannelMap.count(bankname) = 0) continue;
thePulseIslands=&gData->fPulseIslandToChannelMap[bankname];
```

Either should work on every C++03 compiler (modulo mistakes in my code).

**Comment by litchfld** [comment]
While i'm looking at this it the code would be much easier to read (as well as more C++ idiomatic) if we put off declaring `thePulseIslands` until we actually need it, and then declare it as a reference, e.g. version 2 becomes:

``` C++
if (gData->fPulseIslandToChannelMap.count(bankname) = 0) continue;
PulseIslandList& thePulseIslands = gData->fPulseIslandToChannelMap[bankname];
```

**Comment by benkrikler** [comment]
The latest version of MakeAnalysedPulses (currently on featureBK_upgrade_plotters) has now replaced the dodgy area with the following code:

```
        // find the pulse list in gAnalysedPulseMap
        SourceAnalPulseMap::iterator it=gAnalysedPulseMap.find((*generator)->GetSource());
        if(it==gAnalysedPulseMap.end()){
            // source doesn't seem to exist in gAnalysedPulseMap
            cout<<"Error: New TAP source seems to have been created during processing of pulses."<<endl;
            return 1;
        }
        // add the pulses into the map
        it->second=theAnalysedPulses;
```

So there's no risk of adding in new lists once we've started the run.

Also, to obtain the bank name for a given channel, the `SetupNavigator` now provides a more robust case independent (and '-' == '_' ) method which takes an `IDs::channel` and returns the bank name as a string.  That should prevent you getting back an empty string unless the channel Id is genuinely invalid.

**Comment by AndrewEdmonds11** [comment]
This is done.
