### ISSUE TITLE
Number of objects to write?

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#147]
@benkrikler Is there any way to calculate ahead of time how many things we are going to want to store?  I think it's possible to add new pointers-to-memory-buffers on the fly, but it would be easier not to have to read the TTree code...

**Comment by benkrikler** [comment]
By 'things', what do you mean?  
- The number of modules to be used is known directly from the MODULES file.
- The number of generators at a given stage is known by inspecting both the MODULES file and the TSetupData being processed (ie. just after connecting to input)
- The number of TPIs would be known only by checking the input file directly.
- The number of TAPs and subsequent stages would only be known if we can guarantee that a generator will provide 1 TAP per TPI (or at least a fixed factor).  There is a virtual method called `MayDivideTPIs` that should be overloaded by each generator to set whether or not the generator _could_ split up TPIs (ie. produce more TAPs than TPIs), and we could add another to say if they could ignore TPIs (ie. produce fewer TAPs than TPIs).   But even then this would only really answer your question above and not actually give the number of TAPs you will have (unless both methods return false).

You can't be the first person to face these sorts of issues though.  Doesn't TObjArray or TClonesArray take care of this sort of thing?  Certainly, all normal, non-derived TAPs are fixed size so I think you could get away with TClonesArray.  Even if you took the derived TAPs, provided you know the derived type before you need to fill the array you would be confident of fixed size if the derived TAP doesn't contain any pointers or container classes, which is a reasonable restriction to make I think.

**Comment by litchfld** [comment]
By things I mean Banks, TPulseIslandLists and the like.  Normally we might expect 1 generator to produce one output per input at most, but i guess we cant rely on that?  The issue being that it's very useful to have all the pointers to stl containers sitting at known addresses or at least be absolutely sure of the circumstances when they might move.

TObjectArray might have a way to do it (TClonesArray probably not since it achieves it's optimisations by knowing how much memory to allocate at the start), but to do that would require making the objects on disk something other than stl containers, since it requires elements to inherit from TObject. That may be the easiest way though, if i cant predict the number of branches we need.

**Comment by benkrikler** [comment]
> By things I mean Banks, TPulseIslandLists and the like

The number of banks and TPILists is given by the intersection of banks contained in TSetupData and the channels requested through the modules file.  We would first know that number then once we've loaded both files, but we could do both of these things before creating our TAP lists objects no?

> Normally we might expect 1 generator to produce one output per input at most, but i guess we cant rely on that?

That's exactly what I was suggesting in my last post. The method `MayDivideTPIs` which already exists can tell us if `N_tap > N_tpi` and we could add `MayIgnoreTPIs` to cover generators tht could give `N_tap < N_tpi`.  Of course they only work once a generator is made so we would have to wait a while longer still to be able to work any numbers out.

> The issue being that it's very useful to have all the pointers to stl containers sitting at known addresses or at least be absolutely sure of the circumstances when they might move.

You're aware of the STL `list` container, right? It doesn't use contiguous memory like `vector`so maybe that could help you out?

> TClonesArray probably not since it achieves it's optimisations by knowing how much memory to allocate at the start  

I don't think it needs to know the number of entries in the array, only the size of each one which for TAPs and probably Specialised TAPs would be fixed at compile-time.

>  requires elements to inherit from TObject

I think TAPs, TDPs, TMEs and TPIs already inherit from TObject.

**Comment by litchfld** [comment]
Hi Ben

Sorry, we seem to be at crossed purposes for most of this discussion, I was wondering about how many TXxxPulseLists, i.e. std::container<TXxxPulse*> to create. It seems to put an STL container directly in a tree the location _of the pointer_ has to be (reasonably) stable, which means I cant simply go along say with `vector<vector<TXxxPulse*>*>::push_back()` as resizing makes all those addresses change. There are a number of ways round this, the most direct in this example is to use a `vector<vector<TXxxPulse*>**>` but this level of indirection makes my brain hurt. So I was wondering if we could avoid ever having that kind of reallocation.

**Comment by benkrikler** [comment]
I'm guessing you want a vector of vectors of TxxxPulses to replace our `SourceXXXPulseMap`s?  A map could reorganise the contents every time we add a new key right?  But just to be clear:
- the number and types of pulse lists is known before we would write anything
- the number of entries in each list is not known
- the size of each entry is known for each list before we write anything.

Given those points, I'm not sure we would need to worry about the actual lists moving around.

What I really don't understand is why we need to keep the pulses in an STL container?  We don't care particularly what the container is as long as we can iterate over the contents in an easy, random-access way.   If `std::vector` is giving you this much grief and forcing you to have this many nested pointers then why not switch to something else?  

Couldn't we replace `SourceXXXPulseMap` with `std::map<IDs::source , TClonesArray* >`?  Why wouldn't that work or else why doesn't it do what you want?  It's a list of objects that can be looped over and is designed to be stored in a root file.

**Comment by litchfld** [comment]
> - the number and types of pulse lists is known before we would write anything
>   Given those points, I'm not sure we would need to worry about the actual lists moving around.

I'm not sure that is the case. At the moment there is no particular hook for a generator to say "I am going to produce these banks, please make sure the that branch pointers are assigned". [In some sense we don't want to do that because it means two separate bits of code have to agree].  So the first the file I/O knows about a branch is when a generator comes up and says "write this to disk please".  

(It's always doable---I think TBranch::SetAddress() would reset the pointer as the ultimate resort, but the documentation ~~isn't very clear~~ dosen't say anything at all---but the clearer the boundary conditions, the more stable the resulting code.)

I think we are largely committed to the STL containers or something derived from them now: the generators take them in their ProcessPulses methods, so changing the format requires changing the behaviour of all active parts of the code, and iterating through ROOT containers looks very different (Fun fact: ROOT containers pre-date the STL, at least as a standard part of C++)

My approach right now is to simply wrap the STL objects with a TObject for the purpose of saving them;  we can discard the wrappers when we present them to users.  I think this causes the minimum of fuss, summing over internal and external effects.  I'm going to close this for now and see how I get on.

**Comment by benkrikler** [comment]
> At the moment there is no particular hook for a generator to say "I am going to produce these banks, please make sure the that branch pointers are assigned". 

Not true any more.  We already had a `GetSource` method on each generator.  What we now also have (as of last night) is `MakeAnalysedPulses` initialising `gAnalysedPulseMap` so that it contains a list for every source that will need writing.  It now complains if you try to write TAPs to a list with a source ID that was previously not present.  I think this completely covers your description there the only difference being that it's implemented in the client (MakeAnalysedPulses) and not the list container itself, which might be preferable.

> I think we are largely committed to the STL containers or something derived from them now: the generators take them in their ProcessPulses methods, so changing the format requires changing the behaviour of all active parts of the code

Which is something else I had to do last night.  The biggest overhead in that transition is that everyone would have to relearn this part of the framework.  The actual time to change existing code is at present the best part of a few hours, although the longer we leave this the larger that becomes.

> My approach right now is to simply wrap the STL objects with a TObject for the purpose of saving them; we can discard the wrappers when we present them to users

That's exactly what TAnalysedPulseMapWrapper does and it makes it very awkward to work with the output Tree through standalone root code (or to put it another way, my ROOT is not sufficient to work with it).  

When I suggested a data manager, my primary aim was to get rid of global pointers / variables and provide access to the pulse lists.  If we had that then changing the underlying structure is a decoupled issue.  Could we focus on removing the `gXXXPulseMap`s at this point and getting the BankIters functioning with the existing containers in a way we could start developing against them?

**Comment by litchfld** [comment]
> That's exactly what TAnalysedPulseMapWrapper does and it makes it very awkward to work with the output Tree through standalone root code (or to put it another way, my ROOT is not sufficient to work with it).

I think that's inevitable, at least up to the muon event level,. Branches that are not fixed length (i.e. any dynamic container) are a bleeding pain to work with.

> When I suggested a data manager, my primary aim was to get rid of global pointers / variables and provide access to the pulse lists. If we had that then changing the underlying structure is a decoupled issue. Could we focus on removing the gXXXPulseMaps at this point and getting the BankIters functioning with the existing containers in a way we could start developing against them? 

I guess we can do that... It will be limited to TAPs and TPIs, and not put a copy of the TPIs tree across to the output file in the first instance,  Shouldn't be too difficult, although it may be slow if I can't avoid all the copies.

**Comment by benkrikler** [comment]
>  it may be slow if I can't avoid all the copies.

As long as this sort of issue is hidden from us and doesn't affect the interface so we don't need to change our code later then I'm not so worried about it for now.
