### ISSUE TITLE
SQLite: Add an SQLite file for recording whether channels should be analysed or not

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#149]
As mentioned in issue #145, we sometimes have really bad channels that we may not want to analyse.

We should, in the future, add an SQLite database that will check whether a channel is OK to analyse.

**Comment by litchfld** [comment]
A new file or a new table in the same file?

**Comment by AndrewEdmonds11** [comment]
Well at the moment the file is called pedestals-and-noises.sqlite so if we want to add a new table we should probably rename the file.

**Comment by benkrikler** [comment]
Where in the repository is the table stored?  I think if we have more than
one file they deserve their own directory, run_db or something.

Also, i couldn't see the sqlite code in SetupNavigator.  Is it pushed to
develop?

**Comment by AndrewEdmonds11** [comment]
The files not in the repository yet since I'm still using it to mess about with.

Sorry, it's on the branch I'm working on [feature/finalise_template_creator](https://github.com/alcap-org/AlcapDAQ/blob/feature/finalise_template_creator/analyzer/rootana/src/framework/SetupNavigator.cpp).

It'll be merged when I eventually get this template creator working...

**Comment by AndrewEdmonds11** [comment]
I think this can be merged into issue #186.
