### ISSUE TITLE
Wiki: Other stuff

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#15]
Other stuff that should go on the wiki:
- picture book generator instructions
- ODB checker instructions
- alcapana instructions
- rootana instructions

Can anyone think of anything else?

**Comment by benkrikler** [comment]
In principle it might be good if every module had separate documentation.  Is that realistic?

**Comment by AndrewEdmonds11** [comment]
Yes, I think that's a very good idea.

Also, should we also store information about problems with run sets we discover. Obviously the result will be stored in the run DB but for investigations should we use the wiki or the issues system?

**Comment by benkrikler** [comment]
Or how about elog for those? I think those sorts of issues which are closer to the physics (unless its really a software bug) should be written where people not actually using the software would see it.

**Comment by AndrewEdmonds11** [comment]
That's a very good point, actually.

My only thought is that we get e-mail notifications when someone responds to an issue on GitHub (as I'm sure many people are realising) and other people may not check the elog that often.

In either case, I think a summary at the other location would be a good idea.

What does everyone think?

**Comment by AndrewEdmonds11** [comment]
Something else to add is the explanation of TPI --> TAP --> TDP --> TME and associated generators (goes in rootana section I guess)

**Comment by AndrewEdmonds11** [comment]
I can't seem to get subfolders to work with the wiki. If anyone else knows then please enlighten us. If it's not possible we should probably try and standardise how we organise pages...

**Comment by benkrikler** [comment]
I don't think it's possible on github wikis.  For the other organisation
I've worked with, we just use a naming convention to imply a directory.

**Comment by AndrewEdmonds11** [comment]
Ok, what convention do you use then?

**Comment by benkrikler** [comment]
Just a prefix for the 'directory'.  So if you want a directory called
'rootana' we just make sure every page starts with 'rootana-' .  Github can
be funny converting non-alphanumeric characters to dashes or whitespace to
underscores so we should pay attention to it when making new pages.

**Comment by AndrewEdmonds11** [comment]
Ok. So far, I've used an underscore but with the module pages I've just added having an underscore in the name it looks odd. So should we move to hyphen?

**Comment by benkrikler** [comment]
The title  doesnt have to be the URL of the page though.  You can change it
once the page is committed I think. It's been a while since I added
anything though so my memory might be letting me down...

**Comment by AndrewEdmonds11** [comment]
Just adding an image here to see if I can put it on the wiki (apparently you can't do it directly...)
![rebasingimage](https://cloud.githubusercontent.com/assets/1848575/3103115/f285c870-e650-11e3-9ff0-1073146e5236.png)

**Comment by jrquirk** [comment]
Documentation is a running issue. I'm going to close this, but if anyone feels this issue should be open just reopen it.
