### ISSUE TITLE
MaxTimeDiff algorithm enters infinite loop

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#150]
At the moment the MaxTimeDiff algorithm never finishes the first pulse.
There's clearly some problem in the loop termination condition but it's not immediately obvious to me, and I need to focus on other things now so I'm putting this here for future me or present someone else to look back at.

The output I'm currently seeing is:

```
@ src/TDP_generators/MaxTimeDiffDPGenerator.cpp:33 count++= |0|
Fast? Ge-F#MaxBin#default
Slow? Ge-S#MaxBin#default
Created a TDetectorPulse with:
Fast Pulse: -0.00593794
Slow Pulse: -0.0113719

@ src/TDP_generators/MaxTimeDiffDPGenerator.cpp:75 (*pulseIters[b].first)->GetParentID()= |1|
@ src/TDP_generators/MaxTimeDiffDPGenerator.cpp:75 (*pulseIters[b].first)->GetParentID()= |1|
@ src/TDP_generators/MaxTimeDiffDPGenerator.cpp:33 count++= |1|
Created a TDetectorPulse with:
Fast Pulse: -0.009999
Slow Pulse: -0.009999

@ src/TDP_generators/MaxTimeDiffDPGenerator.cpp:75 (*pulseIters[b].first)->GetParentID()= |1|
@ src/TDP_generators/MaxTimeDiffDPGenerator.cpp:75 (*pulseIters[b].first)->GetParentID()= |1|
@ src/TDP_generators/MaxTimeDiffDPGenerator.cpp:33 count++= |2|
Created a TDetectorPulse with:
Fast Pulse: -0.009999
Slow Pulse: -0.009999
```

where `count` is the loop counter and the FastPulse, SlowPulse values are the pulse' time.

That continues until we fill the memory and throw `bad_alloc`.

This is currently on the branch `feature/BK_upgrade_plotters` but should be merged into develop shortly.

**Comment by litchfld** [comment]
I think min_time needs to set to something big inside the while loop, otherwise the min_time found from the first time round will be the minimum for ever more.

**Comment by litchfld** [comment]
Wow 12.9 GiB virtual, 0 events processed! I think I can reproduce this now. :)

**Comment by litchfld** [comment]
OK I think  the min_time change I suggested fixes it, but i'm seeing another infinite (or at least long running) loop now, which I am assuming comes from TMuonEvent as it endlessly prints "No detector called [...]" messages. I'm going to leave it here for tonight, but this bug is probably fixed.

**Comment by litchfld** [comment]
That seems to have fixed it.
