### ISSUE TITLE
I have no idea what gTotalEntries is supposed to be.

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#156]
I'm trying to get rid of the global and external objects but I'm stuck on this one. `gTotalEntries` to me could be one of two things:
- total number of Entries in the tree
- total number of entries we plan to process (i.e `stop - start`)

In fact it seems to be set to `stop`, which makes little sense...

What do people expect to do with this number?  The only code I could find that actually uses it is ExportPulse, and as far as I can tell it is building a list of numbers restricted between 0 and gTotalEntries.  It seems like the each event is just compared to those number, so in practice it doesn't do very much, unless you had a massive configuration file with thousands (millions?) of out-of-range event numbers.  

So, I figure I can just replace it with  the total number of events in the tree, which is an the easier number to access.  Is this okay?

**Comment by benkrikler** [comment]
Replace away! 

I put it in as a sanity check for export pulses, for pulses bring requested through the modules file. I would actually have preferred it give the number of events on the file (hence the name), not the last event to be processed, but I think I chose the wrong variable in main.cpp and wasn't so disturbed by the result as to change it...

Sent from my mobilelitchfld notifications@github.com wrote:I'm trying to get rid of the global and external objects but I'm stuck on this one. gTotalEntries to me could be one of two things:

total number of Entries in the tree
total number of entries we plan to process (i.e stop - start)
In fact it seems to be set to stop, which makes little sense...

What do people expect to do with this number? The only code I could find that actually uses it is ExportPulse, and as far as I can tell it is building a list of numbers restricted between 0 and gTotalEntries. It seems like the each event is just compared to those number, so in practice it doesn't do very much, unless you had a massive configuration file with thousands (millions?) of out-of-range event numbers.

So, I figure I can just replace it with the total number of events in the tree, which is an the easier number to access. Is this okay?

**Comment by litchfld** [comment]
Okidoke.
