### ISSUE TITLE
MakeMuonEvents seems to go into infinite loop

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#159]
After fixing the infinite loop issue #150, I find rootana still enters an (apparently) infinite loop.  It cycles repeatedly through messages of the form

```
No detector called '[...]' exists.
```

I haven't looked any further, for the time being I'm just disabling MakeMuonEvents in the module file.

**Comment by AndrewEdmonds11** [comment]
Is this still a bug, Ben or have you solved it?

**Comment by benkrikler** [comment]
I've been able to run through an entire run and didn't come across this problem, so I think we can close this.  I'm not entirely sure what the issue was though...
