### ISSUE TITLE
PlotAmplitude bug for certain channels?

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#162]
When running PlotAmplitude after MakeAnalysedPulses and using the MaxBinAPGenerator some plots don't look right (x-axis goes from 0 to 1 and there are entries in the plot that don't appear anywhere).

I'm running on run 2808 (Al100) and looking in particular at channel SiL1-1-F and the corresponding source is SiL1_1-F#MaxBinAPGenerator#default.

Here's what the plot looks like:
![sil1_1-f maxbinapgenerator default_run2808](https://cloud.githubusercontent.com/assets/1848575/3762469/662b2fcc-1897-11e4-9677-4d2e48f4f830.png)

and when I try to extend the axis range by hand to be between 0 and 4096, I get this:
![sil1_1-f maxbinapgenerator default_run2808_larger-x-axis-range](https://cloud.githubusercontent.com/assets/1848575/3762475/77ef4c34-1897-11e4-9722-a641a892ea8c.png)

Note that the number of entries here is the same as the number of events in run 2808.

When I check what is being filled into the histogram in PlotAmplitude, the same number gets inserted many times  (I'm guessing in each event) but it _does_ change.

I've found that the number changes when there is a new TPI in SiL1-1-F (there isn't necessarily one in every event) and so I think that the AnalysedPulseList isn't getting cleared properly between events.

I'll look into this a bit further but thought I'd better put my thoughts down somewhere.

**Comment by AndrewEdmonds11** [comment]
Tracked down why the axis range is wrong. Currently, the max_adc_value is being returned as 1 [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/plotters/PlotAmplitude.cpp#L56), which comes about because [i_det->first.Channel().str()](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/plotters/PlotAmplitude.cpp#L55) returns SiL1_1-F, when the detector name is actually SiL1-1-F.

So either we need to change all the strings in IdChannel.cpp or have TSetupData also be -/_ insensitive like IdChannel. 

I'll leave Ben to decide which is best but on my personal branch I'll change _ to - for the time being while I investigate further

**Comment by benkrikler** [comment]
Good sleuthing!  So this is actually 2 bugs you've found (we should set up a bug hunting competition board and tally these up).

The bug of not clearing the TAPs after each event is probably related to the memory leak.  I'll add that we at least clear the main map (`gAnalysedPulseMap`) after each ~~run~~ event, but this won't actually result in deleting the TAPs.

I'll add getting the number of bits for a channel to the SetupNavigator and make it so it uses a channel ID and not a string.  Hopefully this means we don't need to change TSetupData, but it might require some small changes (adding the SetupNavigator as a friend class, possibly).  Worst comes to the worst I'll change the strings in the Channel ID class as you suggest.

**Comment by AndrewEdmonds11** [comment]
Thanks, Ben. Also, if we need to change the strings then MuSc and MuScA would also need to become muSc and muScA.

I'll look into the TAP deletion since I was about to start on the TemplateAPGenerator and was planning on using the plotter modules to test it.

**Comment by benkrikler** [comment]
Thinking about it a bit more, is there any reason not to change the strings?  The only reason I can think of is aesthetic, which doesn't really seem strong enough.  I do want to move this functionality into the SetupNavigator, but we could also change the string representation which would make the implementation easier.

If you look at deleting TAPs or just clearing the map I think the correct place for now, as much as I hate the function, is in `ClearGlobalData`.

**Comment by AndrewEdmonds11** [comment]
> Thinking about it a bit more, is there any reason not to change the strings?

No, I don't think so. I'm more used to muSc than MuSc anyway but maybe others disagree...

Thanks for the heads up of where to put TAP deletion. Just a quick question, from reading about std::vector::clear(), it says this function will also delete the elements. Do we need a special destructor or anything because we inherit TAnalysedPulse from TObject?

**Comment by litchfld** [comment]
FYI I'm intending to rework the SetupNavigator eventually. Keeping it totally separate from the EventNavigator gets murky since the EventNavigator has control of the file in which the TSetupData object is found.  

Sorry to drop unhelpful comments and run away. Unfortunately I haven't looked too hard at what is going on here and don't have much time right now.

**Comment by litchfld** [comment]
I'm not sure but you may find that the SetupRecord interface (via `EventNavigator::Instance().GetSetupRecord()`). will avert this bug, since it is indexed by MIDAS bank name (string) or Channel ID (object).

**Comment by litchfld** [comment]
> Thinking about it a bit more, is there any reason not to change the strings?

I'm not sure what you are asking, but the strings stored in TSetupData of course can't be changed as they form part of the raw archival format. The strings in the channel IDs are easier to change, but IIRC there are soft constraints based on being sure the parser worked correctly. I think it was things like 'SiL1_1-S' vs 'SiL1_Sum'

**Comment by litchfld** [comment]
> Thanks for the heads up of where to put TAP deletion. Just a quick question, from reading about std::vector::clear(), it says this function will also delete the elements. Do we need a special destructor or anything because we inherit TAnalysedPulse from TObject?

No, but you do need to be careful because the elements are TAP*s not TAPs. Deleting the elements just means freeing the memory the pointers are stored in, not deleting them in the sense of destructing and deallocating the object they point to.

**Comment by AndrewEdmonds11** [comment]
So, `ClearGlobalData` was commented out in LoopSequence.cpp and, after uncommenting it, I got the following error:

```
Error: New TAP source "muSc#Template#default" seems to have been created during processing of pulses.
```

This is because we call `gAnalysedPulseMap.clear()` in `ClearGlobalData` which removes all the keys from the map. Then, because `MakeAnalysedPulses` loops through the generators, the work done in `BeforeFirstEntry` is overwritten.

For the time being, I'll comment out line 220 of main.cpp and leave it for someone better to find a better fix.

**Comment by AndrewEdmonds11** [comment]
Just as a summary, here's the diff log of the three files I changed:

IdChannel.cpp:

```
diff --git a/analyzer/rootana/src/framework/IdChannel.cpp b/analyzer/rootana/src/framework/IdChannel.cpp
index 7bd89de..e1eeb32 100644
--- a/analyzer/rootana/src/framework/IdChannel.cpp
+++ b/analyzer/rootana/src/framework/IdChannel.cpp
@@ -25,19 +25,19 @@ std::string IDs::channel::GetDetectorString(Detector_t det){
             case kScL         : output="ScL"      ; break ; 
             case kScR         : output="ScR"      ; break ; 
             case kScVe        : output="ScVe"     ; break ; 
-            case kSiL1_1      : output="SiL1_1"   ; break ; 
-            case kSiL1_2      : output="SiL1_2"   ; break ; 
-            case kSiL1_3      : output="SiL1_3"   ; break ; 
-            case kSiL1_4      : output="SiL1_4"   ; break ; 
+            case kSiL1_1      : output="SiL1-1"   ; break ; 
+            case kSiL1_2      : output="SiL1-2"   ; break ; 
+            case kSiL1_3      : output="SiL1-3"   ; break ; 
+            case kSiL1_4      : output="SiL1-4"   ; break ; 
             case kSiL2        : output="SiL2"     ; break ; 
-            case kSiR1_1      : output="SiR1_1"   ; break ; 
-            case kSiR1_2      : output="SiR1_2"   ; break ; 
-            case kSiR1_3      : output="SiR1_3"   ; break ; 
-            case kSiR1_4      : output="SiR1_4"   ; break ; 
-            case kSiR1_sum    : output="SiR1_sum" ; break ; 
+            case kSiR1_1      : output="SiR1-1"   ; break ; 
+            case kSiR1_2      : output="SiR1-2"   ; break ; 
+            case kSiR1_3      : output="SiR1-3"   ; break ; 
+            case kSiR1_4      : output="SiR1-4"   ; break ; 
+            case kSiR1_sum    : output="SiR1-sum" ; break ; 
             case kSiR2        : output="SiR2"     ; break ; 
-            case kMuSc        : output="MuSc"     ; break ; 
-            case kMuScA       : output="MuScA"    ; break ; 
+            case kMuSc        : output="muSc"     ; break ; 
+            case kMuScA       : output="muScA"    ; break ; 
        }
      return output;
 }
@@ -46,10 +46,10 @@ IDs::Detector_t IDs::channel::GetDetectorEnum(const std::string& det){
      const char* names[1+IDs::num_detector_enums]={ 
             "*"        ,                                                // 0
             "Ge"       , "LiquidSc" , "NDet"     , "NDet2"  , "ScGe"   ,// 1-5   
-            "ScL"      , "ScR"      , "ScVe"     , "SiL1_1" , "SiL1_2" ,// 6-10  
-            "SiL1_3"   , "SiL1_4"   , "SiL2"     , "SiR1_1" , "SiR1_2" ,// 11-15 
-            "SiR1_3"   , "SiR1_4"   , "SiR1_sum" , "SiR2"   , "MuSc"   ,// 16-20 
-            "MuScA" };                                                  // 21
+            "ScL"      , "ScR"      , "ScVe"     , "SiL1-1" , "SiL1-2" ,// 6-10  
+            "SiL1-3"   , "SiL1-4"   , "SiL2"     , "SiR1-1" , "SiR1-2" ,// 11-15 
+            "SiR1-3"   , "SiR1-4"   , "SiR1-sum" , "SiR2"   , "muSc"   ,// 16-20 
+            "muScA" };                                                  // 21
      for (int i=0;i<=IDs::num_detector_enums;i++){
         if(modules::parser::iequals(det,names[i])) return (Detector_t)i;
      }
```

LoopSequence.cpp:

```
diff --git a/analyzer/rootana/src/framework/LoopSequence.cpp b/analyzer/rootana/src/framework/LoopSequence.cpp
index 3af3d7d..c87fa04 100644
--- a/analyzer/rootana/src/framework/LoopSequence.cpp
+++ b/analyzer/rootana/src/framework/LoopSequence.cpp
@@ -96,7 +96,7 @@ void LoopSequence::Process() const
     TGlobalData* raw_data = enav.GetRawData();
     if (raw_data){
       raw_data->Clear("C");
-      //ClearGlobalData(raw_data);
+      ClearGlobalData(raw_data);
     }

     Checkpoint(jentry);
```

main.cpp:

```
diff --git a/analyzer/rootana/src/main.cpp b/analyzer/rootana/src/main.cpp
index ac012af..fb7a204 100644
--- a/analyzer/rootana/src/main.cpp
+++ b/analyzer/rootana/src/main.cpp
@@ -217,7 +217,7 @@ void ClearGlobalData(TGlobalData* data)
     }
     pulse_vector.clear();
   }
-  gAnalysedPulseMap.clear();
+  //  gAnalysedPulseMap.clear();

   for(StringDetPulseMap::iterator mapIter = gDetectorPulseMap.begin(); mapIter != gDetectorPulseMap.end(); mapIter++) {
     // The iterator is pointing to a pair<string, vector<TPulseIsland*> >
```

**EDIT** Just to clarify, these changes are not committed on my branch

**Comment by benkrikler** [comment]
We don't want to clear the map itself, just clear each of the TAP lists it contains, which is done in ClearGlobalData already.  You're right to comment out line 220 then.  Andy, your diff looks like it does everything needed to solve this issue.  Do you want to commit and push your changes then?

**Comment by AndrewEdmonds11** [comment]
Yep, I can do seeing as neither you or Phill have objected.
