### ISSUE TITLE
Changes to BaseModule mean modules not being processed

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#163]
I just hit a very subtle bug where my modules weren't being processed.  After a bit of digging around I think I've found the cause:

The signature for `BaseModule::ProcessEntry` has been changed from:

```
 virtual int ProcessEntry(TGlobal    Data *gData,  TSetupData* gSetup);
```

to 

```
 virtual int ProcessEntry(TGlobal    Data *gData, const TSetupData* gSetup);
```

Because this is not a purely abstract method (BaseModule implements itself) the existing modules that weren't updated as well as new modules made with the  `CreateModule.sh` script don't get processed as the function look-up doesn't find the derived class' method.

I'm going to make this method purely abstract in BaseModule and update all the existing modules and `CreateComponent` script.

**Comment by benkrikler** [comment]
It seems the same is true for the `BeforeFirstEntry` and `AfterLastEntry` methods.

**Comment by litchfld** [comment]
Sorry, I changed all those those. I guess I should have actively warned people. 
(I can't ever remember anything that detailed about code; it never even occurred to me anyone would ever write a derived class without having the base class open alongside.)

**Comment by benkrikler** [comment]
The above commits fix this.  

I've made all three `Process...` methods completely abstract in the base module to avoid this problem in the future (since we know at some point TGlobalData and TSetupData will go).  This means that all modules have to implement all three methods, though if you don't want to do anything with a particular one, just `return 0`.  

I've update the `CreateModule.sh` script and have put in all the necessary changes throughout all existing code.  Modules that haven't been pushed to develop may need updating now though, but it should be straight forward to do.

**Comment by jrquirk** [comment]
> it never even occurred to me anyone would ever write a derived class without having the base class open alongside

Unless they had already written it and were updating it.
