### ISSUE TITLE
Memory leak blues

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#164]
Working on my own branch for TDetectorPulses I'm seeing bad memory leaks that are preventing me from running past 140 events.  I'm using a pretty scaled down modules file, just MakeAnalysedPulses, MakeDetectorPulses and the module to plot TDP properties I've been writing.

Do other people see similarly bad performance (ie.  the problem has gotten worse on develop branch) or have I added a bad leak somewhere on this branch?

**Comment by benkrikler** [comment]
Hang aboot, I thought I'd rebased on Andy's updates but it seems I didn't.  Now I've been able to run over the entire file so it seems to have solved it all for me...

**Comment by benkrikler** [comment]
No, wait, it seems the problem is actually coming from the PlotTime module.  When I take it out of the modules file I can process the entire run.  With it in, seemingly independent of what else is being run, the production dies after event 140...

**Comment by benkrikler** [comment]
Well that was an easy enough fix.  The x-axis of the plots made by PlotTime had 1e6 bins.  I've changed it down to 1e3 and things seem happy again.  Presumably that's fine enough for most purposes, unless we need to start zooming in I suppose.

**Comment by litchfld** [comment]
1e6 bins \* ~ 32 detectors \* 32 bits ~= 120MB... that's big but not devastating.  Are the histograms being deleted properly?

FWIW, and possibly unrelated, i've noticed with simple event loops that the memory usage climbs up high at about 200 events then settles down to something much more modest after about 300. I think this is some artefact of how ROOT estimates buffer sizes but i'm not sure.

**Comment by benkrikler** [comment]
> 1e6 bins \* ~ 32 detectors \* 32 bits ~= 120MB... that's big but not devastating. Are the histograms being deleted properly?

I don't think they're being deleted at all to be honest (I thought by writing them to disk we were essentially deleting them from the heap), but that would not be the cause of the crash I saw as we wouldn't expect to delete them during the event loop, only afterwards no?

> FWIW, and possibly unrelated, i've noticed with simple event loops that the memory usage climbs up high at about 200 events then settles down to something much more modest after about 300. I think this is some artefact of how ROOT estimates buffer sizes but i'm not sure.

I remember you mentioned this before and I've since seen it mentioned on the ROOT forums.

How were you profiling things, btw?  It would be nice to profile the LoadPulses and SavePulses modules cause I'm nervous that I've added more leaks or else I'm using more memory.

**Comment by litchfld** [comment]
> How were you profiling things, btw? It would be nice to profile the LoadPulses and SavePulses modules cause I'm nervous that I've added more leaks or else I'm using more memory.

The dumb way (http://alcap-org.github.io/doxygen/AlcapDAQ/develop/debug__tools_8cpp_source.html#l00015) 

I sometimes watch top in another while it's running, just to check the reported values aren't hiding anything. They haven't so far.

**Comment by litchfld** [comment]
> I don't think they're being deleted at all to be honest (I thought by writing them to disk we were essentially deleting them from the heap)..

Life would probably be easier, were that true.

>  ...but that would not be the cause of the crash I saw as we wouldn't expect to delete them during the event loop, only afterwards no?

Depends on the crash?  I assumed you were getting a bad_alloc.

**Comment by benkrikler** [comment]
It was bad_alloc that was being thrown.  Thinking about it, if the histograms were the cause then this would have bad_alloc-ed right at the start of the run, rather than after the 140th event.  So all I've done is free up more space, but somehow we do see a lot of memory being consumed.  Whether that's memory leaks or your issue of Root consuming a lot of memory early on I'm not sure.  I guess we'll have to see how things go in the next run.
