### ISSUE TITLE
Create a mega TAP generator

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#167]
As outlined in issue #165, I'll create a new TAP generator. 

I'll use the PulseCandidateFinder to remove noisy pulse islands (and hopefully to split up TPIs with multiple pulses), the MaxBin method to get the amplitude, the ConstantFraction method to get the time and the simple integral method for the integral.

Is there a system in place to use functions in other generators? Or do I need to copy the relevant bits of code by hand?

Also, any ideas what it should be called? FirstCompleteAPGenerator? MegaTAPGenerator?

**Comment by benkrikler** [comment]
It would be nice if you could move the algorithms used in the other TAP generators into the system proposed by Phill a while back.  But that depends on your estimate of the effort needed for you to do it.  I don't imagine it to be much, but if it is then for now just copy the code over.

As for naming this, how about SimpleCompleteAPGenerator, although I do like MegaAPGenerator as well..

**Comment by AndrewEdmonds11** [comment]
Is this the plan in issue #142? I can try and do it properly but if it takes me longer than a day then I'll drop it and just copy the code over.

It seems that all I'll have to do is to change the current generators (MaxBin, ConstantFraction, SimpleIntegral) to use this functor approach (i.e. define `double operator() (const TPulseIsland* tpi)` that calculates the energy or whatever). 

Should I create new files for these or just edit the current ones? If it's a new file, do we have a naming convention for them?

**Comment by benkrikler** [comment]
Yup, that's the issue I was referring to and allowing a hard limit of one day to do it seems reasonable to me.  

Rather than make the current generators into algorithms, I would take the code they use in `ProcessEntry` and move it into an algorithm functor then use that in the original generator.  Then the MegaAPGenerator can use those functors as it likes as well as all other generators.

I think I would put these algorithms into a single pair of files (header and implementation) and stick it all in a namespace called algorithms.  The files could be called something like WaveformAlgorithms or TAPAlgorithms and sit in the TAP_generators/utils directory.

**Comment by AndrewEdmonds11** [comment]
So all of this is now done on the feature/AE_split-generators-and-algorithms branch. A few points to make:
- for all the algorithms the pedestal is retrieved from the SQLite database that is produced by `PlotPedestalsAndNoises`. If you don't have the SQLite database locally, then you can create one by running rootana with this module and setting `export_sql=1` in your modules file.
- the various pedestal/trigger polarity/etc. variables should be assigned in the generator and not the algorithm so that we don't get a massive slow-down. I would quite like a way to check that these variables exist before running the algorithm (i.e. fail loudly) but can't think of a way to do it

Anyway, I'll now rebase this branch and open a pull request for people to read through the code and make sure I haven't broken any of the algorithms as I copied them over.

**Comment by AndrewEdmonds11** [comment]
Reopening this since the PulseCandidateFinder still needs adding

**Comment by AndrewEdmonds11** [comment]
Do we want to throw out overflowed/underflowed pulses at this stage or shall I leave that for a later run?

**Comment by benkrikler** [comment]
How obvious is it that they've over / under flowed?  My feeling is keep them still for efficiency checking purposes.

**Comment by AndrewEdmonds11** [comment]
Well, it would be easy to check if that's what you mean. In terms of how they would appear on the amplitude plot, there would just be a large peak at high amplitudes. I'm also inclined to leave it for the time being so we can see changes as we add things one-by-one (splitting up pulse islands, etc).

It would also be nice to code it well (e.g. as an algorithm) so that other generators can use it if they so wish.

**Comment by litchfld** [comment]
We should keep the overflows, we may want them for vetoing other signal at the analysis level so untill then we should always assume they are there.

**Comment by benkrikler** [comment]
I've merged in Andy's work to get the Pulse finder into this generator, although with a few large modifications.  This seems to be working now, so I'm going to close this.
