### ISSUE TITLE
Odd RunTime plots

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#17]
I remember seeing one of the run time plots having large negative values.

This is probably where either the start or stop time is missing from the ODB then, when taking the difference, we get a large negative value. This will also affect any of the rate plots.

I just need to add a check to MDQ_RunTime and anywhere else the duration of the run is calculated. Is there anything special we should do for runs where this happens?

**Comment by litchfld** [comment]
A failed write to the run DB is considered a valid reason to discard the run, as it suggests the DAQ might have stopped in unhappy way.  I suggest doing the same for the ODB.

**Comment by AndrewEdmonds11** [comment]
So, Phill and I saw this in the Al50(a) picture book (Figure 144).

By eye, I thought this was run 3119 or 3120 but neither of these were in the data set (and also there's _no ODB file for run 3119_) and it's actually run 3118.

Looking in the ODB file of run 3118, we have:

```
Start time = STRING : [32] Wed Dec 18 07:23:09 2013
Start time binary = DWORD : 1387347789
Stop time = STRING : [32] Wed Dec 18 07:23:03 2013
Stop time binary = DWORD : 0
```

So not only is the stop time binary (which is what is used to calculate the run time) zero but also this run looks like it stopped before it started.

So either we're all in for a Nobel Prize for breaking causality or we should **remove run 3118 from our golden runs**.

I will add a check to MDQ_RunTime that will cause alcapana to stop running if this happens elsewhere.

**Comment by AndrewEdmonds11** [comment]
Pretty much done this (0852f468033f30549ca1b03ec7483cbd4ed26a3f) but at the moment I quit alcapana very messily and leaves the terminal in that state where you can't see what you type until you type "reset".

Does anyone know of a non-messy way to quit alcapana? I've tried a bunch of things including returning false when the check fails but alcapana seems to ignore everything and just keep ploughing on.

**Comment by AndrewEdmonds11** [comment]
I'm not happy with the messy way I get alcapana to quit so I decided to look through the RunTime plots in the picture books to see if this problem occurs anywhere else.

It doesn't.

So it's only run 3118 that needs to be removed. I'll delete the branch I was working on and close this ticket

**Comment by AndrewEdmonds11** [comment]
Done. For future reference, the commands I used:

```
git branch -D feature/AE_solving_odd_runtime_plots (delete local branch)
git push origin --delete feature/AE_solving_odd_runtime_plots (delete remote branch)
```

**Comment by litchfld** [comment]
There were a number of runs like this, where the additional stop data (end time, total nbytes etc...) were not saved to the run DB.  Oddly, my records show that 3118 is _not_ one of them - i should go back and look harder this when I have the chance.
