### ISSUE TITLE
TPulseIsland should not return a copy of the contained waveform vector

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#171]
Currently, TPulseIsland's have a method to obtain the vector of ADC samples that makes up the waveform they contain.  This method is used throughout the code, but at the moment it returns a copy of the vector:

```
std::vector<int> GetSamples() const { return fSamples; }
```

rather than a pointer or reference which would be much better from a performance perspective:

```
const std::vector<int>* GetSamples() const { return &fSamples; }
// or 
const std::vector<int>& GetSamples() const { return fSamples; }
```

As discussed on pull request #168, changing this now is not a priority and could break existing code.  We could create a new method (eg. `GetSamplesPtr` )which does what we want, but then the concern is that we'd be in a mixed state and could get unpleasant, subtle bugs.  We also need to be careful as this would effect alcapana as well as rootana.

**Comment by litchfld** [comment]
Returning a const reference should be fine... Since GetSamples() is const and the return is not, the compiler is supposed to always copy at least once

``` C++
// GetSamples() currently returns returns vector<int>
const vector<int> foo = myTPI.GetSamples() // (Double) copy, inefficient but OK
vector<int> foo2 = myTPI.GetSamples() // Ditto

const vector<int>& foo3 = myTPI.GetSamples() // OK. C++ extends temporary lifetime 
vector<int>& foo3 = myTPI.GetSamples() // Breaks C++ does not extend temporary 
```

``` C++
// If GetSamples() returns const vector<int>&
const vector<int> foo = myTPI.GetSamples() // OK, copy direct from member (1)
vector<int> foo2 = myTPI.GetSamples() // Ditto (2)

const vector<int>& foo3 = myTPI.GetSamples() // OK 
vector<int>& foo3 = myTPI.GetSamples() // Breaks (does not preserve constness)  
```

So I think the only cases that break would already do so...  This doesn't guarantee we eliminate all copies (1) and (2), but that's another issue.

**Comment by benkrikler** [comment]
That's a good point.  I'd been thinking that your example (2) would be broken but clearly that's wrong.  So we should be safe in alcapana and rootana to change the TPulseIsland method immediately.

If anyone wants to object go for it now, but since we're seeing issues with memory consumption I would like to change this method as soon as we can, hopefully before Wednesday then.

**Comment by benkrikler** [comment]
The above commit has put this change in.  It also added a new constructor which takes a start and stop iterator to `vector<int>` which is more efficient for copying the vector contents over in the Pulse finder, as well as several setters.  I've incremented the ClassDef as a result of these changes.

**You will need to recompile alcapana now to compile rootana when you next git pull develop**
