### ISSUE TITLE
Unhook this repository from thnam/AlcapDAQ?

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#177]
I was wondering (after Ben's accidental pull request in the wrong place) whether we should unhook this repository from thnam/AlcapDAQ?  It wouldn't show up as "forked from ..." any more, and that's basically fine as we aren't likely to merge anything back into the original.  It also has the advantage that non-forked repositories can be searched it the search box at the top of the page, while forked copies can't (you can only search issues).

As far as I could find out though, this can only be done by the repository owner contacting the GitHub Support humans.   This shouldn't be too painful probably, although I lost the page that described how to do it.

**Comment by AndrewEdmonds11** [comment]
Yes, I think we should do this.

**Comment by jrquirk** [comment]
Since no one has said otherwise, I've contact GitHub about this issue.

**Comment by jrquirk** [comment]
> Hi John,
> 
> Sure thing — that's been done:
> 
> https://github.com/alcap-org/AlcapDAQ
> 
> Glad to help.
> 
> Cheers,
> James
