### ISSUE TITLE
Investigating Dodgy Areas of Plots from Wednesday 6th August

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#178]
As asked for in issue #166, I'm going to look into some of the dodgy areas we had in some of the distributions on Wednesday.

From the presentation, I think we said that these are:
1. ScL: 400 < amplitude < 600 (there's a jump)
   ![scl_amplitude](https://cloud.githubusercontent.com/assets/1848575/3839125/f08ea73c-1e0c-11e4-9bac-83d9ca828cb6.png)
2. ScR: 400 < amplitude < 600 (there's a jump) and ampllitude > 3300 (overflow?)
   ![scr_amplitude](https://cloud.githubusercontent.com/assets/1848575/3839133/0e114aa8-1e0d-11e4-9293-4836a74b3fe2.png)
3. ScVe: 400 < amplitude < 600 (there's a jump) and ampllitude > 3300 (overflow?)
   ![scve_amplitude](https://cloud.githubusercontent.com/assets/1848575/3839134/1841ca2a-1e0d-11e4-8b8b-d0dbf8fc25a6.png)
4. SiR1-2-S: amplitude < 60 and amplitude > 60 (double peak structure)
   ![sir1-2-s_amplitude_zoomin](https://cloud.githubusercontent.com/assets/1848575/3839139/2f3e3e02-1e0d-11e4-907b-5b5d5aa72a31.png)
5. SiL1-1-S: time < 10x10^6 (ramp up)
   ![sil1-1-s_time](https://cloud.githubusercontent.com/assets/1848575/3839151/45d5eb1a-1e0d-11e4-8ea3-0de7b6f4aa68.png)
6. SiL1-3-F: 45x10^6 < time < 55x10^6 (peak?)
   ![sil1-3-f_time](https://cloud.githubusercontent.com/assets/1848575/3839160/62bd0c04-1e0d-11e4-95ba-5a173bc38d8f.png)

**Comment by AndrewEdmonds11** [comment]
I've looked at the ScL pulses and found that they all look like muSc pulses:

![scl_amplitude-less-than-300_example](https://cloud.githubusercontent.com/assets/1848575/3840501/b4f6cfee-1e1e-11e4-9578-ee2ecccd3eb1.gif)

This freaked me out a bit until I realised that the scintillators are now plugged into the CAEN rather than the FADC.

Unfortunately, I optimised the PulseCandidateFinder on run 2808 which had the scintillators plugged into the FADCs and so the parameter value is probably too low.

I'm hoping the jump in the distribution gets solved with this because I've looked at pulses (admittedly whole TPIs rather than whatever the PCF gives us)  with amplitude < 400, < 300 (in ScL) and they don't look like noise which is what we expected.

**Comment by benkrikler** [comment]
Could you include the slow silicon channels in your selection?  There's some strange peak structure at low amplitudes:
![all3563_3702_sir1_2_s_amps](https://cloud.githubusercontent.com/assets/4083697/3841509/787946d2-1e2d-11e4-8b2b-2d4ee88df8bf.png)
![all3563_3702_sil1_3_s_amps](https://cloud.githubusercontent.com/assets/4083697/3841508/787095f0-1e2d-11e4-8b67-78c62d268a43.png)

**Comment by AndrewEdmonds11** [comment]
> Could you include the slow silicon channels in your selection?

That's number 4 on my list ;). I'm going through them one at a time so that I don't feel like I'm getting swamped in pulses.

**Comment by AndrewEdmonds11** [comment]
It's still not obvious, with the fix to PulseViewer, what is going on with the jump in ScL, ScR and ScVe. The PulseCandidateFinder is only finding one good looking pulse that happens to have an amplitude < 400 or > 500. 

I've left that one for the minute and found underflowing pulses in ScVe (there are none in ScR for run 3613) which is what we expected that final peak to be:

![scve_underflowed_pulse](https://cloud.githubusercontent.com/assets/1848575/3844508/cde09154-1e49-11e4-85f2-24b32e583063.gif)

**Comment by AndrewEdmonds11** [comment]
For problem 4, the stuff less than 60 is obviously noise:

![sir1-2-s_amp-less-than-60_noise](https://cloud.githubusercontent.com/assets/1848575/3844830/9882b8cc-1e4c-11e4-9d95-104bd4779973.gif)
![sir1-2-s_amp-less-than-60_noise2](https://cloud.githubusercontent.com/assets/1848575/3844831/9dbf4bfc-1e4c-11e4-92a5-14563ff0d653.gif)

But it's not clear that the stuff above 60 is signal:
![sir1-2-s_amp-greater-than-60](https://cloud.githubusercontent.com/assets/1848575/3844837/a7325242-1e4c-11e4-8de3-1758adfaac86.gif)
![sir1-2-s_amp-greater-than-60_2](https://cloud.githubusercontent.com/assets/1848575/3844841/aaf0082a-1e4c-11e4-8e96-69f67172d506.gif)

And here are those two islands with the detected pulse candidates:
![sir1-2-s_amp-greater-than-60_with-candidates](https://cloud.githubusercontent.com/assets/1848575/3844910/55c49dba-1e4d-11e4-923d-9726987b3c8c.gif)
![sir1-2-s_amp-greater-than-60_2_with-candidates](https://cloud.githubusercontent.com/assets/1848575/3844914/5b19e4aa-1e4d-11e4-8e37-477043ded51e.gif)

**Comment by AndrewEdmonds11** [comment]
For problem 5, could the ConstantFraction method be playing up with these poor pulse shapes (i.e. the pedestal is so unstable). Here's an example which had a time < 10ms and with it's pulse candidate:

![sil1-1-s_time-less-than-10ms](https://cloud.githubusercontent.com/assets/1848575/3845177/f02984fe-1e4f-11e4-8dbc-0138ebe6d3b3.gif)

How would the CF algorithm handle the given magenta section?

**Comment by AndrewEdmonds11** [comment]
The time peaks are from finding too many pulses on a pulse island.

In run 3563, there is a peak at about 92.5 ms with a value of 8. I managed to track down the pulse to this one:

![toomanypulses](https://cloud.githubusercontent.com/assets/1848575/3859587/4474efa6-1f1a-11e4-8d9f-4d591c89e71f.png)

Looks like a lot of our problems could be solved by optimising the PulseCandidateFinder better...

**Comment by AndrewEdmonds11** [comment]
Closing this for the time being. Will reopen (probably on a new issue) if we uncover more problems.
