### ISSUE TITLE
Picture books: zoom z-axis on IslandCounter plots and others as well?

### ISSUE THREAD

**Issue by joegrange** [alcap-org/AlcapDAQ#18]
I see issue #10 saw successful implementation of auto zooming of the y-axis to better see the TPI count structure.  Might it be a simple extension to implement the same zooming feature for the z-axis?  It looks like we're only often using the lowest-bin color so we can't see any structure in the number of events (if any).  I hope there's no red bin hiding somewhere in there that will prevent this...
![51596862-e1b4-11e3-8d7a-85d4b8ab4369](https://cloud.githubusercontent.com/assets/5612602/3068000/0b964040-e289-11e3-8117-a2ed702eebec.png)

**Comment by joegrange** [comment]
(besides providing more info in general, hopefully this will help in tracking down the unstable behavior we see in the above fig)

**Comment by AndrewEdmonds11** [comment]
I think the z-axis automatically zooms in ROOT, right? (Although I can't see the red bin here). Maybe we can set the z-max to something lower?

**Comment by joegrange** [comment]
I think you're right.  We could set z-max lower, but I guess that wouldn't extend well to other distributions.  Perhaps log scale would show features?

**Comment by AndrewEdmonds11** [comment]
Good idea and that is already in the code so will take me a second.

**Comment by benkrikler** [comment]
If it is auto-scaling, whats pushing the color bar to such high levels?
Are the underflow and overflow bins being filled?

**Comment by joegrange** [comment]
Right, it's not clear why we apparently only see one color.  Hopefully after seeing the log scale plot it'll become clear.  thanks andy!

**Comment by AndrewEdmonds11** [comment]
Here's the updated version of that plot with a log z scale (doesn't really show us where the red bin is). I'll send Ben some the rest of the updated plots to go on the web page picture book.

Also, I've realised that the underflow and overflow bins don't get filled in the macros, which may also explain what we saw yesterday with no entries in a channel on our plots but you were seeing them in yours. I'll add a simple stats box with the number of entries.

![hdq_islandcounter_sil2-f_na81_trendplot](https://cloud.githubusercontent.com/assets/1848575/3074163/f2b366f8-e327-11e3-939f-e6f33e394af5.png)

**Comment by AndrewEdmonds11** [comment]
I'm going to close this issue. If you think of a better way to try and find the red bin then open a new issue

**Comment by litchfld** [comment]
Yeah the red bin won't necessarily be any more visible on a log z axis (although the green might give you a clue)  The over/under-flow bins won't alter that: ROOT only uses the in range bins for determining auto-zoom. 

More likely the bins are too small - if the average bin size is less than one pixed some of them must get suppressed when rendered in raster format (on screen, .png, .gif).  [.jpeg would be even worse but no-one uses that, right?] .  I'm not sure exactly what algorithm ROOT uses to do this - it certainly favours anything over blank canvas, but it's entirely possible that it doesn't have any (non-trivial) algorithm for adjacent bins of a histogram.  Best fix is to make sure the number of bins on display is roughly the same as the pixel dimension of the canvas, or lower.

**Comment by litchfld** [comment]
FWIW I'd guess the red bin is on or very near the x-axis. =)
