### ISSUE TITLE
Add candidate pulses to ExportPulse?

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#181]
It would be nice to have the sub-pulses that are detected by the PCF to also be exported with the main pulse island in ExportPulse.

This is not an urgent thing and something that can be added later.

**Comment by benkrikler** [comment]
I think that's a good idea.  We could do it by:
1. passing in the TPI ID and start and stop ranges for each candidate pulse to an overload `AddToExportList` method.
2. Calling the PulseCandidateFinder itself within ExportPulse when asked.  This only makes sense if we don't configure the PCF at run time through the modules file though.

Option 1. seems the correct way to go, option 2 seems the simpler way from an implementation point of view at this time.

**Comment by AndrewEdmonds11** [comment]
I think the second method is fine. Soon the PCF will read the parameter values from the calibration DB so all instances should get the same results. It is something to keep in mind though

**Comment by benkrikler** [comment]
Does that mean the `n_sigma` option will be removed from the constructor in the near future?  If not, then I think the first option above is the way to go.

**Comment by AndrewEdmonds11** [comment]
> Does that mean the n_sigma option will be removed from the constructor in the near future?

No, but it will be n_sigma times whatever the value is in the calib DB. It's possible we could set this different in different modules but if we're only going to use it in two (and we wouldn't use it during production for ExportPulse) then it should be OK.

Also, the problem with the first option is that the start and stop ranges (together known as a `Location` in the PCF) are only stored within the object as well. If you can find a way around that though then be my guest.

**Comment by benkrikler** [comment]
I forgot to close this, but it's been finished.  Just give true as the first parameter to ExportPulse in the modules file and the default PCF for that channel will be passed over the original waveform and sub-pulses will be highlighted in magenta.  This changes the output to a THStack, but the usual draw methods should work on that.

The modules file would look like:

```
[ MODULES ]
......
ExportPulse(true) 
```
