### ISSUE TITLE
Rootana production 3

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#183]
Following from issue #166, we can keep track of readiness for the next production here.

Things I made a note that need doing following today's discussion:
- Generate muSc time offsets for the constant fraction method
- Get 1D histograms and TDiff widths (fit a gaussian to the profile?) from the TDiff plots.
- Get 1D profiles of each 2D TDP amplitude plot.
- Redo Time plots with an amplitude cut to remove noise.
- The Constant Fraction Time algorithm should use pedestals from the sqlite database.
- Optimise the time_difference parameter for the MaxTimeDiffDPGenerator
- Locate the time difference peaks for slow channels and set all TDiff axes accordingly.

An issue I found whilst running last night:
- The path to the pedestals-and-noises db is not an absolute path, and just uses the current working directory.  This should be changed so that we can run from anywhere and consistently obtain the same file (a problem when running on the batch system).

Feel free to add things I've missed below.  When someone takes on one of the above tasks, can we open a separate issue and edit this issue (this description even) to mention it.

**Comment by AndrewEdmonds11** [comment]
Other notes I made from today (some of these aren't tasks):
- optimise the PulseCandidateFinder thresholds
  - this could be an explanation for the time peaks in the fast silicon channels (I'm looking at this in issue #178)
- ScL/ScR/ScVe jump in the amplitude spectrum could be a common trigger problem
  - i.e. another channel is triggering and there is a pulse in ScL/ScR/ScVe that wouldn't have hit the hardware threshold for that channel
- plot autocorrelations if we still haven't resolved the timing problems
  - i.e. plot the difference in time for each pulse with it's neighbours
  - (are the TAPs time ordered? I think they are but can't remember)

**Comment by benkrikler** [comment]
> (are the TAPs time ordered? I think they are but can't remember)

I'm pretty sure the TPIs are time ordered, so as long as the reconstructed time of a TAP is within the limits of the waveform sampled in the original TPI and as long as the pulse candidate finder produces sub-pulses in time order that don't overlap, the TAPs will also be time ordered.  I think these assumptions are safe.

**Comment by benkrikler** [comment]
Ah, erm, I made a bit of a mess with the run database I'm afraid.  The perils of working late.

I ended up tagging rootana as v3, mainly by mistake from naming the release v3.  It seemed better to be consistent so this was carried through until I ran the production, so the run database is full for Al50b rootana v3, but empty for v2.  It may be better to just delete the table, or rename as v2.3 etc.  

Also, the runs that need redo-ing are:
3584
3585
3586
3587
3588
3593
but I didn't (and won't) have time to work out how to reset the database for these run (actually I introduced a duplicate of run 3583 in the process of trying to solve it).  

All the files that were produced are in my home directory under `~krikler_b/out/v3` if anyone wants to run off the TAP_trees or look at the histograms.

I need to confess as well (though this may not be the best place) that I'm on holiday next week, (and so will my inbox be), so I'm not going to be able to help much, I'm afraid.

**Comment by jrquirk** [comment]
I'll fix the database, and try to make some script helpers.

How do we load TAPs? Do we omit alcapana input in lieu of passing a file in the config file? Or do the two get loaded on top of each other?

**Comment by jrquirk** [comment]
I've reset runs 3584-3588 (inclusive) and 3593 in table rootana_v3. You'll have to delete the relevant files yourself. The possible files are an output log, error log, and ROOT file. They'll be in the appropriate data/*/v3 directory, and the log files will have rootana in the name.

**Comment by benkrikler** [comment]
> How do we load TAPs?

I put an example of the module file options to specify to control loading in the pulses back into Rootana.  It's in `production.cfg` but commented out or in `testModules.txt` with some comments and explanation.  

>  Do we omit alcapana input in lieu of passing a file in the config file? Or do the two get loaded on top of each other?

The `LoadPulses` module opens a second file containing the tree created by `SavePulses`.  This file is opened in addition to the input file of some TPIs.  The command line parsing in rootana requires a TPI input file in order to run so for the moment event if you do no waveform analysis you will need to supply this option, and it probably needs to be a real file with a real TPI tree I'm afraid.  

Specifying the TAP tree is done through the modules file, so it's also a lot more inconvenient that the TPI tree specification.  If I get time now I will do some work to make this module more convenient to use.

> I've reset runs 3584-3588 (inclusive) and 3593 in table rootana_v3

Thanks for doing that and sorry for the mess. For future reference what was the command you used?

**Comment by AndrewEdmonds11** [comment]
Ben's away this week (is anyone else?) so what's the plan? Shall we try and do another production run on Al50(b) before Wednesday's meeting so we have some new plots to look at?

I'm currently looking at optimising the PulseCandidateFinder (see issue #184).

**Comment by jrquirk** [comment]
@benkrikler 

Thank you for the explanation. There have got to be a number of solutions to this that can be used after your vacation.

To reset some runs in the production DB

```
sqlite> UPDATE rootana_v3 SET status='C',user=null,start=null,stop=null,out=null,olog=null,elog=null,modules=null WHERE run==3584 OR run==3585 OR run==3586 OR run==3587 OR run==3588 OR run==3593;
```

@AndrewEdmonds11 

Right now I was going to work on getting timing offsets into the pedestal/noise database. This does not require another production run for Wednesday.

**Comment by AndrewEdmonds11** [comment]
> This does not require another production run for Wednesday.

Cool. That's good because this optimisation of the PulseCandidateFinder is going slowly.

> Right now I was going to work on getting timing offsets into the pedestal/noise database.

As I mentioned in another issue, I'm going to try and play around with the SetupNavigator that interacts with the SQLite database. So to avoid stepping on your toes, what's your plan? Are you going to produce a module similar to PlotPedestalAndNoise that gets the values for us and puts them there?

EDIT: carrying over in issue #186

**Comment by jrquirk** [comment]
> Are you going to produce a module similar to PlotPedestalAndNoise that gets the values for us and puts them there?

Yep. My plan was to make muSc timing correlation plots like in alcapana for the different timing algorithms and then at end-of-run just plug them into the pedestals-and-noise.sqlite.

**Comment by AndrewEdmonds11** [comment]
So I think from the meeting today the plan is to run over the Al50(b) dataset early next week and get all the time shifts.

I think we'll want to store the time shifts relative to the muSc in the calibration DB but we'll also want plots from the fast and slow channels so we can look at creating TDPs with realistic windows in the following run.

I have a few of questions:
- are all the modules we want ready? do they need some testing/tweaking/features adding?
- will we also want to store the time shift between the fast and slow channels in the calibrated DB as well as the muSc time shifts?
- are there any other TDP modules we'll want for the next run that we can test now? PlotTDPs does a lot but it seems it's mostly within a detector. Do we want modules that will compare detectors?

**Comment by jrquirk** [comment]
- The modules we want are not ready. I'm still working on getting the timeshifts relative to the muSc into the database, and then we have to update things to use the database
- That seems like a good idea, but I would say let's not make this a goal for next week.
- I do not know.

**Comment by AndrewEdmonds11** [comment]
> That seems like a good idea, but I would say let's not make this a goal for next week.

Oh, I thought it was the same module as the one for muSc and it would just be an option that we set when we run... Looking in the plotters/ directory it seems we have a few different TDiff modules. Which are we using? Are the other ones so old that we should delete them/move them into a legacy subfolder?

For the TDP modules, I was thinking that we could have the time differences between different detectors plotted again (mainly as a sanity check during the next run). Do we need to write a separate module or can the plotter modules handle TDPs as well as TAPs? (I'm thinking Ben or Phill might have put something fancy into the framework but I don't know)

**Comment by benkrikler** [comment]
Hey everyone, I'm back!  

> - are all the modules we want ready? do they need some testing/tweaking/features adding?

Could someone summarize the modules we were hoping to run with for the next production?  I wanted to tweak the axis limits for some of the TDiffs plots after the last run, but if we get in the corrected time offsets then this shouldn't be necessary.  

> Looking in the plotters/ directory it seems we have a few different TDiff modules. Which are we using? Are the other ones so old that we should delete them/move them into a legacy subfolder?

The TDiff plotting modules we have are:
- **PlotAmpVsTDiff** - Original rootana module, should be deprecated to legacy
- **PlotAmpVsMuScTDiff** - My first attempt but it plots ALL TAP sources against ALL MuSc sources, so it produces a lot of histograms which ate up our memory.  If we reworked this to compare the same generators only then it would be safer.
- **PlotTDiff** - The version mainly written by Damien that takes two specific channels and plots the TDiffs between them.  If you're interested in a specific combination of channels then this is the one to use.

> Oh, I thought it was the same module as the one for muSc and it would just be an option that we set when we run..

If you want to use the existing modules to produce the TDiff plots themselves then either we come up with a modules file by hand and use the `PlotTDiff` module multiple times, or we can enhance the `PlotAmpVsMuScTDiff` module to make fewer plots and use a channel other than muSc to pair pulses against.  

What work's gone on this week for this?  @jrquirk have you got another module in progress for to do create the offsets?

> For the TDP modules, I was thinking that we could have the time differences between different detectors plotted again (mainly as a sanity check during the next run).

So this would be to use the TDP pairing to apply a cut on unpairable pulses?  I guess you'd use the fast timing in the TDiff but the slow amplitudes right?

> Do we need to write a separate module or can the plotter modules handle TDPs as well as TAPs? (I'm thinking Ben or Phill might have put something fancy into the framework but I don't know)

We decided to keep the TDP and TAP base classes separate since they contain different contents.  But because of this, plotting modules need to be written.  That makes sense in a way since any amplitude plotting module, for instance, would have to specify which amplitude to use and what to do if there is no paired pulse in the fast or slow channel you're looking at.  

I can think of things we could do if we want to avoid copying code around, such as a similar structure to our TAP generator algorithms, or an intermediate extension to the BaseModule class for all plotting modules to derive from.  But if we don't want to go down another of these layers then just copying the modules of interest for now will probably be good enough.

Also, I've read the phrase 'calibration DB'  around.  Does this mean we're looking into getting energy calibration done as a next goal or is this mainly with respect to timing calibration?

**Comment by AndrewEdmonds11** [comment]
Welcome back!

Should we not just use Damien's TDiff module and specify all the combinations we want? Is the MuSCTDiff plotter quicker or something when you are keeping one detector the same?

Copying the plotting modules for the TDPs is fine. I don't think we should spend much longer on abstract framework stuff. Should we have a separate source folder for TDP and TAP plotters? Or do the modules have to be uniquely named anyway?

The calibration DB is just the pedestals and noise database that we are extending to include time shifts. Later we can use it for energy calibration but not at this time.

**Comment by benkrikler** [comment]
Thanks!

> Should we not just use Damien's TDiff module and specify all the combinations we want?

I think that's right.  The only reason I can think to do otherwise is convenience.  Should we move both the other TDiff plotters into the deprecated directory then?

> I don't think we should spend much longer on abstract framework stuff. 

Sounds reasonable to me.

> Should we have a separate source folder for TDP and TAP plotters? Or do the modules have to be uniquely named anyway?

Each module needs a unique name.  Should we just suffix them with the pulses they're using (TAP, TDP) to plot things?  I'll rename the existing modules as well if we agree this.  We can at the same time move the modules into a separate directory for TAPs and TDPs.  It just depends how many files there are, though my feeling right now is that it's not really necessary.

**Comment by jrquirk** [comment]
I've created a module that stores the time offset for each run+channel+generator+config combo we want. For all channels enabled, it adds an additional ten minutes maybe onto each run if we calculate the muSc offset for MaxBin and CF(60%). To do this we need to have a generator with the time offset set to zero, so these generators would be in addition to the main one.

**Comment by AndrewEdmonds11** [comment]
> so these generators would be in addition to the main one.

So we want an algorithm that gets time simply from the time stamp and the clock tick. Would the associated generator want any other field filled to work with your time offset calculator module? I'll add it to my ToDo list...

**Comment by benkrikler** [comment]
So where are we up to?  Any chance of running properly by Friday?

**Comment by AndrewEdmonds11** [comment]
So from the meeting today, the plan is this to re-run tomorrow afternoon (UTC) with the new time shifts stored in to the calib DB. We'll have to run twice: once to generate the TDiff values and another to use them and get the same plots as we had last time.

The immediate plan is this:
- John will code SetupNavigator to output the TDiff values into CSV format
- Andy will copy John and move the pedestal and noise values into SetupNavigator
- John will write a script to convert CSV to SQLite database
- Run

I'm going to play with the issues on GitHub and move some to the next milestone so that we are all on the same page.

**Comment by benkrikler** [comment]
> once to generate the TDiff values

And the pedestals and noise database right?  We should have a modules file in the repository that does all the calibration stuff I think.

**Comment by AndrewEdmonds11** [comment]
@jrquirk, was the actual run done or do we just have the calibration DB?

I will get the config file for the picture book ready by testing locally on one file from the new master branch while I wait for the answer

**Comment by jrquirk** [comment]
I didn't save the output. But the pedestals plotter doesn't take long to run, and we want to rerun the PlotTAP_TDiff generator with the timing offsets so I think by chance it's not a huge deal.

**Comment by AndrewEdmonds11** [comment]
Ok, I've run locally with the production.cfg file we have.

Do we want to add the TDiff combinations of all the channels with muSc to check the time offsets? The only ones we have in there are the ones for Jim's analysis goals.

We also have to add the generators with the correct constant fraction for each channel (locally, I've copied them from timeoffset_calib.cfg)

Once that's finalised we can do production run 3

**Comment by AndrewEdmonds11** [comment]
Ok, I'm just going to start a release branch for the next production run. I'll make a production.cfg script and then we can run and I can generate a picture book in the morning.

**Comment by AndrewEdmonds11** [comment]
Ok, we seem to be on v5 but production run 3. Don't know what's gone wrong there but I guess it doesn't matter

**Comment by jrquirk** [comment]
There have been two other versions. I did a test run at some point (v4) and because we don't have sub-versioning the previous rootana_v2.whatever was v3.

**Comment by AndrewEdmonds11** [comment]
Ah, OK. So we should only use major version numbers for tags. That's my mistake.

**Comment by AndrewEdmonds11** [comment]
Ok, everything's ready for production now.

Just to check I have the correct command to start a new run:

```
./run_production.py --production=rootana --new=rootana_v5 --version=5 --dataset=Al50b --display
```

and then for other people to join it's:

```
./run_production.py --production=rootana --version=5 --dataset=Al50b --display
```

Is that correct, John?

**Comment by jrquirk** [comment]
Close. When you use `version` and the `new` args at the same time, `version` actually means what version of alcapana you want to use. So in the first command it should be `--version=3`.

Also, I cleaned up the bad tables rootana_v4 and rootana_v5. So it'll be

```
./run_production.py --production=rootana --new=rootana_v5 --version=3 --dataset=Al50b --display
```

for you and

```
./run_production.py --production=rootana --version=4 --dataset=Al50b --display
```

for everyone else.

**Comment by AndrewEdmonds11** [comment]
Cool. 

Also, I just want to clarify which alcapana work directory the jobscripts use. From reading them it seems to be production/ but to compile rootana we need to do $USER

**Comment by AndrewEdmonds11** [comment]
Ok, I've started. Anyone else who wants to join, a few things to remember:
- checkout the master branch
- compile alcapana in `work/production` and `work/$USER` where $USER is your uername on merlin
- link to John's calibration.db (`ln -s ~quirk_j/AlcapDAQ/analyzer/rootana/calibration.db calibration.db` **EDIT:** softlink this to your home dir `~`)

I've started but don't have much quota left so we'll see how it goes (I may need to delete some stuff)

**Comment by AndrewEdmonds11** [comment]
So my jobs seem to be failing but I don't get any log files in `~/data/log` to help me work out what's going on.

The jobs submit and then fail quite quickly. Anyone else having trouble?

**Comment by jrquirk** [comment]
When a job fails it's files are cleaned up and it is resubmitted. I haven't tried yet. Were you able to run it okay in an interactive session?

**Comment by AndrewEdmonds11** [comment]
Ok, after clearing some space (by deleting my v1, rootana output files). I now get a log with the following message:

```
ERROR: Require at least positional arguments input file, output file, and modules file as inputs!
```

which makes sense but are these not worked out in the jobscripts?

Have I mis-set an environment variable?

**Comment by AndrewEdmonds11** [comment]
> Were you able to run it okay in an interactive session?

Sorry, just seen your comment. Yes I was able to run it interactively

**Comment by jrquirk** [comment]
I'm looking into it. The error is from file analyzer/batch/scripts/batch_rootana.sge. But you may have already found that.

**Comment by jrquirk** [comment]
I'm uploading a fix.

**Comment by jrquirk** [comment]
This problem is fixed.

**Comment by AndrewEdmonds11** [comment]
Excellent. Thanks, John. What was the problem?

**Comment by AndrewEdmonds11** [comment]
Now, I'm getting a no CalibDB error. Where should my soft link go?

**Comment by jrquirk** [comment]
[This](https://github.com/alcap-org/AlcapDAQ/blob/master/analyzer/batch/scripts/batch_rootana.sge#L12) line used to say not equal to 4 instead of less than three. I don't know how it snuck in there, but it's left over from when the calibration argument was introduced into the run_production.py script.

**Comment by jrquirk** [comment]
SetupNavigator looks in the current directory, which unless otherwise noted is your home directory for grid jobs. Soft link from there.

**Comment by AndrewEdmonds11** [comment]
Cool. Thanks for your help, John. Everything seems to be running fine for 1 minute 52 seconds and I've got to dash. Hopefully, it will all work out well.

BTW I may have messed up the production.db while trying to fix things earlier (I think I started a production twice). I'm not sure how bad it is so apologies for that.

**Comment by jrquirk** [comment]
It's extremely easy to drop bad tables and remove their entries from the DB, and as long as people specify the version they want to produce with the --version argument, they won't even notice.

**Comment by jrquirk** [comment]
Andy, it seems you're running on v10, so I will run on the same.

**Comment by jrquirk** [comment]
I also have the TAP TDiff plots zoomed in to -5us to 5us in ~quirk_j/data/out/v12

**Comment by AndrewEdmonds11** [comment]
Cool. I'll try and create a picture book with v12 but I think it's worth noting that we can set new axis limits with the new picture book code (we have to have the same number of bins though) without having to re-run.

**Comment by AndrewEdmonds11** [comment]
So, I'm having problems with the computer I work on at the moment due to memory leaks in the picture book code. But an example plot from each chapter is shown below over 10 runs.

I have made a couple of additions to the picture book code:
- can now ask for projections of histograms (used for TDiff)
- can ask for histograms to be added together run by run (used for the 2D PlotTDPs plots)

TAP Amplitudes
![trendplot_hmusc_firstcomplete_ constant_fraction 0 60 _amplitude_9](https://cloud.githubusercontent.com/assets/1848575/4059962/56eaf998-2deb-11e4-9629-66cc44ad4183.png)

TAP Times
![trendplot_hge-f_firstcomplete_ constant_fraction 0 90 _time_9](https://cloud.githubusercontent.com/assets/1848575/4059966/5e6ccb4c-2deb-11e4-9cd2-50c2bff5067f.png)

TAP Integrals
![trendplot_hge_s_firstcomplete__constant_fraction_0_60__integrals_177](https://cloud.githubusercontent.com/assets/1848575/4059971/77a0e4cc-2deb-11e4-831b-c81b8a2d8030.png)

TAP TDiffs
![trendplot_hscl_sil1-3-f_firstcomplete_ constant_fraction 0 40 tdiff_ampa_9](https://cloud.githubusercontent.com/assets/1848575/4059979/8893891a-2deb-11e4-8f93-aa2a3c57f8b6.png)

TDP Amplitude Comparison
![hge_maxtimediff__alias_detector_pulses__time_difference_1__amp_9](https://cloud.githubusercontent.com/assets/1848575/4059989/9a149e2c-2deb-11e4-88fe-24e06c29b632.png)

TDP Time Comparison
![hge_maxtimediff__alias_detector_pulses__time_difference_1__times_9](https://cloud.githubusercontent.com/assets/1848575/4059994/a5854fd6-2deb-11e4-9e41-79c5aea2758a.png)

TDP Scale Factor
![trendplot_hge_maxtimediff__alias_detector_pulses__time_difference_1__scale_factor_9](https://cloud.githubusercontent.com/assets/1848575/4060010/bc780936-2deb-11e4-9b4d-8b5653570d05.png)

I will hopefully be able to run over all the runs soon. Any comments about changes to these plots (log scales etc)?

**Comment by benkrikler** [comment]
Log scale the z-axis for the 2d plots I think. And use Phill's palletes perhaps (mainly for consistency).

**Comment by benkrikler** [comment]
What happened to this production then?  Did the picture book ever finish getting made?

**Comment by AndrewEdmonds11** [comment]
> What happened to this production then?

I think it's the data in John's out/v12 directory that is the result of this.

>  Did the picture book ever finish getting made?

No, there's a massive memory leak that I'm trying to get to the bottom of (ran with valgrind over the weekend so need to look at that). It was also running very slowly.

My supervisor has said that I should move over to work on the MC as well so I've not been so busy writing GitHub comments :)

**Comment by jrquirk** [comment]
Andy posted the picture book to [Analysis-R13:169](https://muon.npl.washington.edu/elog/mu2e/Analysis-R13/169) (prod_run_3.pdf).
