### ISSUE TITLE
Copy of the pedestal-and-noise database

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#189]
I propose changing the `[]` to an `at()` [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/framework/SetupNavigator.h#L26-L29). I'm getting a bunch of zeros for the pedestal.

Also, did we ever agree on a location to store it? Will it just be in ~edmonds_e/AlcapDAQ/analyzer/rootana?

And finally, is there a copy of the DB I can copy over for testing?

**Comment by AndrewEdmonds11** [comment]
Ben's got the most up to date version of the DB in his data dir somewhere

**Comment by jrquirk** [comment]
Thank you.

**Comment by litchfld** [comment]
How large are these DB files?  Unless they are weirdly large they could be shared by the repository (that was how I always imagined this working.)  

GIT handle binary files much better than CVS, the only issue is that they are hard to merge, so we'd probably want to a rule of not modifying them in a feature branch, or something similar.  

Alternatively they could be stored as SQL dumps and the actual DB rebuilt as part of compilation.

**Comment by litchfld** [comment]
I should add that if we don't put the files in GIT then we need to find an alternative way of archiving them, and making them accessible at other locations.  Calibration constants are too important for the primary source to be a file left lying round in someone's personal directory tree.

**Comment by benkrikler** [comment]
> Alternatively they could be stored as SQL dumps and the actual DB rebuilt as part of compilation.

That would give us access to git(hub)'s diff tools to view what parts of the DB were changed, when and by whom.
