### ISSUE TITLE
Passing arguments to TAP generators

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#191]
I know we've gone over this before, but I can't remember how to pass options to a generator. I'm looking into it, but does anyone remember?

I'm trying to generate a bunch of files with different threshold cuts/constant fraction thresholds, and don't want to have to babysit the jobs as the time they take is in the uncomfortable range between short enough to watch it and long enough to leave it.

**Comment by AndrewEdmonds11** [comment]
I think it's just the same as any other module, right? (I had a quick glance at Ben's GausFitAPGenerator and that seems to be the case)

I had problems passing options from the generator to a utility class (PulseCandidateFinder) but I don't think that's an issue here.

**Comment by jrquirk** [comment]
I'm having issues all the same. Here is the constructor for my class and the last line

```
CFTimeNoShiftAPGenerator::CFTimeNoShiftAPGenerator(TAPGeneratorOptions* opts) :
    TVAnalysedPulseGenerator("CFTimeNoShiftAPGenerator",opts) {
  fConstantFractionTime.constant_fraction = opts->GetDouble("constant_fraction", 0.10);
  fThresholdPercent = opts->GetDouble("threshold_percent_of_range", 0.05);
  std::cout << "Using CF fraction " << fConstantFractionTime.constant_fraction << "." << std::endl
        << "Using CF cut percent " << fThresholdPercent << "." << std::endl;
  if (fConstantFractionTime.constant_fraction <= 0.00 || fConstantFractionTime.constant_fraction >=1.00)
    throw OptionsError();
  else if (fThresholdPercent < 0.00 || fThresholdPercent >= 1.00)
    throw OptionsError();
}
...
ALCAP_TAP_GENERATOR(CFTimeNoShift,threshold_percent_of_range,constant_fraction);
```

I included the output statements because then, when I run with this configuration file

```
list_modules
dump_contents

[ MODULES ]
analyse_pulses = MakeAnalysedPulses
l2_s_musc = CalcCoarseTimeOffset( SiL2-S   , muSc ) 
l2_f_musc = CalcCoarseTimeOffset( SiL2-S   , muSc ) 

[ analyse_pulses ]
muSc=CFTimeNoShift(0.00, 0.50)
muSc+=MaxBinNoShift(0.00)

SiR2-S=CFTimeNoShift(0.00, 0.50)
SiR2-S+=MaxBinNoShift(0.00)

SiL2-S=CFTimeNoShift(0.00, 0.50)
SiL2-S+=MaxBinNoShift(0.00)
```

I get the following output

```
[quirk_j@merlinl01 rootana]$ ./rootana -i ~daniel_a/data/tree/tree03739.root -o test.root -m configurations/time_offset.cfg
Starting event
Number of modules requested: 3
Raw data tree contains 5668 entries.
Processing file, which may take a while...
Will analyse all 29 channels
Using CF fraction 0.1.
Using CF cut percent 0.05.
Using CF fraction 0.1.
Using CF cut percent 0.05.
Using CF fraction 0.1.
Using CF cut percent 0.05.
Processed     0/5668  ( 0%)
...
```

So in my constant fraction constructor, the default is getting returned  in the `opts->GetDouble(...)` method. Has anyone successfully passed arguments to a TAP generator before?

I think this question will have to wait for Ben to get back, but it never hurts to ask.

I tried the same things with GaussFit; as in I put in a print out statement and tried the constructor `muSc+=GaussFit(1.,1.,1.,1.,1.)` and the defaults were still loaded.

**Comment by jrquirk** [comment]
The problem was that the names of the variables aren't getting registered; instead they are just the argument number. Switching to `opts->GetDouble("0", 0.05)` works. One of the problems is [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/framework/TemplateFactory.tpl#L16-L26), where again we should just throw. Without putting a print out statement, there'd be no reason to assume things aren't working. Even the modules file that get's dumped to standard out is just the file that was loaded, not the values that were set.

**Comment by jrquirk** [comment]
Now I'm having an issue where if I run the same generator multiple times with different configurations on the same detector

```
muSc=CFTimeNoShift(0.00, 0.10)
muSc+=CFTimeNoShift(0.00, 0.20)
muSc+=CFTimeNoShift(0.00, 0.50)
muSc+=CFTimeNoShift(0.00, 0.75)
```

then the options are only loaded correctly for the first instance, and the rest get the default arguments in the `opts->GetDouble("0", 0.1)` call.

_Edit_: Also the next three get tagged with the generator config string "any", only the first one gets correctly labelled something like "{0=0.00,1=0.10}". I'm looking into it.

**Comment by jrquirk** [comment]
[Here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/MakeAnalysedPulses.cpp#L162-L186):

```
std::stringstream sstream;
...
for(gen=generatorList.begin();gen!= generatorList.end();gen++){
    ...
    if(start_br!=std::string::npos){
        ...
        sstream.str(gen->substr(start_br,end_br-start_br));
        ...
        for(int count=0; std::getline(sstream, arg,','); count++){
            opts->AddArgument(count,arg);
        }
    }
    ....
}
```

The `std::stringstream`'s eof bit gets set on it's first time through the `for` loop. If we move it in the scope of the loop the problem should be solved.

**Comment by jrquirk** [comment]
I'm going to describe one of the problems as I understand it.

The issue above where we TAP generators can only reference positional arguments instead of named ones stems from [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/framework/TemplateFactory.tpl#L16-L26), [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/TAPGeneratorFactory.h#L26-L27), and [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/MakeAnalysedPulses.cpp#L174); some of this code I'll reproduce below as needed.

When a TAP generator is created, someone it's named arguments are registered like this

```
#define ALCAP_TAP_GENERATOR( NAME , ... ) \
RegistryProxy<NAME##APGenerator,TVAnalysedPulseGenerator,TAPGeneratorOptions,TAPGeneratorFactory> p_AP##NAME(#NAME, #__VA_ARGS__);
```

This causes the factory to map, for example, CFTimeAPGenerator->(constant_fraction, threshold_fraction, ...) and all other names of the arguments (and similarly for all TAP generators). Then you start instantiating the options for the generators that you will pass to the generators' constructors like so

```
opts=new TAPGeneratorOptions(detector+"::"+generator);
```

But when you try to load in the arguments, it looks for the argument list for a module called "musC::CFTimeAPGenerator" or something like that, which wasn't how it was registered via the `RegistryProxy` macro (it had the name CFTimeAPGenerator). So then the module's argument list isn't found (though because of the use of the `map::operator[]`, it is added as a module with an empty arguments list).

So then I'm taking out the `detector+"::"` and changing the `GetArgumentName` function to the following

```
{
  return fModuleArguments.at(module).at(argument);
}
```

I've reasoned this two ways
1. The TAPGeneratorOptions don't seem to need unique names. They're never referred to by name as far as I can see; and even now I am running okay with multiple configurations for detector+generator pairs, which share the same TAPGeneratorOptions names.
2. I can't think of a reason to catch an out-of-range exception (this is as the beginning of job, so we don't even need to exit gracefully and save the data because we haven't done anything yet). If someone enters too many arguments via the constructor-like method in a configuration file, they've probably made a mistake. And a module that is being passed options should not, for any reason I can think of, _not_ be registered.

**Comment by jrquirk** [comment]
Apparently the argument lists aren't loaded in until after the TAP generators have already been created. At the time of instantiating a CFTime instance these are the contents of fModuleArguments

```
CalcCoarseTimeOffset: det1 det2
LoadPulses: file_name tree_name
MakeAnalysedPulses: slow_gen fast_gen
MakeDetectorPulses: default_algorithm
MakeMuonEvents: algorithm
PlotPedestalAndNoise: x_max
PlotTDPs: slow_ch_cut fast_ch_cut
PlotTDiff: det1 det2
PulseViewer: source trigger summarize
```

No TAPs. Later on `CFTime: constant_fraction threshold_percent` etc. show up, but it happens too late.

**Comment by jrquirk** [comment]
I think the argument list is registered with a TAPGeneratorFactory, but then it's sought after [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/framework/ModulesOptions.cpp#L82)? I think TAPGeneratorOptions should override the AddArgument method of modules::options to grab the instance of TAPGeneratorFactory, not modules::factory. I'll try this tomorrow.

**Comment by jrquirk** [comment]
It worked. To sum up, we can now use named arguments in TAP generators and we get an exception if too many arguments are passed in the constructor-like declaration in a configuration file.

Though this is bad form, this is part of my toff_rootana feature branch instead of its own. I'm working on other things still and want to wait until next week when @benkrikler has had a chance to look through this in case there are any issues I overlooked. So this won't be merged until next week, and this shouldn't matter because if this issue was pressing others would have noticed this first.

**Comment by benkrikler** [comment]
Wow, ok.  So I've had a look through and to try and summarize the differences you've introduced:
- TAP Generator options get named with the generator name only and not the channel (what was the reason  for this?)
- Re-instantiate the stringstream within the loop over all arguments (did `sstream.str("")` not work?).
- Copy the implementation of `AddArgument` from ModulesOptions into TAPGeneratorOptions.  Did you see that the method is public in `modules::options` and `TAPGeneratorOptions` derives publically from this class?  I don't think you need to do this at all..
- Throw an exception for excess arguments as opposed to numbering them, which seems fine to me.

Anyway, if you get the behaviour you want, feel free to merge and then I'll do a tidy up on a new branch.

**Comment by jrquirk** [comment]
Welcome back Mr. Krickler. As is evident, we've missed you.
- The reason one might name the TAPGenOpts would be to give each instance a unique name, but this goal wasn't met anyway given that the generator config string isn't included in the name so the they aren't guaranteed unique anyway. The name (stored in the field fModuleName) is only used once in the entire code as far as I can tell, and that's [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/framework/ModulesOptions.cpp#L82), when the argument name registered with the factory needs to be used which is, in fact, just the TAPGen name without the channel name (which makes sense, all instances of the same TAPGen are going to have the same names of their arguments). If we gave the TAPGenOpts a unique name, we'd have to strip it down at that point in the code, but again there's no reason thus far to have unique names.
- The `stringstream.str("")` method sets the data in the ss to empty as far as I can tell, but after the first loop through, when the ss streams in the last little bit, it's end-of-file bit is set. Setting the data to the null char does not reset the eof bit.
- I did notice that the `AddArgument` could be used by TAPGenOpts, and this is evident by the fact that the code doesn't crash. However, the `RegistryProxy` method, called at the bottom of our TAPGens implementation code, includes in the template arguments a factory to register with. The publicly derived `AddArgument` always calls the `modules::factory` instance, which TAPGens are not registered with, instead of the correct TAPGenFac (I assume this is the same for TDPs and TMEs). I just copied the code over to a TAPGenFac implementation file and changed `modules::factory->Instance()` to `TAPGeneratorFactory::Instance()`.

Does this make sense?

**Comment by benkrikler** [comment]
Thanks John.
- That makes total sense, and this is definitely the right way to do it for now.  Perhaps we should be passing in a source ID instead, which would allow the internal methods for arguments to work but this is definitely the right way to do it for now.
- I'd never thought of the 'eof' issue before, and in fact that could explain some previous issues I've had with stringstreams. Seems we need to call `std::stringstream::clear()` as well as `str("")`.  
-  Oh ok, I see what you're saying.  A solid solution could get a bit messy (more templating etc) so for now let's keep it this way.

**Comment by jrquirk** [comment]
I want to preface this saying I don't think it matters too much because this part of the code shouldn't be changing much.

When it comes to reseting the stringstream, it's good practice to declare it in the scope of the loop it will be used in. First, that means we don't need to call the clear/str functions, so there's less code to read through. Second, it's more obvious to maintainers that the stringstream is used only in the scope of the loop.

You might say that theres time in the allocation/deallocation, but it's possible the compiler can optimize at least some of this away (we wouldn't know without checking, though this is certainly the case for primitives if not classes). But even if there is no optimization, this is beginning of job stuff, so we can afford to pay a little extra in speed for maintainability.

This is not a habit we've been practicing experiment-wide, but as I come across things like this I move them in scope so that if I look at the code later, I don't have to dig around for the variable declaration and check where it might be used.

**Comment by benkrikler** [comment]
> I want to preface this saying I don't think it matters too much because this part of the code shouldn't be changing much.

In this case, that's true and this code is called only once per source during the entire run so it won't have any impact either way.  Hopefully stringstreams should never be needed during the main event loop, but if they are we should consider how to optimise their use.

The purpose of this code is to parse the constructor-type specification of a generator and I put functions into `modules::parser` (implemented in the `framework/ModulesParser.*` files) to do exactly this.  I think I wrote MakeAnalysedPulses before this code existed, and forgot to go back and add it in, but it's used in the way we read in modules in `ModulesReader.*`.

**Comment by litchfld** [comment]
Sorry i'm behind on all this (on a quick break now).

> Even the modules file that get's dumped to standard out is just the file that was loaded, not the values that were set.

Checking the values are set correctly for a module is an excellent candidate for a unit test...
