### ISSUE TITLE
Pulse Candidates and Constant Fraction

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#192]
The constant fraction method find the max bin and then walks backwards until it hits _xx_% of the peak between the peak and the pedestal

What is the beginning of the PCs? Does it go down to pedestal? (@AndrewEdmonds11)

**Comment by AndrewEdmonds11** [comment]
For the slow pulses, definitely [(see here)](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/utils/PulseCandidateFinder.cpp#L205-L217):

``` C++
// Track back until we get to the pedestal again so that we get the whole pulse (Ge-S pulses were being cut-off at the start)
location.start = (int)(i);
for (int j = i; j > 0; --j) {
  sample_height = polarity * (samples[j] - fPedestal);
  if (sample_height <= 0) {
  location.start = (int)(j);
  break;
  }
  else if (j == 1) { // if we are at the last iteration
  location.start = 0; // set the location to the start since we haven't gone below pedestal again
  }
}
```

I don't have the same thing for the fast pulses (I can add it in though if you like) but we do take a couple of samples beforehand [see here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/utils/PulseCandidateFinder.cpp#L129-L155):

``` C++
int n_before_start_samples = 2; // take a few samples from before the official start
...
location.start = (int)(i - 1) - n_before_start_samples;
```

Now it is only the Ge-F and the scintillators that use the fast algorithm and this value of 2 is pretty much OK for those. 

If you want to have a look at pulse candidates yourself you can do it by setting MakeAnalysedPulse with the debug option and setting the channel you want exported in the code [(see here)](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/FirstCompleteAPGenerator.cpp#L70-L80). It just dumps the sub-pulses into the top level directory of the output file and you'll need to ExportPulses with PulseViewer or uncomment the code [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/FirstCompleteAPGenerator.cpp#L113-L116) to get the original TPI.

Also, here's a macro I use to plot the candidates on top of the island:

``` C++
void PlotPulseCandidates() {

  TFile* file = new TFile("output.root", "READ");

  std::string detname = "SiL1_2_F";
  std::string event_number = "3649";
  std::string pulse_number = "0";

  std::string islandname = "ExportPulse/Pulse_" + detname + "_" + event_number + "_" + pulse_number;
  TH1D* hist2 = (TH1D*) file->Get(islandname.c_str());

  hist2->SetLineWidth(2);
  hist2->Draw("HIST");

  const int max_sub_pulses = 10;
  for (int i_subpulse = 0; i_subpulse < max_sub_pulses; ++i_subpulse) {
    std::stringstream subpulsename;
    subpulsename << "hSubPulse_" << detname << "_Event" << event_number << "_Pulse" << pulse_number << "_SubPulse" << i_subpulse;

    TH1D* hist3 = (TH1D*) file->Get(subpulsename.str().c_str());
    if (hist3) {
      std::cout << subpulsename.str() << std::endl;
      hist3->SetLineWidth(2);
      hist3->Draw("SAMES");
    }
    else {
      break;
    }
  }
  /*  TLegend* legend = new TLegend(0.3, 0.85, 0.6, 0.75, "");
  legend->SetBorderSize(0);
  legend->SetTextSize(0.04);
  legend->SetFillColor(kWhite);
  legend->AddEntry(hist2, "Pulse Island");
  legend->AddEntry(hist3, "Pulse Candidate");
  legend->Draw();
  */
}
```

I hope that helps

**Comment by jrquirk** [comment]
That does help. So the slow pulses and even the silicon fast pulses are okay. And the scintillators/ge-f have rise times that are usually a couple of bins.

Thank you.
