### ISSUE TITLE
Create a TAP Algorithm and Generator with no time shifts

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#194]
As requested in issue #183, to calculate the correct time shifts, we need a generator and algorithm that doesn't fill in the time of a TAP with the time shift.

I propose to call the algorithm `NoShiftTime` and the generator UncalibratedAPGenerator, since we may want something similar at a later date for the amplitude.

**Comment by AndrewEdmonds11** [comment]
Also, I will just use the time stamp for determining the time. I think this is correct since we would be adding time shifts to this anyway?

**Comment by jrquirk** [comment]
Hope you haven't spent too much time on this today.

The goal is to use each of the timing methods to determine the shift for them. So I've been using two new TAP gens, MaxNinNoShiftAPGenerator and CFTimeNoShiftAPGenerator. The simply have the algorithm.time_offset set to zero instead of getting it from TSetupData. So this is done.

**Comment by benkrikler** [comment]
Do we need new generators at all?  Couldn't we add a `no_time_shift` option to the main generators which disables the use of the database value? It would mean more code re-use...

**Comment by AndrewEdmonds11** [comment]
Oh right, I completely misunderstood then. I thought having a generator with no calibration was the idea and then you use that to determine the offset somehow.

I'll delete the pull request then. Luckily, it wasn't too much work :)

**Comment by jrquirk** [comment]
> Couldn't we add a `no_time_shift` option to the main generators which disables the use of the database value?

Yes, we could. I'll switch over to doing that instead.
