### ISSUE TITLE
Add ZoomAxis Function to the Picture Book Program

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#195]
In the old version of the picture book code, there was a function to zoom the axes to sensible values (since some histograms are created with limits that are large enough for one channel but too large for others).

This should be simply copying some code over.

**Comment by AndrewEdmonds11** [comment]
Done

**Comment by benkrikler** [comment]
This could be very helpful if ticket #193 allows us to keep zoomed out plots with fine binning.
