### ISSUE TITLE
Anyone else having trouble connecting to merlin?

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#199]

**Comment by AndrewEdmonds11** [comment]
Seems like it. (I've just tried and it seems to be hanging)

**Comment by jrquirk** [comment]
An important question is whether one of us broke it.

**Comment by AndrewEdmonds11** [comment]
I haven't logged into Merlin in a while so it wasn't me. Honest.

**Comment by jrquirk** [comment]
No matter what we should present a united front if questioned on the issue.

**Comment by ajidaniel** [comment]
I just checked and it seems I also can't log on to merlin (though balrog seems OK)

**Comment by benkrikler** [comment]
Is anyone else have troubles again?   I'm getting a timeout error each time I try to ssh into merlin.

**Comment by AndrewEdmonds11** [comment]
I think there was an e-mail saying that it is down for maintenance today. But it could be next Friday.

EDIT: Just checked - it's today

**Comment by benkrikler** [comment]
Oh yeah, I just found it.  That's a nuisance, i didn't push my work...

**Comment by AndrewEdmonds11** [comment]
I guess not many people work on it anymore but is anyone having a problem with submitting jobs to Merlin? Mine just seem to get stuck in the "Submitted" state and never run...

**Comment by jrquirk** [comment]
Mine are sitting there for a bit, but one has been submitted since you posted.

**Comment by AndrewEdmonds11** [comment]
Ok, I'll leave mine there overnight and hopefully they'll be done in the morning.
