### ISSUE TITLE
ODB Loading needs to be standardized

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#2]
Right now ODBs are loaded during alcapana production in alphabetical order from analyzer/odb/ and then from the run#####.odb if it exists or the mid file if it doesn't.

The loading should be done something like Default->Run ODB->Corrected ODB, and never from the file since the file is necessarily the last in the list

**Comment by AndrewEdmonds11** [comment]
Did we eventually decide how we were going to deal with corrected ODB values at FNAL?

From what I recall, our options were: 
- the above
- modifying the run ODB file itself
- something else?

There was also the issue of the rootana correction files. Did we decide we were not going to use them in the end? In which case, how are we going to deal with occasions where we find we need to add a correction during rootana production? Just re-run alcapana?

**Comment by benkrikler** [comment]
I hope Phill (@litchfld) has seen this..

The thing I remember most vividly was deciding that we need this to be rigidly defined.  
I think in the end, we said we would remove the wiremap correction files and put in odb corrections before alcapana.  If rootana tells us the odb was wrong we go back and change the odb then re-run alcapana.   I have already removed the lookup of the wiremap_corrections files from rootana which is sitting on the develop branch now.

As a result of this, I think we said that for each run we would have an odb file which we would edit.  These would mostly come by copying the online odb files but we'd add in the missing fields or replace incorrect values as needed.  The key point was that there would only be 1 file for each run and this and only this would be the source of all odb information when we run alcapana.  That way there's no difficulty in knowing where the information in the odb (and TSetupData) used in the final analysis came from.

That's what I remember us agreeing at least.  Does it sound right?  Actually, I thought that was the main motivation for the alcapana production runs that are going on..

**Comment by jrquirk** [comment]
As I remember we never settled. What I said above is what worked for MuSun and what appeals to me. If we're worried about what value were used, we can always dump the ODB again after a file has been processed, though I don't think that's necessary.

In the scheme above (Default->Run->Corrections) we can always work backwards to find what was going on.

Having just one ODB file per run (instead of three) does have a lot of strengths. The biggest weakness is that someone has to do the work. And this seems a much bigger job than just outputting a corrections file.

**Comment by litchfld** [comment]
I would argue that if we have to dump the file in odb format for record keeping, someone has already done most of the work?  And any other kind of record is even more work...

Actually I don't have so much concern about a default file that is overriden by the run file.  It's clear in that case there would always be two files involved.  It's issue of knowing whether or not a correction file was used (e.g. if someone fat-fingers the command line and it isn't picked up) that is the scary part.

**Comment by litchfld** [comment]
I guess one approach that protects against most of my concerns is to have additional fields in the run and correction files.  The run odb file would have:

run_odb_file_seen = [run_number]

And in the correction file:
correction_odb_file_seen = [run_number]
correction_odb_file_version = [version_string]

The existence of all three fields is checked, and the two run-numbers is compared. The correction version is then passed to the output.  Then the only problem is if someone forgets to change the version string when changing a correction, or makes a version that they forget to store, which are less common problems. (Fat-fingering has a very insidious relative: mount points that aren't visible on some subset of compute nodes).

This does require all runs have a minimal correction file containing that information.

**Comment by AndrewEdmonds11** [comment]
So, in today's discussion we also talked about using an SQL database for this. However, it was decided for the time being that we stick with what we're doing and go with option no.2 from elog:84 but reading in the dumped ODB.

John, do you still need the alcapana modules to not use things like the pedestal? Open an issue if it does. It will require us to re-run alcapana an extra time but we should have time for that and will also mean we can get better trend plots for data quality investigation.

**Comment by jrquirk** [comment]
It'll be okay for now. In the future I like the idea, however. Around the same time we switch to the SQL thing if we ever do.
