### ISSUE TITLE
Better Colour Palette

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#20]
We want a better colour palette for the z-axis, so that there is better contrast in the mid range. Phill says he has one and will distribute it

**Comment by AndrewEdmonds11** [comment]
Fixed. Currently set to palette number 3 but please test for yourself.

Before:
![hdq_musctdiff_sil2-s_na80_trendplot](https://cloud.githubusercontent.com/assets/1848575/3077062/7812c9a4-e410-11e3-8962-e3942f4d59a1.png)

After:
![hdq_musctdiff_sil2-s_na80_trendplot](https://cloud.githubusercontent.com/assets/1848575/3077064/8305d702-e410-11e3-81b5-b11a1a557f33.png)

**Comment by litchfld** [comment]
Hi Andy, would be better to bump the number of colour stops up a bit too; 20 is needlessly low in this day and age. 200 (255?) is perfectly fine, as long as you don't redeclare the palette for every event.

**Comment by litchfld** [comment]
PS i'm not sure, but I think I prefer the palette 1 myself.

**Comment by AndrewEdmonds11** [comment]
Which part of the macro do I need to change? The "stops" are arrays of 5 doubles, do I need to increase the size of the array?

**Comment by litchfld** [comment]
Sorry, its in a different place: 
gStyle->SetNumberContours(N_contours);

and a bit of experimentation shows I can't differentiate between more than 100 colour contours, so 255 is probably overkill.

**Comment by AndrewEdmonds11** [comment]
I think it's already set to 255 since that's the default value in the argument list and I don't ask for anything less :)

```
void SetUserPalette(Int_t palette = 0, Int_t nCont=255, Float_t alpha =1){
  switch (palette) {
  case 1: 
    // Rainbow palette
    TColor::InitializeColors();
    const Int_t NRGBs = 5;
    Double_t stops[NRGBs] = { 0.00, 0.34, 0.61, 0.84, 1.00 };
    Double_t red[NRGBs]   = { 0.00, 0.00, 0.87, 1.00, 0.51 };
    Double_t green[NRGBs] = { 0.00, 0.81, 1.00, 0.20, 0.00 };
    Double_t blue[NRGBs]  = { 0.51, 1.00, 0.12, 0.00, 0.00 };
    TColor::CreateGradientColorTable(NRGBs, stops, red, green, blue, nCont, alpha);
    gStyle->SetNumberContours(nCont);
    break;
```

**Comment by litchfld** [comment]
hm... do you do this before drawing the histograms?  The sublety I had forgotten before is that nCont is the number of contours in the gradient table, and the second 'NCont' was the number of _histogram_ contours in gStyle, which is copied by the histogram when it initailises. So if you do this after making the histogram it doesn't take.

**Comment by AndrewEdmonds11** [comment]
I don't understand the difference between those two. Is the gradient table the colours on the z-axis? And what are the histogram contours?

Either way, this function is called in LoadPicBookMacros.C before I run the picture book macros, which draw the histograms.

**Comment by litchfld** [comment]
Probably can just move on, but here's the details.

When you create the gradient table, it is just appended to the global colour table (which is just a long indexed container of colours). The stops and rgb values define the colour curve from on end of the gradient to the other, and the nCont in the function call says how finely to sample this notional gradient graph, and therefore how to many colours to append.

The 'NCont' passed to gStyle is how many contours histograms use when drawing themselves... they don't necessarily have to be colours at all, some of the Draw("cont") versions use dotted lines.  It also happens to be used for the z axis in "colz" plots. 

So to take an extreme example you can have a greyscale palette with 2 stops (white, black) that defines 101 colours (shades of grey) starting from colour N in the global table, and then set gStyle so histograms use just 3 of them N, N+50, N+100.  Eye-watering, isn't it?
