### ISSUE TITLE
IDs::source "any" and == operator not working?

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#201]
Quick question: Am I misusing the `==` operator when matching sources with "any" as a generator/config?

Longer explanation:
I'm trying to write the TDP plotter that plots the time difference between pulses in two sources. In the config file I want it so that you can just specify a channel (e.g. muSc or Ge) and not necessarily the generator or config.

Here's how I create the two sources:

``` C++
  IDs::channel channel_a = IDs::channel(opts->GetString("det_a"));
  IDs::channel channel_b = IDs::channel(opts->GetString("det_b"));
  IDs::generator generator_a = IDs::generator(opts->GetString("gen_a", "any"), opts->GetString("config_a", "any"));
  IDs::generator generator_b = IDs::generator(opts->GetString("gen_b", "any"), opts->GetString("config_a", "any"));

  fSourceA = IDs::source(channel_a, generator_a);
  fSourceB = IDs::source(channel_b, generator_b);
```

and the config file I have:

``` cfg
## Plot TDPs
PlotTDPs
PlotTDP_TDiff( muSc, Ge )
```

However, when I loop through the DetectorPulseMap to try and find the correct DetectorPulseLists, they don't match because I have the strings `any` for both the generator and config in the sources and not the actual generators and configs (i.e. `muSc#PassThrough#{alias=detector_pulses}{time_difference=1} != muSc#any#any`).

Here's how I loop through the TDP sources.

``` C++
  // Loop over all TDP sources
  for(SourceDetPulseMap::const_iterator i_source=gDetectorPulseMap.begin();
      i_source!= gDetectorPulseMap.end(); ++i_source){

    std::cout << i_source->first << ", " << fSourceA << std::endl;
    if (i_source->first == fSourceA) {
      fDetPulsesA = i_source->second;
      if (Debug()) {
        std::cout << "PlotTDP_TDiff: " << fSourceA << " pulses found. (" << fDetPulsesA.size() << " pulses)" << std::endl;;
      }
    }
    else if (i_source->first == fSourceB) {
      fDetPulsesB = i_source->second;
      if (Debug()) {
        std::cout << "PlotTDP_TDiff: " << fSourceB << " pulses found. (" << fDetPulsesB.size() << " pulses)" << std::endl;
      }
    }
  }
```

So what's the correct way to implement this?

**Comment by benkrikler** [comment]
This isn't a bug.  The `operator==` checks for exact equality so both IDs would need to contain the 'any' part.  Use the `matches` method instead which respects the wildcard part.  The commenting for `IDs::source` isn't very good, but for `IDs::channel` this is explained properly I think.

**Comment by AndrewEdmonds11** [comment]
Cool. I thought it might be intentional. Thanks.
