### ISSUE TITLE
Changes to PlotTDiff

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#204]
Specifically to @benkrikler and @dmalexan. I made some not-so-backward compatible changes to the code. The first is that I got rid of the default-value checking when filling since the 2D histograms will fill the underflow bins. As of now if a generator fills a default value for one TAP, it fills it for all TAPs, so we just get empty 2D hists whenever we get a 1D one. I also got rid of the 1D tdiff hist which must now be recovered from the x projection. And finally there are three module-file arguments that can be passed now, the low and high dT values for the histograms and a flag to do calculations for the calibration database which is now done in the After-Last function.

**Comment by benkrikler** [comment]
Sounds good to me.  Thanks for the heads up.

>  the low and high dT values

That's the x-axis limits right?

One other thing that might be nice to add is to fit the 1D projection to the X-axis and get the TDiff peak width (with some low-amplitude cut perhaps).  Of course, we can do this in the picture book later, but there's no harm of doing it now I think.

**Comment by jrquirk** [comment]
Those are the x-axis limits.
