### ISSUE TITLE
TAPAlgorithms has parameter values set in constructor

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#206]
It was mentioned in the meeting today that the TAPAlgorithms structures have parameters that may be used uninitialised which could result in problems.

I think the idea is to create the TAPAlgorithm instances with the parameter values in their constructors.

**Comment by benkrikler** [comment]
If we're not going to change the parameters controlling an algorithm during a run then we should make the actual fields const.  They would only be assignable in the constructor then and we can be confident they're not being changed accidentally which would be very hard to identify.

**Comment by jrquirk** [comment]
> we should make the actual fields const

This makes sense. I made both the fields in the algorithms const and the algorithm objects themselves in the generators. Andy has finished this, so I'm going to close this issue like a bank is closed on Summer Bank Holiday.

**Comment by AndrewEdmonds11** [comment]
Were they not const already? I must have ballsed up one of my many rebases...

**Comment by benkrikler** [comment]
They seemed const on my pile-up branch.  This is a bit restrictive though; I've had to change it for one of the things I'm trying out.  For those fields we don't make const, proper accessor methods (getters/setters) should be used, so we don't set a field instead of getting it...
