### ISSUE TITLE
ConstantFractionTime Algorithm should take a parameter for the fraction that is used (via the generator)

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#207]
We want to be able to set a fraction in the modules files, that gets passed to the ConstantFractionTime algorithm. I think this will be somewhat related to issue #206.

**Comment by jrquirk** [comment]
You mean the constructor, since it already is a field in the struct?

**Comment by AndrewEdmonds11** [comment]
Probably
