### ISSUE TITLE
Move to using SetupNavigator::GetTimeShift rather than TSetupData

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#215]
We need to use the new TimeShifts for the SetupNavigator (see issue #212) in any generators where we use them. Most importantly, in FirstCompleteAPGenerator. Maybe we can do this on the release branch before merging into master?

**Comment by jrquirk** [comment]
Okay, I think this is done. Calibration DB is at ~quirk_j/AlcapDAQ/analyzer/rootana/calibration.db. And rootana v4 has been tagged.
