### ISSUE TITLE
The picture book program should be able to handle subfolders

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#222]
At the moment, the picture book program assumes all plots are directly inside the folder produced by each module.

For production, we have several instances of PlotTAP_TDiff, which means a subfolder is created for each instance.

The picture book should be able to handle this or we should rework PlotTAP_TDiff to produce all the plots in one folder (which may be too much work, which is why I titled the issue with the first solution)

**Comment by benkrikler** [comment]
I've used the following macro before to recurse through a root file and produce png plots of all TH{1,2}s.  Is it of any help here?

``` c++
#include "TString.h"
#include "TProfile.h"
#include "TH1F.h"
#include "TH2F.h"
#include "TFile.h"
#include "TDirectory.h"
#include "TStyle.h"
#include "TSystem.h"
#include "TROOT.h"
#include "TCanvas.h"
#include "TKey.h"
#include <iostream>
using std::cout;
using std::endl;

void Save(TString name){
  name=name.ReplaceAll("#","_");
  name=name.ReplaceAll(" ","_");
  gPad->Print(name.Data());
}

void FitProfile(TH1* profile,const char* out_dir, const char* ext){
  profile->Fit("gaus");
  Save(Form("%s/%s.%s",out_dir,profile->GetName(),ext));
}

void Plot1D(TH1* hist,const char* out_dir, const char* ext){
  gPad->SetLogy(1);
  hist->Draw();
  const char* name=hist->GetName();
  Save(Form("%s/%s.%s",out_dir,name,ext));
}

void Plot2D(TH2* hist,const char* out_dir, const char* ext){
  gPad->SetLogy(0);
  gPad->SetLogz(1);
  hist->Draw("colz");
  const char* name=hist->GetName();
  Save(Form("%s/%s.%s",out_dir,name,ext));
  FitProfile(hist->ProjectionX(),out_dir,ext);
  FitProfile(hist->ProjectionY(),out_dir,ext);
}

void recursive_plot(TDirectory* dir,const char* cwd,const char* ext){
  if(!dir) {
    cout<<"Couldn't find directory"<<endl;
    return;
  }
  TList* keys = dir->GetListOfKeys();
  TIter next(keys);
  TObject *obj;
  TKey* key;
  while ((key = (TKey*) next())){
    obj=key->ReadObj();
    //cout<<cwd<<endl;
    if( obj->IsA()==TDirectoryFile::Class()){
      TString new_dir=Form("%s/%s",cwd,obj->GetName());
      cout<<"Putting plots into "<<new_dir<<endl;
      gSystem->mkdir(new_dir.Data(),true);
      recursive_plot((TDirectory*) obj,new_dir.Data(),ext);
    } else if (obj->InheritsFrom(TH2::Class())){
      Plot2D( (TH2*) obj,cwd, ext);
    } else if (obj->InheritsFrom(TH1::Class())){
      Plot1D( (TH1*) obj,cwd, ext);
    } else {
      //cout<<"Skipping object: "<<obj->GetName()<<endl;
    }
  }
}

void make_all_plots(const char* ext, const char* out_dir=".",const char* start_dir="/"){
  gROOT->ProcessLine(".L $DAQdir/analyzer/picture_books/low_level_data_quality/palettes.C");
  gROOT->ProcessLine("SetUserPalette(3)");
  gStyle->SetOptStat(111110);
  TCanvas* c1=new TCanvas("c1");
  gDirectory->pwd();
  gDirectory->cd(start_dir);
  cout<<"start_dir="<<start_dir<<endl;
  TDirectory* dir= gDirectory;
  dir->pwd();
  recursive_plot(dir,out_dir,ext);
}

```

**Comment by AndrewEdmonds11** [comment]
I really like that `obj->InheritsFrom()` function (I was looking for something like that for some reason so will try and find a place to put it) but otherwise I don't think so. The new system is quite different to the old one.

Last time, the plots were produced with a different macro to the one that produced the latex output. Now, they are sort-of done at the same time. The new program is OO and everything!

I think the way to go is to just add another loop if there's a subfolder and a way to add sub-sections. It shouldn't be too bad just need to get plots to test with first (#221) :)

**Comment by benkrikler** [comment]
> I think the way to go is to just add another loop if there's a subfolder and a way to add sub-sections. It shouldn't be too bad just need to get plots to test with first (221) :)

That's exactly what you've got here, only the loop is recursive so it will work to an infitie depth with little extra code. 

You could turn the Plot1D and Plot2D into overloaded members of some class whose implementation changes if you're outputting to latex or pngs with the code you already have.

**Comment by AndrewEdmonds11** [comment]
Ok, I see. You keep calling the `recursive_plot` function.

In which case, I will try something similar. At the moment in the picture book code, the loop is done in `main()` and I guess it's not possible to recursively call main so I'll have to move the loop to another function.

Thanks, Ben.

**Comment by AndrewEdmonds11** [comment]
Ok, after a bit of refactoring the code, commit 884291687fe299045f7c51c39830e715c4d2d39a has the recursive histogram plotting so we can plot histograms in subfolders.
