### ISSUE TITLE
replace `std::map::at`

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#228]
Throughout the SetupNavigator we now used `std::map::at` to obtain values from the channel map, such as getting noise or pedestal values from the DB.  This is good in that if a value doesn't exist we get an exception, and stop running, but the exception is not very informative and we have no control over what exception is actually thrown. 

To improve this, I've added an `alcap::at` method which I've put in `definitions.h` (although it might want to go elsewhere).  So:

```
aMap.at(someKey);
```

becomes

```
alcap::at<ExceptionType>(aMap ,someKey);
```

This is even better if `ExceptionType` is an AlcapException (inherits from `Except::Base`) as you'll get a backtrace along with the exception.

**Comment by benkrikler** [comment]
And this is now merged in on develop so i'm closing this.

I've put it into the SetupNavigator and elsewhere though I've not rigorously replaced every use of `std::map::at` so feel free to replace them when you come across one.

**Comment by AndrewEdmonds11** [comment]
So this can be used with any map or just ones where we have a channel/source?

**Comment by benkrikler** [comment]
It's a fully templated function so should work with any map.  

There are actually three template parameters if you look at the definition but gcc (and I think other compilers) will deduce those automatically from the map object you pass in, so the only template parameter you should specify is the exception one.
