### ISSUE TITLE
Equations

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#233]
If I want to put maths in the issue tracker (or wiki too? I haven't tried that). I have been using this site:
http://www.sciweavers.org/free-online-latex-equation-editor 

You can write the equation in LaTeX there then link it as an image. (Unfortunately GitHub deliberately avoids letting you use MathJax directly.) Take the bare URL ("Twittter/Google Docs") which will look something like:

```
http://www.sciweavers.org/tex2img.php?eq=%5Csin%5Ctheta%20%3D%20%5Cfrac%7BO%7D%7BH%7D&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0
```

Wrap it in parenteses, `()`, and preceed it with a `![tagname]` (the tagname is arbitrary, but the exclamation point is needed to make it inline):

```
![def sin](http://www.sciweavers.org/tex2img.php?eq=%5Csin%5Ctheta%20%3D%20%5Cfrac%7BO%7D%7BH%7D&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0)
```

And after a moments thinking it 'should' - fingers crossed - replace the alt text with the image. 

Unfortunately it doesn't seem to be working so well today.  Anyone have any better methods?

**Comment by jrquirk** [comment]
Download the image and upload it like this

![eqntest](https://cloud.githubusercontent.com/assets/5143258/4360365/4287e89a-427b-11e4-88a5-dbd565463491.jpg)
