### ISSUE TITLE
Rootana crashes on Merlin (bad_alloc)

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#235]
Since Friday about half of my rootana jobs on the cluster had been failing with bad_alloc (I just `cat data/log/*.err` while the jobscripts were running since the logs are deleted a couple of seconds after an error is seen when the run is unclaimed and possibly resubmitted). I was having no problems running rootana on the login node.

This (Monday) morning I was not able to run a full run (specifically 3600) on the login node, or the cluster. The same bad_allocs showed up.

In the meeting today, it was suggested I try running `ulimit -a` in the grid scripts to check if I'm bumping up against any limitations.

As of this afternoon, after implementing this debug message, my jobs are only rarely crashing and there are no imposed memory limitations

```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 191992
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) 86400
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

The CPU time is a limit we put on the scripts ourselves, and the jobs are certainly not hitting this.

Anyway, I used memcheck and found no memory leaks above the like few MB I have for histograms, so this was odd. But If I used massif I found a couple of GBs set aside by root in the `TTree::GetEntry` function called in our main_event_loop. I don't know if this is a problem with a cause on our end. I know things like this have been reported before, and Phil specifically noted ROOT applications bloat in the beginning. But a couple of gigs is a lot. Here's the massif output (graph and peak heap)

```
--------------------------------------------------------------------------------
Command:            ./rootana -i /gpfs/home/alexander_d/data/tree/tree03600.root -o test.root -m configurations/ge.cfg -n 100
Massif arguments:   (none)
ms_print arguments: massif.out.17034
--------------------------------------------------------------------------------


    GB
2.478^                                                                       #
     |                                                             @@@@::::::#
     |                                                           @@@@@@:     #
     |                                                        @@@@@@@@@:     #
     |                                                     @@@@@@@@@@@@:     #
     |                                                   @@@@@@@@@@@@@@:     #
     |                                                @@@@@@@@@@@@@@@@@:     #
     |                                             @@@@@ @@@@@@@@@@@@@@:     #
     |                                          @@@@ @@@ @@@@@@@@@@@@@@:     #
     |                                      @@@@@@@@ @@@ @@@@@@@@@@@@@@:     #
     |                                    @@@@@ @@@@ @@@ @@@@@@@@@@@@@@:     #
     |                                 @@@@@@@@ @@@@ @@@ @@@@@@@@@@@@@@:     #
     |                              @@@@@@@@@@@ @@@@ @@@ @@@@@@@@@@@@@@:     #
     |                            @@@@ @@@@@@@@ @@@@ @@@ @@@@@@@@@@@@@@:     #
     |                        @@:@@@@@ @@@@@@@@ @@@@ @@@ @@@@@@@@@@@@@@:     #
     |                     @::@ :@@@@@ @@@@@@@@ @@@@ @@@ @@@@@@@@@@@@@@:     #
     |                   ::@::@ :@@@@@ @@@@@@@@ @@@@ @@@ @@@@@@@@@@@@@@:     #
     |                 @@::@::@ :@@@@@ @@@@@@@@ @@@@ @@@ @@@@@@@@@@@@@@:     #
     |             ::::@@::@::@ :@@@@@ @@@@@@@@ @@@@ @@@ @@@@@@@@@@@@@@:     #
     |          @@@::: @@::@::@ :@@@@@ @@@@@@@@ @@@@ @@@ @@@@@@@@@@@@@@:     #
   0 +----------------------------------------------------------------------->Gi
     0                                                                   3.728
...
--------------------------------------------------------------------------------
  n        time(i)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
 65  3,595,205,850    2,633,121,912    2,631,661,768     1,460,144            0
 66  3,640,243,037    2,660,526,800    2,658,993,584     1,533,216            0
 67  4,002,810,932    2,660,794,920    2,659,261,656     1,533,264            0
99.94% (2,659,261,656B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->96.24% (2,560,756,096B) 0x510D722: TBuffer::TBuffer(TBuffer::EMode, int) (TBuffer.cxx:72)
| ->96.24% (2,560,756,096B) 0x6018767: TBufferFile::TBufferFile(TBuffer::EMode, int) (TBufferFile.cxx:94)
|   ->96.24% (2,560,692,088B) 0x7959E77: TBasket::TBasket(char const*, char const*, TBranch*) (TBasket.cxx:99)
|   | ->96.24% (2,560,692,088B) 0x79A40B5: TTree::CreateBasket(TBranch*) (TTree.cxx:3383)
|   |   ->96.24% (2,560,692,088B) 0x795C56C: TBranch::GetBasket(int) (TBranch.cxx:1096)
|   |     ->96.24% (2,560,692,088B) 0x795CC94: TBranch::GetEntry(long long, int) (TBranch.cxx:1232)
|   |       ->96.24% (2,560,692,088B) 0x796B964: TBranchElement::GetEntry(long long, int) (TBranchElement.cxx:2321)
|   |         ->96.24% (2,560,692,088B) 0x796B928: TBranchElement::GetEntry(long long, int) (TBranchElement.cxx:2304)
|   |           ->96.24% (2,560,692,088B) 0x79A7FD4: TTree::GetEntry(long long, int) (TTree.cxx:4922)
|   |             ->96.21% (2,560,052,008B) 0x47E41C: EventNavigator::LoadEntry(long long) (EventNavigator.cpp:339)
|   |             | ->95.25% (2,534,400,792B) 0x482066: LoopSequence::Process() const (EventNavigator.h:124)
|   |             | | ->95.25% (2,534,400,792B) 0x482241: LoopSequence::Run() const (LoopSequence.cpp:139)
|   |             | |   ->95.25% (2,534,400,792B) 0x4397B7: Main_event_loop(TTree*, ARGUMENTS&) (main.cpp:193)
|   |             | |     ->95.25% (2,534,400,792B) 0x43A889: main (main.cpp:146)
|   |             | |       
|   |             | ->00.96% (25,651,216B) in 1+ places, all below ms_print's threshold (01.00%)
|   |             | 
|   |             ->00.02% (640,080B) in 1+ places, all below ms_print's threshold (01.00%)
|   |             
|   ->00.00% (64,008B) in 1+ places, all below ms_print's threshold (01.00%)
|   
->02.23% (59,465,408B) in 1663 places, all below massif's threshold (01.00%)
| 
->01.47% (39,040,152B) 0x5147C58: TStorage::ReAllocChar(char*, unsigned long, unsigned long) (TStorage.cxx:276)
  ->01.47% (39,040,152B) in 2 places, all below massif's threshold (01.00%)

```

I've seen it get up to over 3 GB. But it's not a memory leak according to memcheck, so I don't know. My jobs are running now, but as this has come up before and it's annoying when it does I thought I'd post again.

**Edit**: I'm on the GeSpectrum feature branch running configurations/ge.cfg.

**Comment by litchfld** [comment]
@benkrikler forwarded me the documentation for the TTree cache mechanism. It looks familiar, but there are a few things that don't quite fit - the cache is supposed to be O(MB) not GB, .  Might be worth playing around with - we shouldn't need much in the way of fancy preloading schemes since the cluster disk seems to be pretty nearby.

 http://root.cern.ch/root/html/TTreeCache.html

The obvious thing to try would be to set `TTree::SetCacheLearnEntries()` to something smaller than its default.  However despite the documentation saying the default learning phase is 100 entries the code seems to suggest that it is only 10 entries, which would mean it doesn't actually align with what i've seen before (issue #11).  

`TTree::SetCacheSize()` might also be an interesting knob to twiddle, but again it looks like the defaults would not allow this sort of memory growth.

**Comment by litchfld** [comment]
Might be worth using the debug functions to get an event-by-event picture of the memory growth in a successful and non-successful run.  You can output it to the log or make an axillary plot to save to file. http://alcap-org.github.io/doxygen/AlcapDAQ/develop/namespaceDEBUG.html#a60406d2633a01859a75a95fa95943672

**Comment by jrquirk** [comment]
Now I'm trying to run on calibration data and getting over 5 GB on the heap, but TTree::GetCachSize is under 30 MB. I'll try your debug function. To check though, I just stream DEBUG::check_mem().str somewhere?

**Comment by litchfld** [comment]
(That's what I was afraid might happen...)

Yup, or you can use the integer `.res` and `.virt` values in your own output.

**Comment by jrquirk** [comment]
I printed out the above in the EventNavigator::LoadEntry method and the last few lines were

```
Memory usage:    Res/Virt(MiB) =  136 / 9384
Memory usage:    Res/Virt(MiB) =  136 / 9409
Memory usage:    Res/Virt(MiB) =  136 / 9433
Memory usage:    Res/Virt(MiB) =  136 / 9458
Memory usage:    Res/Virt(MiB) =  136 / 9482
Memory usage:    Res/Virt(MiB) =  136 / 9507
Memory usage:    Res/Virt(MiB) =  138 / 9531
Memory usage:    Res/Virt(MiB) =  139 / 9555
Memory usage:    Res/Virt(MiB) =  139 / 9580
Memory usage:    Res/Virt(MiB) =  139 / 9604
Terminating due to unexpected exception:
std::bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

The virtual memory started at a reasonable value and increased at about the same rate you see here before crashing. 9.6 GB is a lot, and since it growing with every event somethings going on.

**Comment by benkrikler** [comment]
Is this with one of the standard config files?  If not, could you test it with a simple one, like one of the calibration ones and see if we still see the same bloat?

**Comment by jrquirk** [comment]
The errors I've been running into today are with the pedestalsandnoise_calib.cfg.

**Comment by jrquirk** [comment]
Except they were with a different run, run 3375. I just ran on run 3600 with the pedestalsandnoise_calib.cfg and got a successful run

```
...
Memory usage:    Res/Virt(MiB) =  486 / 3370
Memory usage:    Res/Virt(MiB) =  486 / 3370
Memory usage:    Res/Virt(MiB) =  486 / 3370
Memory usage:    Res/Virt(MiB) =  486 / 3370
Memory usage:    Res/Virt(MiB) =  486 / 3370
Memory usage:    Res/Virt(MiB) =  486 / 3370
Memory usage:    Res/Virt(MiB) =  111 /  245
Memory usage:    Res/Virt(MiB) =  111 /  245
Memory usage:    Res/Virt(MiB) =  111 /  245
Memory usage:    Res/Virt(MiB) =  111 /  245
Memory usage:    Res/Virt(MiB) =  111 /  245
...
```

So it does eventually shrink down. But the calibration run 3375 might have a lot more hits maybe?

**Comment by litchfld** [comment]
Can you print out the event number (or maybe you just remember) for these two?  The single saw-tooth seems to stablely happen after a fixed number of entries, so if the earlier one is the same thing it should have died early on, before it got that far.

**Comment by jrquirk** [comment]
It was 168 for run 3600, and the bad_alloc was thrown at some point between 350 and 400 for 3375. I was thinking the same thing.

Another note is that while 3375 crashes with a 9.6 GB footprint when the raw data tree "learning" entries is set to 100 (the default I guess? or set somewhere in the code I haven't seen), if I set it to 10 it crashes with a 11-12 GB footprint.

**Comment by litchfld** [comment]
Hmm... it kinda looks like a simple memory leak, but you said valgrind/memcheck didn't report anything? Odd.

One thing that might(?) be worth doing is looking at the memory growth. Some of ROOT's caching mechanisms create staircase-like memory growth whereas dumb memory leaks are more likely to be linear. It looks linear at ~25MiB/event for the range you posted, and 9600/25 ~ 390 events, which fits, but if your suck for ideas you might try verifying that and/or start from part-way through a file.  I'll try looking at the code but it's all action on COMET right now, so doubt I can spend much time on it.

**Comment by jrquirk** [comment]
I ran on my own machine and included the following line in `EventNavigator::LoadEntry`

```
std::cout << DEBUG::check_mem().str << "(" << entry << ")" << std::endl;
```

And I saw the familiar behavior much later

```
Res/Virt(MiB) =  309 / 28569(2952)
Res/Virt(MiB) =  309 / 28569(2953)
Res/Virt(MiB) =  309 / 28569(2954)
Res/Virt(MiB) =  309 / 28569(2955)
Res/Virt(MiB) =  309 / 28569(2956)
Res/Virt(MiB) =  309 / 28569(2957)
Res/Virt(MiB) =  309 / 28569(2958)
Res/Virt(MiB) =  309 / 28569(2959)
Res/Virt(MiB) =  109 /  219(2960)
Res/Virt(MiB) =  109 /  219(2961)
Res/Virt(MiB) =  109 /  219(2962)
Res/Virt(MiB) =  109 /  219(2963)
Res/Virt(MiB) =  109 /  219(2964)
Res/Virt(MiB) =  109 /  219(2965)
```

So instead of entry 168, the memory reduction happens at event 2959. But it blows up to 28.6 GB before this happens (and it's quite steady before this). So I don't know. I've tried a number of the TTree cache-restricting methods. But I don't know if this is even a TTreeCache problem and not some other aspect of ROOT. I expect this problem to continue coming up, and certainly for at least the calibration run 3375 we can't run on Merlin.

**Comment by jrquirk** [comment]
Since this problem has a work-around (run on a different machine) and it seems to be with ROOT and not us, this is being closed.

Two other work-arounds were suggested but not tested (though there's no reason to expect they wouldn't work).
1. Split the file up (since the crash happens after > 300 MIDAS events, we could break it up into 200 event files) so that the crash-point wouldn't be reached
2. When invoking rootana, specify a small range of events to run.
