### ISSUE TITLE
muPC data delivery

### ISSUE THREAD

**Issue by joegrange** [alcap-org/AlcapDAQ#237]
Hi folks,

In poking around the muPC I'm ready to unpack and deliver it to alcapana --> rootana and I'm hoping for feedback from the analyzers on the preferred form.  The following three objects are created and I think it'd be good to deliver them all into alcapana in whatever container we go with:
- bare wire hits in x plane: for each hit we get two objects, the wire number and the timestamp
- same as above but for the y plane
- time-correlated (+-95ns) pairs of x wire hit and y wire hit with some other cuts to remove bad hits: here we get the x wire number, the y wire number and the timestamp

So thinking about this structure, forming TPulseIslands would seem to be a misuse of the class that could make analysis obnoxious, but I'm curious to hear what you think.  As you know, a TPI is a collection of timestamp, sample vector, and string for detector name.  To uniquely identify which wire was hit with a string, for the first and second items above we'd have 24 different "detector names" each (maybe "muPC_x_[0-23]" etc - or maybe they're more properly bank names, not detector names...), and for the third we'd have 24 x 24(!) for each x-y combination.  The sample vector would just be a single "hit" bin state along with its timestamp. 

And to confirm, these hits are a simple binary state where a wire signal has passed some threshold so we've no additional handle on signal height/intensity.

So for sure TPIs aren't optimal for muPC.  I'd guess it'd be better to make a new container that just delivers the bank name, wire number(s) and the timestamp for each hit.  But then there's a trade-off here as well of course of having to deal with a container unique to muPC.  

Thoughts?

**Comment by AndrewEdmonds11** [comment]
Nice work, Joe!

Yes, I see that we probably shouldn't use TPIs for this and need a new container. I think (someone corrrect me if I'm wrong) but the only real place that we will be using this is in the `TMuonEvent::HasMuonHit()` function so I don't think it would be too bad having a unique container for it.

One other question, is there any point in having the raw hits? If we're removing "bad" hits (where I'm thinking "bad" is some problem with the electronics rather than it not being a muon or something), then would we ever want to look at them?

**Comment by jrquirk** [comment]
The name, wire, and timestamp are in line with what we've been doing (taking the raw data to a simple C++ object), so that sounds like a good idea.

We may also use the info to get distributions to put in the simulation,

What cuts other than time are used to clean up the hits?

**Comment by joegrange** [comment]
Right, I wouldn't guess "bad" hits are so helpful, where bad is just defined as a lone (outside of +-95 ns window) hit in an x- or y- wire.  I didn't find the wire spacing so am not sure how common it might be for a muon to only trigger a single wire but probably the majority of single-hits are just noise.  

Okay, so I'll look into getting a simple x/y wire + timestamp container set up.

**Comment by joegrange** [comment]
(Though folks are still welcome to comment on alternative preferences)

**Comment by joegrange** [comment]
Got it!  For future ref, one has to register the new class in [DataLibraryClasses.list](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/src/common/DataLibraryClasses.list) and [DataLibraryLinkDef.h](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/src/common/DataLibraryLinkDef.h).

**Comment by joegrange** [comment]
BTW here's a look at the muPC data:
![c1](https://cloud.githubusercontent.com/assets/5612602/4704618/718ba6f0-5873-11e4-9858-b120a00a01e1.png)

X-wires 16-18 look funny at low and high Y, and I think we talked about this some during the run.

**Comment by AndrewEdmonds11** [comment]
Thanks, Joe. Has this been merged onto develop yet?

Also, why does the plot look so different now? Were we ignoring those wires before or something?

**Comment by jrquirk** [comment]
I think it was because we cleaned it up with coincidence with muSc, and the hot wires disappeared.

**Comment by joegrange** [comment]
I haven't pushed it yet because I wanted to test the alcapana output first (the above is just a diagnostic histogram added to the DQ plots).  I'm just looking how I can retrieve this now.  Once I've filled various instances of TMuPCCluster's, how can I access them in the tree file?

And good memory John - see [this elog](https://muon.npl.washington.edu/elog/mu2e/RunPSI2013/250).  So in the analysis we should also correlate this with muSc activity.
