### ISSUE TITLE
Picture Books: Add stats box with the number of entries

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#24]
I'll add a stats box with the number of entries in to make sure that we are seeing the same number of entries in all our plots.

**Comment by benkrikler** [comment]
If it's a problem that it will hide some of the plot, could you locate it just above the main plot?

**Comment by AndrewEdmonds11** [comment]
Oops, thought I'd already commited this. 

No, it's fine. When we just have the number of entries in the stats box it fits nicely above the colour axis :)
