### ISSUE TITLE
Forgot to do pull request and just merged

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#242]
I accidentally merged instead of doing a pull request, so I'm just going to push it since the only common code changed was the SetupNavigator which now requires an Energy table in the calibration database, of which there is a copy of at merlin:~quirk_j/AlcapDAQ/analyzer/rootana/calibration.db.

You will need an an Energy table with at least the run, channel, gain, and offset columns and at least a single entry. The reason for this is to follow the form of how we treat the other tables to have consistent code, not really because anyone needs to be using the energy calibration anytime soon.

You can also just make a table with these columns and a random entry.

```
$ sqlite3 calibration.db
sqlite> CREATE TABLE Energy(run INT, channel TEXT, 'gain' REAL, 'gain_err' REAL, 'offset' REAL, 'offset_err' REAL, 'chi2' REAL, 'ndf' REAL);
sqlite> INSERT INTO Energy VALUES (3779, 'Ge-S', 0.122246, 6.1085e-06, 0.308841, 0.0356455, 1.4031, 6.0);
```

Post issues here.

**Comment by AndrewEdmonds11** [comment]
Is there a module, similar to the pedestal and time offset one, to generate the calibration entries for the Ge yet?

**Comment by jrquirk** [comment]
Unfortunately not, it's less simple. The wiki will be updated with the process soon. Also, right now it only works on datasets where the two Ge channels were plugged into the UH because of how easy it is to pair up pulses. So the SiR dataset is not calibrated.
