### ISSUE TITLE
Linking new classes to alcapana

### ISSUE THREAD

**Issue by joegrange** [alcap-org/AlcapDAQ#244]
Hi much more talented C++'ers,

I'm working on a simple TMuPCCluster class that delivers a timestamp + x wire + y wire of muPC correlated hits defined in this funny Muon Query Language:

https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/src/muSC_muPC/MMuPC1AnalysisMQL.MQL

Anyway, I ported the TPulseIsland example to do what I want it to, but I get an error saying my constructor is not defined.  This sounds like a linking problem to me.   In alcapana, might anyone know where I might need to "register" new classes so they're usable?  I looked around the Makefile, DataLibraryDict and some other likely places to no luck.  

Thanks for any thoughts!
Joe

**Comment by joegrange** [comment]
@benkrikler , @litchfld maybe?

**Comment by litchfld** [comment]
Seems optimistic to think i can help.  I'm not familiar with this MQL, or (TBH) the esoteric usage of C in MIDAS.  But i can try...  Can you post the error message? Also i don't see the TMuPCCluster class on GitHub?

**Comment by joegrange** [comment]
Thanks for offering to take a look.  This doesn't have anything to do with MQL - I'm just trying to repackage some data that I can access just fine into a new class.  The error is:

/gpfs/home/grange_j/AlcapDAQ/analyzer/work/grange_j/../../src/muSC_muPC/MMuPC_Repackage.cpp:121: undefined reference to `TMuPCCluster::TMuPCCluster(double, double, double)'
collect2: ld returned 1 exit status
make: **\* [alcapana] Error 1

And certainly there exists a constructor that accepts 3 doubles as indicated.  TMuPCCluster is what I'm trying to integrate and fully test before pushing to github.  I could upload it on a separate branch.

**Comment by jrquirk** [comment]
Publishing the branch is a good idea. Then people can poke around when they get a chance.

**Comment by litchfld** [comment]
Yeah, without seeing what you have it's difficult to guess...  

Only thing i can think of: have you updated `files.make` appropriately?

**Comment by jrquirk** [comment]
The solution is posted in #237.

**Comment by joegrange** [comment]
(thanks John)
