### ISSUE TITLE
Jobscript error

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#247]
I've just tried to do a run with the jobscript and got back an error which I'm not sure how to proceed with.

My command was:

```
$DAQdir/analyzer/batch/jobscripts/run_production.py --production=rootana --new=mu_stop --version=3 --modules=$DAQdir/analyzer/rootana/configurations/production.cfg --database=/gpfs/home/krikler_b/data/production.db --dataset=SiR2
```

And the full output is:

```
INFO: Starting new production, version 25
Claimed run: 2091
Claimed run: 2092
Claimed run: 2093
Claimed run: 2094
Claimed run: 2095
Claimed run: 2096
Claimed run: 2097
Claimed run: 2098
Claimed run: 2099
Claimed run: 2100
Submitting run:2091
ERROR: There was an uncaught exception. Aborting...
Aborting runs: [2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100]
Traceback (most recent call last):
  File "/gpfs/home/krikler_b/AlcapDAQ/analyzer/batch/jobscripts/run_production.py", line 217, in <module>
    sub = runman.SubmitOne()
  File "/gpfs/home/krikler_b/AlcapDAQ/analyzer/batch/jobscripts/RunManager.py", line 155, in SubmitOne
    job = mu.submit_job(run, self.prod, infile, self.mods, self.calib)
  File "/gpfs/home/krikler_b/AlcapDAQ/analyzer/batch/jobscripts/merlin_utils.py", line 141, in submit_job
    con = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

Any ideas what I should try? 

I'm using my old production.db file.  Should I start from a fresh one maybe?  How do I set that up again?

**Comment by jrquirk** [comment]
If you put a `print cmd` statement before line merlin_utils.py:141, you'll see one of the elements of the list `cmd` is `None` instead of a string. and I think that's going to be `infile` (I've run into a similar problem before).

`infile` is initialized to `None`, but there's never a sanity check later on, which is why I think this is the variable not being set.

Could you point me to your DB file?

**Comment by benkrikler** [comment]
My DB file is in ~krikler_b/data.

Indeed you're right I do have `None` in there:

```
['qsub', '-v', 'DAQdir=/gpfs/home/krikler_b/AlcapDAQ', '-e', '/gpfs/home/krikler_b/data/log/rootana.run02091.err', '-o', '/gpfs/home/krikler_b/data/log/rootana.run02091.out', '-N', 'rootana', '/gpfs/home/krikler_b/AlcapDAQ/analyzer/batch/scripts/batch_rootana.sge', None, '/gpfs/home/krikler_b/data/out/out02091.root', '/gpfs/home/krikler_b/AlcapDAQ/analyzer/rootana/configurations/production.cfg']
```

Is this related to moving files from Andy's area to yours?  Maybe I need to refresh the production.db to reflect this?  I don't remember, but I think I copied yours over a while ago...

**Comment by jrquirk** [comment]
Tree files Andy had created were recently moved over to my space so he'd have more breathing room for the MC. You can change your database with

```
sqlite> UPDATE alcapana_v3 SET tree=replace(tree, 'edmonds_a', 'quirk_j') WHERE tree LIKE '%/edmonds_a/%';
```

Or copy over the new one at ~quirk_j/data/production.db.

**Comment by benkrikler** [comment]
I took the lazier option and copied over your DB.  Everything's working now (if a little slowly, only 1 job seems to be running at a time, though I guess that's the batch system being clogged up..) so thanks for your help!
