### ISSUE TITLE
TDPs and Unparied Pulses

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#249]
Is there an easy way (or a module already written) that can look at the TAPs that don't get paired into TDPs?

**Comment by benkrikler** [comment]
Just loop over the TDPs in gDetectorPulses for a given channel and check the `IsPairedPulse` flag returns false.  Also relavant is the `CouldBePaired` which will be true if the generator used to pair things was anything but the `PassThrough` generator (which is actually unable to pair fast and slow channels).

If you want to check a specific fast or slow channel then use the `GetTAP` method on the TDP.  If it returns NULL there was no pulse paired, for that channel.  It takes a `TDetectorPulse::ParentChannel_t` enum as an argument, so to get the fast TAP in a TDP do:

```
a_tdp->GetTAP(TDetectorPulse::kFast);
```

and use `TDetectorPulse::kSlow` for the slow TAPs.

Also, there is already a module that will plot this sort of thing, but it does a lot more as well so may be too much output for you.  It's the `CheckTDPs` module which will produce plots for all paired detectors that show the relative amplitudes, timings and efficiencies.

**Comment by AndrewEdmonds11** [comment]
Thanks, Ben. Whereabouts is the CheckTDPs module? I can see PlotTDPs and CheckTMEs but not that one.

**Comment by benkrikler** [comment]
My mistake, it's just `PlotTDPs` that you want.

**Comment by AndrewEdmonds11** [comment]
Ok, thanks. Closing....
