### ISSUE TITLE
Amplitude Trend Plot Underflows

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#25]
Because the IslandAmplitude plots are with the pedestal subtracted, there could be entries in the underflow bin.

At the moment, the underflow and overflow bins are not copied to the trend plots. Our options are:
- copy the underflow and overflow bins as well
- extend the range of the IslandAmplitude plots in the negative direction
- don't have pedestal subtraction in these plots (would this also allow us to see how stable the pedestal is?)

What do people think?

**Comment by thnam** [comment]
I prefer no subtraction, then we don't have to think how much to extend to the negative side.

**Comment by AndrewEdmonds11** [comment]
Yes, I would agree. If other people think the same, then the way to implement this is to use TPulseIsland::GetPeakSample() which returns the _position_ in the samples vector of the peak sample and then put that value in the plot.

**Comment by AndrewEdmonds11** [comment]
This has now been solved. Two things to note:
- the shape of this plot for positive and negative polarity pulses are now different (one tails off to the right, the other tails off to the left)
- I still didn't see any entries on SiR1-sum-F of Al100 run 2808....
