### ISSUE TITLE
Possible Merlin Jobscript Bug (Submitting same job twice)

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#250]
So I think I've found a minor jobscript bug.

When a run has an error, I can see on the display that the same run gets submitted twice afterwards. For the time being this is not a problem (one output will overwrite the other) but it should be solved in the future.

**Comment by jrquirk** [comment]
The job is listed twice with the `--display` option (or more, I've had runs listed 10+ times), however as far as I can tell the submission only happens once (checked with qstat). Is this consistent with what you've seen?

**Comment by AndrewEdmonds11** [comment]
Ok, that's fine. I was just making sure that we weren't submitting jobs twice and so gradually destroying our priority
