### ISSUE TITLE
Constant fraction issues

### ISSUE THREAD

**Issue by dmalexan** [alcap-org/AlcapDAQ#252]
Working with the old framework, so most of the mechanics are included in just TAnalysePulse and my PSD algorithm, so things are a little cluttered.

I am using the same cf timing algorithm as the the newer framework.  The timing seems alright when comparing two TAnalysedPulses, the issue starts when I compare the TAP muSc time to the discriminator NDet/NDet2 time (again, same algorithm, so it is likely an issue with the cuts).  I'm posting a slightly trimmed down version of the codes below, if you need the full length, let me know.

TAnalysePulse (cf timing portion) :

``` C++
void AnalysePulseIsland::GetAllParameters_MBCFT(TSetupData* gSetup, const TPulseIsland* pulse,
                         double& amplitude, double& time, double& integral, double& energy) {

  float constant_fraction = 0.50;
  std::string bankname = pulse->GetBankName();
  double pedestal = gSetup->GetPedestal(bankname);
  int trigger_polarity = gSetup->GetTriggerPolarity(bankname);
  double eCalib_slope = gSetup->GetADCSlopeCalib(bankname);
  double eCalib_offset = gSetup->GetADCOffsetCalib(bankname);
  double clock_tick_in_ns = gSetup->GetClockTick(bankname);
  double time_shift = gSetup->GetTimeShift(bankname);

  std::string detname = gSetup->GetDetectorName(bankname);
  if(detname == "NDet")
    time_shift += 192;
  if(detname == "NDet2")
    time_shift += 34;


  // First find the position of the peak
  const std::vector<int>& samps = pulse->GetSamples();
  const std::vector<int>::const_iterator b = samps.begin(), e = samps.end();

  std::vector<int>::const_iterator m = trigger_polarity > 0 ? std::max_element(b, e) : std::min_element(b, e);
  const int amp = *m;
  const unsigned int cf = trigger_polarity > 0 ?
      (unsigned int)(constant_fraction*(double)(amp-pedestal)) + pedestal :
      (unsigned int)((double)(pedestal-amp)*(1.-constant_fraction) + amp);
  while (m != b && (trigger_polarity > 0 ? *--m > (int)cf : *--m < (int)cf));
  double dx = (double)(m-b);
  if (*(m+1) != *m)
    dx += (double)((int)cf - *m)/(double)(*(m+1) - *m);


  // Now assign the parameters
  amplitude = amp;
  time = (dx + (double)pulse->GetTimeStamp()) * clock_tick_in_ns - time_shift;
  integral = 0;
  energy = eCalib_slope * amplitude + eCalib_offset;
}
```

NGammaDiscrimination with timing cut:

``` C++
 //  Analyze the waves


    std::vector<TPulseIsland*> pulses = mapIter->second;

    if(pulses.size() == 0)
      continue;          // skip if no pulse


    for(std::vector<TPulseIsland*>::iterator pIter = pulses.begin(); pIter != pulses.end(); pIter++)
    {
      std::vector<int> samples = (*pIter)->GetSamples();


      float sum = 0, pedestal = 0, peak = 0, energy = 0, tpeak = 0;
      int count = 10;
      float timeB = 0, timeA = 0;
      bool coincidence = false;
      double fullInt = 0, tailInt = 0;
      double ratio = 0;  
      int pileup = 15000; //in ns


      float constant_fraction = 0.50;
      int trigger_polarity = gSetup->GetTriggerPolarity(bankname);
      double clock_tick_in_ns = gSetup->GetClockTick(bankname);
      double time_shift = gSetup->GetTimeShift(bankname);


      //corrections to time shifts
      if(detname == "NDet")
    time_shift += 192;
      if(detname == "NDet2")
    time_shift += 34;



      for(std::vector<int>::iterator sampIt = samples.begin(); sampIt != samples.begin() + count; sampIt++)
    sum += (*sampIt);

      pedestal = sum / count;




      const std::vector<int>::const_iterator b = samples.begin(), e = samples.end();

      //std::vector<int>::const_iterator m = trigger_polarity > 0 ? std::max_element(b, e) : std::min_element(b, e); // find peak position

      std::vector<int>::const_iterator m = std::max_element(b, e);

      peak = *m - pedestal;
      tpeak = m-b;

      if(peak > 5000)
    {
      continue; // overflow cut
    }


      //Fill values for our integrals

      for(std::vector<int>::const_iterator samp = m-3; samp != m+20; samp++){
    fullInt += *(samp) - pedestal;
    if(samp >= m+5){
      tailInt += *(samp) - pedestal;
    }
      }


      ratio = tailInt / fullInt;


      //Scale to MeV
      if(detname == "NDet")
    energy = (peak+15.2)/177.2;
      if(detname == "NDet2")
    energy = (peak+15)/269.1;



      //search for constant_fraction time
      const unsigned int cf = (constant_fraction*(double)(peak-pedestal)) + pedestal;

      while(m != b && (*--m > (int)cf));
      double dx = (double)(m-b); // determine how many clock ticks we are in
      if(*(m+1) != *m)
    dx += (double)((int)cf - *m)/(double)(*(m+1) - *m);;
         //calculate shift to actual cf, linear interpolation
         //replace with spline interpolation time permitting (to get lower cf)

    //get cf time
      timeB = (dx + (*pIter)->GetTimeStamp()) * clock_tick_in_ns - time_shift;
      //timeB = (tpeak + (*pIter)->GetTimeStamp()) * clock_tick_in_ns - time_shift;

      // search for timing coincidence

      for(std::vector<TAnalysedPulse*>::iterator pIterA = currentDetAPulse; pIterA != detAPulses.end(); ++pIterA)
    {

      timeA = (*pIterA)->GetTime();

      if(timeA > timeB + fstopwindow)
        {
          coincidence = false;
          currentDetAPulse = --pIterA;
          break;  //we passed the time window, no coincidence found
        }


      if(pIterA != detAPulses.begin()){
        if(timeA - (*(pIterA - 1))->GetTime() < pileup){ 
          continue; //pre-pulse pileup protection (skip pulse)
        }
      }
      if(pIterA+1 != detAPulses.end()){
        if( (*(pIterA + 1))->GetTime() - timeA < pileup){
          continue; //post-pulse pileup protection (skip pulse)
        }
      }


          double t_diff = timeB - timeA;

      if((t_diff > fStartWindow) && (t_diff < fStopWindow))
        {
          coincidence = true;
          break;
        }


      currentDetAPulse = pIterA;
    }   // end timing coincidence search

      /////////////////////////////////


      if(coincidence == false)
      continue;  //cut on timing


      //filling Histograms

      NGCDisc_plots[keyname]->Fill(fullInt, tailInt);
      NGCRatio_plots[keyname]->Fill(energy, ratio);


      float temp1 = 0.09579 + 0.02932/energy - 0.00385/(energy * energy);
      float temp2 = 0.10864 + 0.03444/energy - 0.00645/(energy*energy);


      if((detname == "NDet") && (ratio > temp1)) 
    NGNCEnergy_plots[keyname]->Fill(energy);
      if((detname == "NDet") && (ratio < temp1)) 
    NGGCEnergy_plots[keyname]->Fill(energy);      
      if((detname == "NDet2") && (ratio > temp2))
    NGNCEnergy_plots[keyname]->Fill(energy);
      if((detname == "NDet2") && (ratio < temp2))
    NGGCEnergy_plots[keyname]->Fill(energy);


```

**Comment by AndrewEdmonds11** [comment]
Hi Damien. Could you write "C++" directly after your backticks so we get some nice syntax highlighting?

**Comment by AndrewEdmonds11** [comment]
Also, do you have any plots highlighting the problem with the output?

**Comment by dmalexan** [comment]
The problem is that the timing cut seems to fail beyond a certain energy.  The energy of this failure seems to be dependent on what timing cut I'm making (shorter timing cuts fail at a higher energy).  If there was some smooth transition I would understand this better, but the cutoff is fairly sharp as evident in the 2D histogram below.

![ndet2_wtf](https://cloud.githubusercontent.com/assets/5910796/5632820/8bef57a6-9597-11e4-8b84-ee7bcc6fe316.jpg)

In some instances the cutoff gives a region rather than fullscale beyond some energy

![ndet2_gamma_al](https://cloud.githubusercontent.com/assets/5910796/5632941/4fc52fc0-9598-11e4-9e6c-c6983e239b1b.jpg)

**Comment by benkrikler** [comment]
Hey Damian,  I think it might be easier to follow through this code if I had it on my computer locally (then I can bounce around it in vim etc).  Have you been working on your own branch of rootana?  If so you could just push that and we can look at it directly then.  We don't need to merge anything into develop yet so don't worry about things being broken or not being finished etc.  But if you push your branch we can help more directly I think.

**Comment by AndrewEdmonds11** [comment]
Ok, I have a few questions.
- In the second block of code, is `detA` the muSc and `detB` one of the NDets?
- It looks to me that you have a second slightly different implementation of CF timing in the second block of code to calculate `timeB`. Is there a reason for this?
- Also, (I think this is @jrquirk's fault :p), why is there a `while` loop without any curly braces in the first block?
- Finally, in your first plot, what timing cut are you using?

**Comment by jrquirk** [comment]
> Also, (I think this is @jrquirk's fault :p), why is there a while loop without any curly braces in the first block?

By "fault" you must mean innovation. The code block

```
while (m != b && (trigger_polarity > 0 ? *--m > (int)cf : *--m < (int)cf));
```

which has no body, is supposed to step `m` back until either the first sample (`b` for beginning) or until it's above/below (-/+ polarity) the `cf` level. A std::lower_bound would be more readable, but I didn't know how to account for the negative polarity.

**Comment by dmalexan** [comment]
I've pushed the code to the github under the feature Neutron_Detectors.  The name of the module of interest is NGIntTCut.cpp.

Yes. detA is the muSc and detB is the NDets, Sorry for any confusion.

Other than some of the variable names, the only differences I can see are removal of some of the conditionals that are unecessary if we know the trigger polarity.  

the while loop is not supposed to have curly brackets, it's simply moving the iterator till the condition is met (shift is included in the condition).

The first plot should be using a timing cut of 20-200 ns with a constant fraction of 65% (I'm having problems going lower because of the linear interpolation).

**Comment by dmalexan** [comment]
There are a few corrections I made, 

```
  if(timeA > timeB + fstopwindow)  --> fStopWindow
    {
      coincidence = false;
      currentDetAPulse = --pIterA;  --> remove, causes a crash
      break;  //we passed the time window, no coincidence found
    }
```

**Comment by AndrewEdmonds11** [comment]
> By "fault" you must mean innovation.

Whoops. I didn't know about that use of the while loop. Looks like I'm learning everything about C++ today :D.

> Other than some of the variable names, the only differences I can see are removal of some of the conditionals that are unecessary if we know the trigger polarity. 

Is there a reason why the normal way doesn't work with the NDets?

Also, your second plot is just photons, right? Does that correspond to anything in the top plot (e.g. is it a projection onto the x-axis of some part of that first plot)?

**Comment by jrquirk** [comment]
You could also try MaxBin timing instead, just to make sure the problem resides in the timing calculation. You'll have to redo the time shifts if you do this.

Also, maybe look at a pulse with the ExportPulse module that is in a funny region and then one that's in a normal region. Print out the times for some of them and see if they are what you expect.

**Comment by dmalexan** [comment]
The AnalysePulseIsland module works fine on the neutron detectors, I removed the excess lines from the code when I transferred it to try and keep it more readable.  I doubt it saves much in the way of processing time, though there shouldn't be any change in how it's processed (just choosing outcome from the conditional that we know).  I can add it back in if it will help.  I am considering moving the ratio analysis to AnalysePulseIsland in an attempt to clean up the code somewhat.

The second plot is a projection of the gammas (the group with the lower ratio) onto the x axis.  These two plots are from different runs, with the 1-d plot having aluminum timing (200-2000 ns), and the 2-d plot having prompt timing (-20 to +20 ns), not 20-200 ns as previously stated (sorry).

I've already tried the maxbin method and it works fine (these artifacts do not show up).  Ido need to print up timing to ensure there is no problem.  The architecture is already in place in NGammaInt.cpp to print up waveforms.  I need to port it over to examine ones that are left after the cut.  I should have both done by tomorrow.

**Comment by dmalexan** [comment]
There are some compilation issues with the current version.  I'm trying to set it to what I'm working with, but I'm using a completely separate AlcapDAQ file.  I'm having some difficulty undoing all the changes to make this run, is there some way to add my file structure as a separate branch?

I'd also like to ask a quick question regarding all versions.  When I attempt to run the code, I get messages stating 
"Completed 0 out of 0 events"
"Completed 100 out of 0 events"
then I throw a bad_alloc error at roughly 115 events.  When running the exact same code on the lab computer, the number of events displays normally and the program finishes all events without a problem. I've tried running the code printing both total number of events and event that I am on for each iteration which seems to work fine.  Not the biggest problem, but I thought I'd check if anyone else has run into something like this or if anyone had any ideas.

**Comment by AndrewEdmonds11** [comment]
Hi Damien

>  I'm having some difficulty undoing all the changes to make this run, is there some way to add my file structure as a separate branch?

I don't understand what you mean. Are you trying to update your branch to match the latest version of develop?

> then I throw a bad_alloc error at roughly 115 events. When running the exact same code on the lab computer, the number of events displays normally and the program finishes all events without a problem.

This is odd, I haven't seen it. What systems are they and what compilers do they use?

**Comment by dmalexan** [comment]
I've worked out the first part.

This error is on my laptop.  A Lenovo G505 running Fedora 19 with g++ v 4.8.3 20140911.
For some reason, my computer was unhapy with the Long64_t type.  Changing it to a standard c long corrected the printout issue.  This strikes me as odd, I've already enabled 64 bit addressing in the OS, and I'm using the same version of root.

I'm not sure if I can do anything about the bad_alloc error though, I believe that stems from too little memory (increased the swap partition, but that did not help at all).

**Comment by dmalexan** [comment]
I've found the error.  I'm already subtracting the pedestal before the  constant fraction calculation.  The inclusion of it there then causes the sudden jump at the point where the cf crosses over the threshold.  It has been removed and the pulses are look as expected.

![ndettcutfixed](https://cloud.githubusercontent.com/assets/5910796/5668696/14f2c3f8-9737-11e4-91b3-e4cb32a2dde1.jpg)
