### ISSUE TITLE
Increment ClassDef of TSetupData?

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#26]
[Copied from the thnam repository]

We recently changed TSetupData to also include whether or not a bank was enabled from the wiremap. Root considers that a 'schema evolution' so we should increment the number in the ClassDef to show the data members have changed. I don't think that happened when the new information was added though, and so now there's a problem reading in old files that didn't have this info put into them. It might be worth changing that number before we go for Alcapana Production 2.0, but I don't have the experience to say what that would mean for the data files from the current Alcapana Production...

**Comment by litchfld** [comment]
It does need to be bumped for development, and AFAIR there is no downside to bumping even if nothing has changed. So I bumped it in my feature branch. Develop should probably do the same - if you want to read old files use the tagged version... we do have a tagged version, right?

**Comment by benkrikler** [comment]
Done and pushed to develop: c9d9647f105e84d7e4d1674e37b499bbc335ec8b
