### ISSUE TITLE
rootana linking to libDataClasses

### ISSUE THREAD

**Issue by thnam** [alcap-org/AlcapDAQ#263]
rootana is linked to the libDataClasses under user's working directory:

``` bash
[hoai_n@merlinl01 rootana]$ cat Makefile

.....
ALCAPANA_DATACLASSES := $(DAQdir)/analyzer/work/$(USER)/libDataClasses.so
....
```

But the batch script uses another alcapana executable from another place:

``` bash
[hoai_n@merlinl01 rootana]$ cat ../batch/scripts/production-run-3/batch_alcapana_prod-run-3.sge
#!/bin/bash
# batch_alcapana.sge
....
################
# Command to run
CMD="$DAQdir/analyzer/work/data_quality/alcapana"
ARGS="-i $RAWFILE -o $HISTFILE -T $TREEFILE"
....
```

This might cause problem later if there is something <del>compatible</del> incompatible between the data_quality and the $USER dirs.

**Comment by jrquirk** [comment]
Phil pointed this out a while ago and we just never dealt with it. I'll change on of them today.
