### ISSUE TITLE
Remove run 3257 from the golden datasets

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#265]
Run 3257 has being giving me problems for a while. When running on Merlin, it keeps on crashing and being resubmitted (as designed I think) so I suggest we remove it from the production DB.

I think the relevant sqlite command is `DELETE FROM datasets WHERE run=3257;` 

Can someone confirm this before I screw up my local production DB?

**Comment by jrquirk** [comment]
Yep. Same thing happens to me. Also the record from table alcapana_v3 should go if that goes. You can make a backup first if you're worried.

**Comment by AndrewEdmonds11** [comment]
Yes that command works and I've implemented it in my local databases.
