### ISSUE TITLE
Cleaning Up My Branches

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#267]
Hi Everyone!

I'm finally getting round to cleaning the branches I used for my analysis and thesis (both in AlcapDAQ and g4sim). To be honest, I don't think there's much hope in getting anything merged back in to develop because of the mess but it might be useful if we ever want to go back and check some of my work. Once it's all done, I'll post a summary here.

Cheers,
Andy

**Comment by AndrewEdmonds11** [comment]
Ok, all done. I've renamed the main scripts/Al50 folders in both AlcapDAQ and g4sim to scripts/Al50_andy-thesis. The versions of scripts committed in there are the ones I used for my thesis and should have all the hardcoded filenames/efficiencies etc. that I used so that I can go back and double check any of my work should we need to.

I wouldn't recommend using any of it though...

**Comment by benkrikler** [comment]
Hey Andy.  What branch was this on?  AE_Al100-simulations?

**Comment by benkrikler** [comment]
Also, (sorry for the spam) where were the main configuration files / macros you used for G4Sim?  Is `alcap/macros/andy_run.mac` the main macro you used?

**Comment by AndrewEdmonds11** [comment]
For g4sim it was AE_Al100-simulations and for AlcapDAQ it was AE_remove-scattered-muons. I've been pretty poor at changing branches when I move onto something new but I'm planning on redoing things from scratch a little.

Yes, it's andy_run.mac and then when I want to vis something I uncomment the test_vis.mac line
