### ISSUE TITLE
Move TAP, TDP and TME classes into rootana

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#27]
I think this was left over from the PSI run, but at the moment the classes for TAnalysedPulse, TDetectorPulse and TMuonEvent are all defined in files stored in analyzer/src/common.  I don't think they're used at all by alcapana, and I'm uneasy having to change 'common' code.   

I wanted to check there were no objections then to me moving these files into rootana/src somewhere..

**Comment by AndrewEdmonds11** [comment]
I think that's sensible. Should we also have TPulseIsland, TGlobalData and whatever else recompiled at the same time as rootana so that we don't have to compile alcapana first?

**Comment by benkrikler** [comment]
That's a really good idea!  I was actually scratching my head to find which part of the alcapana make process compiles those classes.  Do you know where it does?

So to summarise, I'll move the code for TAPs, TDPs and TMEs into rootana, then leave the code for TPIs TGlobalData and TSetupData in analyser/src/common, but  tell rootana to compile them as well somehow.  I'm not sure the best way to implement that last bit. Maybe I'll add an EXTERNALS variable into files.make which we can use to specify specific external files maybe?  The objects they produce would still sit in rootana.  Hopefully they don't depend on anything else within alcapana. If so then it might be more trouble than it saves.

**Comment by benkrikler** [comment]
In answer to my own question how alcapana knows to compile the TAP, TDP and TME code, it's on line 87 of the analyzer/Makefile: `DATA_LIBRARY_CLASSES = $(shell cat ../../src/common/DataLibraryClasses.list)`.

**Comment by benkrikler** [comment]
Does anyone use the MAnalysePulseIsland module?  It's the only module that depends on TAnalysedPulse, so it would suffer if I move TAnalysedPulse into rootana.

**Comment by AndrewEdmonds11** [comment]
No, I don't think so. It isn't used in the data_quality version of alcapana and I think we all now know to do this in rootana. I guess I wrote it during the run

**Comment by benkrikler** [comment]
Cool ok.  Should I delete that module whilst I'm there then?  Or leave it for future reference?

**Comment by AndrewEdmonds11** [comment]
Even if it's deleted it's still in the repository right? I would say delete it to avoid confusion if someone new comes along to use the code (they're going to need all the help they can get)

**Comment by benkrikler** [comment]
I've now moved this code into rootana.  I was unsure about which sub-directory they should go into, so for now I've put them in their corresponding generator sub-directory.  Perhaps they should actually go in the event navigator directory when that's finished.  Is it important (probably not...)?

As for getting rootana to compile without compiling alcapana, I'm going to put it on the back burner for now cause I want to focus on other things a bit..

**Comment by benkrikler** [comment]
Ok, I've spent the last few hours wrestling with this but I think I might have done some damage here.  I'm geting problems with root not being able to find various dictionaries.  Does anyone have proper experience with makefiles and rootcint to be able to work out what's going wrong.  Importantly, this may affect the develop branch.  I think, if I cant solve this soon, that I will roll back these changes.  They've given me much more grief than the should have done...

**Comment by AndrewEdmonds11** [comment]
What are you having problems compiling? I was fine with alcapana after I did a make clean...

**Comment by benkrikler** [comment]
ok, so alcapana now seems ok, I think I'd been playing around with LD_LIBRARY_PATH and that broke things there.  Can I confirm though, we've always had the situation that if we open root from outside of work/$USER we don't get the class dictionaries for TGlobalData, TSetupData and so on?  In other words, if you do:

```
cd analyzer/work
root
.class TSetupData
```

you get an error like: `Error: class,struct,union or type TSetupData not defined  :0:`
If so, I've not broken that, it's just behaviour I hadn't noticed.

Rootana still seems to be playing up though... I'll update in a miute after some more investigating..

**Comment by AndrewEdmonds11** [comment]
I don't know if we've always had it but it certainly just happened to me in analyzer/work but it's fine in work/data_quality.

**Comment by benkrikler** [comment]
Phew, panic over.  Some dodgy combination of a lack of make cleans and playing with LD_LIBRARY_PATH meant that rootana wasn't working, but things seem ok now.  The changes are on another branch but I'll merge it shortly...

**Comment by litchfld** [comment]
YEAY =)

**Comment by benkrikler** [comment]
I'm going to close this for now as the original purpose has been finished.  I've not got rootana compiling TSetupData, TGlobalData or otherwise, so we still need the alcapana library.  I'll open another ticket for that task, but I wouldn't expect it to happen anytime soon....
