### ISSUE TITLE
Batch script errors on merlin

### ISSUE THREAD

**Issue by dmalexan** [alcap-org/AlcapDAQ#270]
Attempting to run the batch scripts on merlin.  Files are downloading, jobs are getting accepted, just not completing (and I can't seem to catch them on qstat).  Looking at the error log, I see the following entry:

Warning in TGMimeTypes::TGMimeTypes: error opening mime type file /etc/root/root.mimes
/gpfs/home/alexander_d/AlcapDAQ/analyzer/work/data_quality/alcapana: symbol lookup error: /gpfs/home/alexander_d/AlcapDAQ/analyzer/work/data_quality/libDataClasses.so: undefined symbol: _ZN4ROOT14RegisterModuleEv

I'm checking for solutions, but right now not sure where to start.

**Comment by AndrewEdmonds11** [comment]
Hmm... I'm not sure I've seen this one before. Is that the directory alcapana is compiled in or do you have it compiled in your $USER folder?

**Comment by dmalexan** [comment]
I have it compiled in the data_quality folder.  Should I compile in my own folder as well?

**Comment by AndrewEdmonds11** [comment]
I don't think so. It looks like it's trying to find it in the data_quality folder so I don't know why it's complaining. Which script is it you're using to submit to Merlin?

**Comment by benkrikler** [comment]
When I get undefined symbol errors often they can be solved by doing `make clean` then `make`.  In those cases the cause is that I've added a function to a class but for whatever reason the '.o' file isn't recompiled so the library is made linking object files that don't define all symbols whilst the compiler before it has no problem since the headers all make sense.

You may have already tried it, but if not it's relatively quick and would remove one possible cause at least.  Hope it helps!

**Comment by dmalexan** [comment]
I'm running a modified version of the alcapana production run scripts from last year.  In the end the command is 
$DAQdir/analyzer/work/data_quality/alcapana -i $RAWDATADIR/run[number].mid -o $HISTDATADIR/hist[number].root -T $TREEDATADIR/tree[number].root
DAQdir is defined in thisdaq.sh, the others are all in ~/data/[DATADIR]

I thought I had already done a clean compilation, but tried it again to make sure.  Problem still persists.  Could Merlin be trying to use a different version of root to process alcapana?

**Comment by AndrewEdmonds11** [comment]
> Could Merlin be trying to use a different version of root to process alcapana?

Possibly. If you type `which root`, is it pointing to your version in AlcapDAQ? 

Also, is there something we've added to the code that needs compiling in ROOT? (I'm guessing not because you can run on the login node, right?)

**Comment by dmalexan** [comment]
I am using the AlcapDAQ verson of root.  I'm unsure about your second question.  Nothing I've added should need root permissions, but I cannot speak for all the changes.

As to nodes, I'm still fairly new to this.  I am attempting to run directly after login (and sourcing a couple of files).  I've also attempted to run in a screen with no luck. If there's something more specific to check or try, please let me know.

**Comment by jrquirk** [comment]
In the output log, there should be a line like "LD_LIBRARY_PATH=...". Could you post that? If not, could you post the output of `echo $LD_LIBRARY_PATH`. Additionally, could you you provide the fewest steps to reproduce the issue, including the MODULES file, sourcing the thisdaq.sh, and making/cleaning. And finally, could you confirm when you say 

> I'm running a modified version of the alcapana production run scripts from last year.

You're referring to changing the CMD and ARGS variables of analyzer/batch/scripts/batch_alcapana.sge?

**Comment by dmalexan** [comment]
I've looked through the .sge folder, though it has remained mostly the same.  Most of the edits are to the accompanying .sh file to correct data locations, script locations, etc.  I tried making some other little changes, though they've since been redacted.

I will push the MODULE and script files to R15a shortly.
On connecting to merlin.

> cd AlcapDAQ
> . thisdaq.sh
> cd root-install
> . bin/thisroot.sh
> cd ../analyzer/work/data_quality
> make clean
> make
> cd ../../batch/script/R15a_DQrun1
> emacs R15a_DQrun1_Ambient.sh    ( add -p [password from email])
> ./R15a_DQrun1_Ambient.sh  
> (errors show up under $DAQdir/analyzer/batch/log/alcapana.run06179.err)

LD_LIBRARY_PATH=/gpfs/home/alexander_d/AlcapDAQ/sqlite-install/lib:/gpfs/home/a\
lexander_d/AlcapDAQ/midas/linux64/lib:/gpfs/home/alexander_d/AlcapDAQ/compress:\
/opt/root/root-5.34/lib/root:/gpfs/home/alexander_d/AlcapDAQ/CAEN/lib:/gpfs/hom\
e/alexander_d/AlcapDAQ/analyzer/rootana

**Comment by jrquirk** [comment]
You are definitely not using the ROOT version in AlcapDAQ for the submitted jobscript because thisdaq.sh isn't sourcing it. You recognize this in your login session as you explicitly go to root-install and source bin/thisroot.sh. This information is _not_ passed to the node, however, as it still only sources thisdaq.sh.

There are a number of fixes:
1. Link to AlcapDAQ/root-install and call it AlcapDAQ/root
2. Rename root-install root.
3. Change thisdaq.sh to source root-install/bin/thisroot.sh instead.
4. ...

You can probably see where this is going. The smoking gun is in ~alexander_d/AlcapDAQ/analyzer/batch/log/alcapana.run06179.out the top of the file says

> Check you've got root set up properly on this machine

If the problem persists, let us know. Otherwise, this is our one win for the day.

**Comment by AndrewEdmonds11** [comment]
> thisdaq.sh isn't sourcing it

It does on the branch I am on (R13). I think we should match what's there...

**Comment by dmalexan** [comment]
thisdaq.sh looks in the file AlcapDAQ/root/bin.  The way the root install macro works (cmake) this file is never made and no compilation occurs in the root folder itself.  if you install root using the install-root.sh macro, the compilation occurs in root-install.  I've edited thisdaq.sh on R15a to look in AlcapDAQ/root-install/bin now.  I will try running it and let you know.

**Comment by dmalexan** [comment]
Some progress, though I need the odb files for this to work.  Merlin is rejecting permission to pull from BU and I don't see them on ftp server (unless they're under a different folder).

**Comment by jrquirk** [comment]
The files are on alcap@susy.bu.edu:/data/R15a/odb as you imply, but also on merlin:/gpfs/home/quirk_j/data/R15a/odb.

**Comment by benkrikler** [comment]
You're running the alcapana executable right?  If you find where it's located (`which alcapana`) and then do `ldd` on that file, you will get a list of all the libraries being linked in and where they are located.  Then we could check that list to see if any libraries aren't being found and where the found libraries are located.

So try doing:

```
ldd `which alcapana`
```

then post the output of that here.  (I think alcapana was the name of the executable, right?)
It might also be worth submitting a batch job that does this (after doing your normal setup stuff) just to check that things are working on the batch system ok.

**Comment by dmalexan** [comment]
Script running.  Histograms generated.  Will double-check histograms later.
