### ISSUE TITLE
Reading keys from ODB

### ISSUE THREAD

**Issue by dmalexan** [alcap-org/AlcapDAQ#271]
Working on the MDQ_Threshold module.  I have it searching for and finding the keys.  It retrieves a value, but the output is weird.  Most of these keys are in WORD or DWORD type, and when I output the value obtained (Thresholds[0], same thing used to fill the histograms last time) I get values in the range of 10^-42 for the DWORD types and aproximately -1.5 for the WORD types.  The values for most of these should be falling in the 7000 or 15000 range according to the odb itself.  How did this work last time, and what can be done to correct this now?

**Comment by AndrewEdmonds11** [comment]
Do you have the code itself so we can take a look?

I'm just looking at some of the old code to jog my memory and it looks like we had three steps:

``` c
   if(db_find_key(hDB,0,keyName, &hKey) != SUCCESS){
    printf("Warning: Could not find key %s\n", keyName);
    return false;
   }
   KEY upper_threshold_key;
   if(db_get_key(hDB, hKey, &upper_threshold_key) != DB_SUCCESS){
      printf("Warning: Could not find key %s\n", keyName);
      return false;
   }
   INT UpperThresholds[upper_threshold_key.num_values];
   size = sizeof(UpperThresholds);
   if(db_get_value(hDB, 0, keyName, UpperThresholds, &size, TID_INT, 0) != DB_SUCCESS){
    printf("Warning: Could not retrieve values for key %s\n", keyName);
    return false;
   }
```

So we had to find the key, get the key and then get the value (making sure that the variable we were passing the value into was the correct type and size).

Does that help?

**Comment by dmalexan** [comment]
I am copying this practically verbatim, which is why I am confused the output is so different.  Most of the values in the current setup are recorded as WORD or DWORD, but this was the case for the UH CAEN unit in R13 as well and I see no problem with the picture book values.  Was there any post-processing on these histograms?

**Comment by dmalexan** [comment]
``` C++
    //---------------------dt5730----------------------------//
    if(TSetupData::IsWFD(bankname) && bankname.at(1) == '7'){
      // first get the channel and address from the bankname
      int iChn = (int)(bankname[3] - 48);

      // Get the threshold
      sprintf(keyName, "/Equipment/Crate 7/Settings/CAEN/Ch0%d/Self trigger threshold DPP", iChn);
      if(db_find_key(hDB,0,keyName, &hKey) != SUCCESS){
    printf("Warning: Could not find key %s\n", keyName);
    return false;
      }
      KEY threshold_key;
      if(db_get_key(hDB, hKey, &threshold_key) != DB_SUCCESS){
    printf("Warning: Could not find key %s\n", keyName);
    return false;
      }
      float Thresholds[threshold_key.num_values];
      int size = sizeof(Thresholds);
      if(db_get_value(hDB, 0, keyName, Thresholds, &size, TID_WORD, 0) != DB_SUCCESS){
    printf("Warning: Could not retrieve values for key %s\n", keyName);
    return false;
      }
      std::cout << bankname << "   "  << Thresholds[0] << std::endl;

      DQ_Thresholds_histograms_map[bankname]->Fill("Self_trigger_threshold DPP", Thresholds[0]);
    }
```

**Comment by dmalexan** [comment]
output from the comment lines

D400   1.12104e-41
D401   1.12104e-41
D402   1.68156e-41
D403   0
D404   0
D405   0
D406   2.10195e-42
D407   4.2039e-42
D500   -1.63284
D501   -1.63285
D502   -1.63285
D503   -1.63285
D700   -1.63284
D701   -1.63286
D702   -1.63292
D703   -1.63293
D704   -1.63286
D705   -1.63286
D706   -1.63284
D707   -1.63285
D800   4.2039e-42
D801   1.4013e-42
D802   1.4013e-42
D803   0
D804   5.46506e-42
D805   4.2039e-42
D806   0
D807   4.2039e-42

**Comment by AndrewEdmonds11** [comment]
> Was there any post-processing on these histograms?

Only in the picture book macros, where line widths/colours etc. were changed. Nothing to the values themselves.

Looking at the code you've just posted, I think it's here, where you need to make sure that the types match:

``` c
float Thresholds[threshold_key.num_values]; // float should be WORD so that it matches TID_WORD two lines down
int size = sizeof(Thresholds);
if(db_get_value(hDB, 0, keyName, Thresholds, &size, TID_WORD, 0) != DB_SUCCESS){
    printf("Warning: Could not retrieve values for key %s\n", keyName);
    return false;
```

Has that worked?

**Comment by dmalexan** [comment]
Found error, while I updated the type call under db_get_value, I did not update the type of Thresholds.  Corrected and working
