### ISSUE TITLE
Picture book compilation errors

### ISSUE THREAD

**Issue by dmalexan** [alcap-org/AlcapDAQ#272]
I am having two types of problems with the picture books, and could use some help.
1.   Several of the section and subsection headings are coming out incorrect.
   ~~a)  The subsections for the first section (section[0]) are being written as section headings.
   Under CreateSections() 

``` C++
  section_headings[0].section_name = "\\section{Digitizer-specific Issues}\n\n";
  (section_headings[0]).subsection_names[0] = "\\section{Digitizer Overflows}\n\n";
  (section_headings[0]).subsection_names[1] = "\\section{Digitizer Errors}\n\n";
```

Under GetListOfLines()

``` C++
      std::string plotname = plotname_cstr; // convert to std::string so I can use find()

      // Work out which section and subsection this plot is for
      int section = -1;
      int subsection = -1;


      if (plotname.find("Digitizer") != std::string::npos) {
        section = 0;

        //Check for subsection
        if (plotname.find("Overflow") != std::string::npos){
          subsection = 0;
        }
        else if (plotname.find("Error") != std::string::npos){
          subsection = 1;
        }

      }
.
.
.
      // If the section was found...
      if (section >= 0) {
        // ...add the section heading if it hasn't been started yet
        if (section_headings[section].section_started == false) {
          plot_names.push_back(section_headings[section].section_name);
          section_headings[section].section_started = true;
        }
      }

      // If the subsection was found...
      if (subsection >= 0 && section >= 0) {
        // ...add the subsection heading if it hasn't been started yet
        if (section_headings[section].subsection_started[subsection] == false &&
        section_headings[section].subsection_names[subsection] != "" ) {

          plot_names.push_back(section_headings[section].subsection_names[subsection]);
          section_headings[section].subsection_started[subsection] = true;
        }
      }
```

In the Tex file however, it generates

``` LaTeX
\section{Digitizer-specific Issues}

\section{Digitizer Errors}

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_Digitizer_DT5720Errors.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_Digitizer_DT5730Errors.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 

\section{Digitizer Overflows}

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_DigitizerOverflow_FractionByEvent.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_DigitizerOverflow_Fraction.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 
```

I'm guessing this has something to do with the use of 0 for saying the section exists.~~

b)
Similarly, I have a subsection that gets mislabeled

``` C++
  section_headings[1].section_name = "\\section{TPulseIsland-specific data quality issues}\n\n";
  (section_headings[1]).subsection_names[0] = "\\subsection{Total number of TPulseIslands}\n\n";
  (section_headings[1]).subsection_names[1] = "\\subsection{Length of TPulseIslands}\n\n";
  (section_headings[1]).subsection_names[2] = "\\subsection{Rate of TPulseIslands}\n\n";
  (section_headings[1]).subsection_names[3] = "\\subsection{Timestamps of TPulseIslands}\n\n";
  (section_headings[1]).subsection_names[4] = "\\subsection{Amplitudes of TPulseIslands}\n\n";

  section_headings[2].section_name = "\\section{Pulse Details}\n\n";
  (section_headings[2]).subsection_names[0] = "\\subsection{Pulse Shape Persistancy Plot}\n\n";
  (section_headings[1]).subsection_names[1] = "\\subsection{Neutron Gamma Separation plot}\n\n";
.
.
.
      else if (plotname.find("Island") != std::string::npos) {
        section = 1;

        // Check for subsection
        if (plotname.find("Counter") != std::string::npos) {
          subsection = 0;
        }
        else if (plotname.find("Length") != std::string::npos) {
          subsection = 1;
        }
        else if (plotname.find("Rate") != std::string::npos) {
          subsection = 2;
        }
        else if (plotname.find("Timestamp") != std::string::npos) {
          subsection = 3;
        }
        else if (plotname.find("Amplitude") != std::string::npos) {
          subsection = 4;
        }
      }
      else if (plotname.find("PulseShapes") != std::string::npos) { // want the Pedestal and Noise plots to be put into a separate section even though they are created in this module
        section = 2;
        subsection = 0;
      }
      else if (plotname.find("HEFoM") != std::string::npos) {
        section = 2;
        subsection = 1;
      }
```

Which outputs

``` LaTeX
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_IslandCounter_V1724_5_D405.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 

\subsection{Neutron Gamma Separation plot}

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_IslandLength_BROKEN_D700_normalised.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\begin{figure}[h] 
\begin{center} 
```

I'm definitely more perplexed by this error, especially as I do not have any of the plots that should generate this subsection to begin with.  This is probably some error of understanding in how these titles are searched and generated.  It is also worth noting that the Amplitude section is created in subsection 1 despite being labeled as subsection 5.

2.
I have a problem with the compilation not completing (error on the last section).  Checking the output file the last few lines are:

> <data_quality_figs/hDQ_TDCCheck_nMuons.png, id=1371, 698.61pt x 473.77pt>
> <use data_quality_figs/hDQ_TDCCheck_nMuons.png> [166 <./data_quality_figs/hDQ_T
> DCCheck_Muon_time.png> <./data_quality_figs/hDQ_TDCCheck_nMuons.png>])
> Runaway argument?
> {Timing) \par \subsection {Sync Pulses} \par \begin {figure}[h] \begin \ETC.
> !> File ended while scanning use of \@xdblarg.
> <inserted text> 
>                \par 
> <*> Data_Quality_Run6179
> These files do occur in the listoflines.txt file
> data_quality_figs/hDQ_TDCCheck_nMuons.png
> data_quality_figs/hSyncCount_Crate0.png
> data_quality_figs/hSyncCount_Crate1.png
> data_quality_figs/hSyncCount_Crate2.png
> data_quality_figs/hSyncCount_Crate3.png
> data_quality_figs/hSyncCount_Crate4.png
> data_quality_figs/hSyncCount_Crate5.png
> data_quality_figs/hSyncCount_Crate6.png
> data_quality_figs/hSyncCount_Crate7.png
> data_quality_figs/hSyncCount_Crate8.png
> data_quality_figs/hSyncCount_TDC.png
>  The images seem to be included in the Tex file
> 
> ``` LaTeX
> \subsection{Number of muons hits}
> ```

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_TDCCheck_nMuons.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 

\section{Timing)

\subsection{Sync Pulses}

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate0.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate1.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate2.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate3.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate4.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate5.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate6.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate7.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate8.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_TDC.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 

\newpage 
 \clearpage

\end{document}

```
This one has me completely lost as to the cause.
Any thoughts?                     
```

**Comment by dmalexan** [comment]
First problem fixed

**Comment by AndrewEdmonds11** [comment]
Hi Damien

It look like your running into my horrible code :p. It is a bit of a mess of hard-coded sections and section headings etc. 

For part b of section 1, should:

``` c++
(section_headings[1]).subsection_names[1] = "\\subsection{Neutron Gamma Separation plot}\n\n";
```

be

``` c++
(section_headings[2]).subsection_names[1] = "\\subsection{Neutron Gamma Separation plot}\n\n";
```

I'm not sure about the second problem. Do you have the corresponding section of the log output for the plot before hDQ_TDCCheck_nMuons?

**Comment by AndrewEdmonds11** [comment]
Or could it be that you have mismatched brackets. Should this:

```
{Timing) \par \subsection {Sync Pulses} \par \begin {figure}[h] \begin \ETC.
```

be

```
{Timing}....
```

(i.e. close with a curly bracket rather than a normal one)?

**Comment by dmalexan** [comment]
output.txt

```
<data_quality_figs/hDQ_TDCCheck_Muon_rate.png, id=1360, 698.61pt x 473.77pt>
<use data_quality_figs/hDQ_TDCCheck_Muon_rate.png> [165 <./data_quality_figs/hD
Q_RunTime.png> <./data_quality_figs/hDQ_TDCCheck_Muon_rate.png>]
<data_quality_figs/hDQ_TDCCheck_Muon_time.png, id=1370, 698.61pt x 473.77pt>
<use data_quality_figs/hDQ_TDCCheck_Muon_time.png>
<data_quality_figs/hDQ_TDCCheck_nMuons.png, id=1371, 698.61pt x 473.77pt>
<use data_quality_figs/hDQ_TDCCheck_nMuons.png> [166 <./data_quality_figs/hDQ_T
DCCheck_Muon_time.png> <./data_quality_figs/hDQ_TDCCheck_nMuons.png>])
Runaway argument?
{Timing) \par \subsection {Sync Pulses} \par \begin {figure}[h] \begin \ETC.
! File ended while scanning use of \@xdblarg.
<inserted text> 
                \par 
<*> Data_Quality_Run6179
```

and a shifted segment of the LaTeX output to cross check

``` LaTeX
\section{Run Time}

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_RunTime.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\section{TDC-specific data quality issues}

\subsection{Rate of muon hits}

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_TDCCheck_Muon_rate.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 

\subsection{muon hit times}

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_TDCCheck_Muon_time.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\subsection{Number of muons hits}

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hDQ_TDCCheck_nMuons.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 

\section{Timing)

\subsection{Sync Pulses}

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate0.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate1.png} 
\end{center} 
\vspace{-5mm} 
\caption{} 
\end{figure} 
\vspace{1.5cm}\clearpage 
```

**Comment by AndrewEdmonds11** [comment]
Yeh, I think it's here from the latex that's created:

``` latex
\section{Timing) - should be a }

\subsection{Sync Pulses}

\begin{figure}[h] 
\begin{center} 
\includegraphics[height=0.33\textheight, angle=0]{data_quality_figs/hSyncCount_Crate0.png} 
\end{center} 
```

In whichever part of whichever script defines the section headings, this should be changed

**Comment by dmalexan** [comment]
This fixed it, sorry for the troubles.  Now to get the trendplots and dataset picturebooks working
