### ISSUE TITLE
Is there a reason TSetupData is stored in a Tree?

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#29]
Since it derives from TObject it could sit directly in the file quite happily.  That wouldn't work so well if there were multiple versions of TSetupData in a file, but i've never seen that, and if there was, I don't know how you'd work out which one you would use...  Is this a capability we need to preserve?

**Comment by AndrewEdmonds11** [comment]
I don't think so. I can't see any reason we would want more than one TSetupData
