### ISSUE TITLE
Interesting Git hub ideas

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#30]
This isn't really an issue, but I thought I'd share this link for a GitHub flow model:
https://guides.github.com/introduction/flow/

I'm not suggesting we change how we're working; I think it's going fine with git flow.  I just wanted to share this to give people some ideas about using pull-requests more...

**Comment by benkrikler** [comment]
Ok, I'm finding more interesting stuff there.

For publication purposes, we can set up a DOI for our repository: https://guides.github.com/activities/citable-code/

Also, I've been looking into it a bit and there are ways to host doxygen documentation on github for any particular project.  I can setup a cron job as well that would update this nightly after a commit.  That might be quite helpful for the rootana documentation, and save me some effort updating things in the wiki.

**Comment by AndrewEdmonds11** [comment]
Nice. So a couple of questions:
1. Should we use the pull request feature when we want to finish a branch? I think it may slow us down a bit since we are adding features quite quickly but it won't...
2. Do you have any good guides on using Doxygen and how much work would it be to add it to old code? (I'm thinking of the data quality modules here...) I guess this would mean we keep the wiki just for instructions and guides and not for documenting each and every module.

**Comment by litchfld** [comment]
So that totally failed to tell me what a "pull request" is.  It's not doing 'git pull' at the command line, i can see that much...

**Comment by benkrikler** [comment]
@AndrewEdmonds11:
1.  I'm not sure whether or not we should use it to be honest.  You're definitely right about it being slower.  But I do feel nervous about merging in branches to develop each time.  So far it's been fine cause no one else has been working on the same area of code, but soon that should change and then pull requests might be a good way to announce things.  I don't think it works with git flow though, so maybe it's really not a good idea.
2.  I have no good guides off hand, though the minimum is essentially just stick a comment above each function and class definition using three slashes instead of 2.  Even if we add no extra comments, I find it can be much more digestible to browse code with doxygen.  You can see for example which other functions call this one, or what functions this one calls as well as all the inheritance graphs of a class and so on.

@litchfld: http://bit.ly/1wkT3tD.  It's the way to pull code from one branch or repository to another one within the github website itself.

**Comment by benkrikler** [comment]
Doxygen documentation is now implemented and the other ideas are here for longevity.  Discussion seems to have finished, so I'm closing this ticket...
