### ISSUE TITLE
Add TDC muSc Rate to MDQ_IslandRate

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#32]
It was suggested in today's meeting that we add the muSc rate from the TDC and add it to the IslandRate plot.

This would require adding the number of entries in hDQ_TDCCheck_muSc to hDQ_IslandRate before the whole histogram is scaled by the duration of the run.

This is definitely possible and easy to implement. However, since the last alcapana production run I have added muSc normalisation to a number of modules, including MDQ_IslandRate.

In this module, this means we do another scaling to hDQ_IslandRate by the number of entries in hDQ_TDCCheck_muSc. 

So my question is - is it OK to add the muSc count to hDQ_IslandRate even though it is going to be scaled back to 1 anyway? Or would people prefer that we do one or the other?

**Comment by jrquirk** [comment]
Perhaps keep it as is then? I didn't realize this...

**Comment by AndrewEdmonds11** [comment]
Clearly my summary in the meeting was too succinct then! I'll leave it as it is and close this issue. Just re-open and comment if you disagree
