### ISSUE TITLE
Produce ODB Correction Files

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#37]
If the ODB Checker is finished (@jrquirk?), we need to produce the ODB corrections.

What do people think the best way to do this is? One person to do them all? Create them just before people submit their runs to Merlin (i.e. put it in the alcapana-prod-run-1_dataset.sh scripts)?

I think we'll want to review the output before submitting but maybe that's not such a worry (we certainly aren't going to look through _all_ the files...)

**Comment by jrquirk** [comment]
It's a low-demand program. One person can run all of them. I'll incorporate the links into link_data.sh in case people don't want to run it.

I'm checking the corrections still. And I would greatly appreciate brand new eyes on the stuff.

**Comment by jrquirk** [comment]
link_data.sh has been updated
