### ISSUE TITLE
Channels erroneously labelled as disabled in wiremap

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#39]
This would fit nicely in a corrected ODB

**Comment by AndrewEdmonds11** [comment]
Which channels are these?

**Comment by jrquirk** [comment]
Sorry, I should've included some information. For run 3275, GeF is disabled in the WireMap but there are filled histograms. Also for not the Ge are array index 32/32.
![enabled](https://cloud.githubusercontent.com/assets/5143258/3131584/43cf3a7a-e806-11e3-9014-a8d11a858e26.png)
![detname](https://cloud.githubusercontent.com/assets/5143258/3131620/aaf301c8-e806-11e3-90ef-327b419b45f5.png)
![bankname](https://cloud.githubusercontent.com/assets/5143258/3131629/c6461a6e-e806-11e3-8264-d965e9a2726e.png)
![filled_histograms](https://cloud.githubusercontent.com/assets/5143258/3131585/43d0d146-e806-11e3-84bf-b68b5ce5943f.png)

**Comment by jrquirk** [comment]
The newest version of the ODBChecker marks channels with LLDQ histograms as enabled, and those without as disabled.
