### ISSUE TITLE
Dataset Picture Books - histograms that appear in later runs and not earlier ones

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#4]
When creating the dataset picture books, the names of the 1D histograms that are used to get the trend plots are obtained from the hist file for the first run.

This assumes that the histograms are the same for all runs in that dataset. This is certainly incorrect for Al50(a), where NDet2 histograms only exist in the final run range and so don't appear in the picture book. This was discovered because there was a "ghost" detector in the IslandRate trend plot.

I don't know how much this affects other runs but I'll try and think of a fix.

**Comment by jrquirk** [comment]
For the ODB checker I already have a struct WireMap which has a method to load from an ODB file. I could incorporate a diff method and then write a short program to output some sort of history of changes if people want. It won't fix the problem, if it is a problem. But it would indicate how constant det<->chan mappings are over a run.

**Comment by AndrewEdmonds11** [comment]
Yes, that's a good check, John.

Another check (although not as concrete) is, with the changes I made in commit b486b76cf69cb462b4dd490bb997983973cd0e8c (where any bin label in a run plot that is not already in the trend plot is added to the top of the y-axis), we can check the y-axis of the IslandRate plot for any detectors that appear suddenly, later in the dataset.

By doing this I only see the NDet2 detector appear in the final run range of Al50(a) (which we already know about). All the other datasets are fine.

I think it will be difficult to change the picture book macros to account for this so I think we should treat this as a separate dataset and generate a picture book for it on it's own.

Also, I think this is also the run range that we've proposed to demote to silver so this may all be moot anyway.

**Comment by AndrewEdmonds11** [comment]
I'm going to close this and say that the problem only occurs once, which we already know about, and the above solutions will work.

I think people just need to be aware of this.

**Comment by AndrewEdmonds11** [comment]
Looking at John's detector-channel map files in the drop box and with a bit of conditional formatting it looks like it occurs more than once but the other occasions it occurs are in Al100 and look to be duplicate detector names:

| Dataset | Run | Channel | From | To | Notes |
| --- | --- | --- | --- | --- | --- |
| SiR | None | N/A | N/A | N/A | N/A |
| Al100 | 2934 | Nh84 | NULL | SiR1-4-S | duplicate of Nh82 |
|  |  | Nb84 | NULL | SiR2-S | duplicate Nb80 |
|  |  | Na84 | NULL | SiL2-S | duplicate Na80 |
|  | 2889 | Ng81 | SiR1-sum-F | NULL | duplicates of SiR1-x-F (N{e,f,g,h}83)? |
| Al50a | 3442 | Nf81 | NULL | NDet2 | the one we know about |
| Si16P | None | N/A | N/A | N/A | N/A |
| Al50b | None | N/A | N/A | N/A | N/A |
| SiR2(3%) | None | N/A | N/A | N/A | N/A |
| SiR2(1%) | None | N/A | N/A | N/A | N/A |

I will also post this information to the elog
