### ISSUE TITLE
Update Production Scripts

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#40]
Production scripts need updating for the new run sets etc.

I will do this on the release branch

**Comment by AndrewEdmonds11** [comment]
This is mostly done now. Just one thing to mention is that I have hardcoded the directory with the correction ODBs to John's area. This is because I am uncertain of the effects when using link_data.sh if there are other files around before a big run (e.g. if you end up linking to someone else's hist and tree files for a run that you will now be doing, what will happen?)

**Comment by AndrewEdmonds11** [comment]
This now done. I will write the elog and send e-mails to let people know they can being production

**Comment by thnam** [comment]
I guess it is okay to delete the ROOT files from the first run.

**Comment by AndrewEdmonds11** [comment]
I think we may have to do this since I've just noticed that my quota is at 180GB/300 GB before this production run.

I would rather keep the data from at least one previous run but we do have a tagged version of the code from then so we can always re-run if we want to check with the past.

**Comment by AndrewEdmonds11** [comment]
Just a thought, but if we do need to make space it's probably best to delete the tree files (~1GB each) and are not used rather than the hist files (~7MB each) which might be good to look at in the future

**Comment by AndrewEdmonds11** [comment]
I've had to delete my old tree files from the first production run in order to make space. This shouldn't be too much of a problem since we were only really using the histogram files anyway

**Comment by thnam** [comment]
And I do have a copy of all of them locally.
