### ISSUE TITLE
Notes from EventNavigator discussion (Phill, Ben, Andy)

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#44]
Full notes; any discussion should probably break of the relevant question into a separate issue.
#### How do we query a pulse generator for the type of pulse it produces?

We will know the generator from the branch name on file, but generator->pulse type (a subcass of basic TAnalysedPulse etc) can be many to one.  What if we wish to examine all pulses that have a particular kind of output? Options considered were (we settled on number 3): 
- Store a 'pet' pulse of the appropriate type, then type can be deduced, schematically this is `typeid(*(Generator::GetPetPulse()))`. The return value of GetPetPulse() must be a pointer/reference to the base class, but as long as it has a VTABLE this works. 
- Template the generator on the pulse, and have a method that can return a pointer to the template parameter. Because this is static polymorphism you only need to return a temporary pointer, not to an existent object, however this is not a major advantage since pulses objects should be small, and generators few in number.
- **Do nothing.  Assume the exact type of the generated pulse can only be needed when you actually have a container of (pointers to) them, and that all contained objects are of the same derived type. One need only examine the type of an object in the container.**
#### Do we need to provide converted vectors for derived pulse types?

Internally the EventNavigator will store `vector<TXxxPulse*>`s but these pointers may actually be pointing to instances of sub-classes `TSpecialisedXxxPulse`. Is it possible & helpful to provide conversions, i.e. a method that can return a (const, temporary) vector<TSpecialisedXxxPulse*>?

Yes it is possible:

``` C++
vector<B*> vb;
// ... add pointers to vb ...

vector<A*> va(vb.size());
template<typename B, typename A> B* unary(A* a){return static_cast<B*>(a);} 
std::transform(vb.begin(), vb.end(), va.begin(), unary);
```

Although it is slightly inefficient because we are copying all the pointers.  However it saves a little because the user doe not have to dynamic cast each one.

Possibly better to provide a python-like generator as this idiom is expected to be used in other places as well.
#### If multiple containers exist from multiple algorithms, do we provide a default?

For a given detector at a give stage in reconstruction there may be multiple stored answers. It is convenient just to have a method that returns one, for the normal case if the user does not care or know which algorithm was used. But this must either default or blow up if multiple versions exist.
- For now we decide to take the first thing we come across. Can be modified later if a use case is apparent
##### If yes does this have any additional implications?
- This should definitely be possible.
- It shouldn't require too much special adjustment because the model is that data is first copied over to the new file, so should be able to treat it in the same way as a module output.
##### What about TGlobalData?
- This is to be treated as a special case and always copied over at start, _but_ since we don't necessarily want to save it it can exist as a temporary (see below) that persists for the event and no longer.
#### What is the form of tree // branch names?
- `tree` => "PulseIslands", "AnalysedPulses", "DetectorPulses", etc
- `branches` => "detector::generator::config_name"
- [**TODO:** check that "::" is acceptable in branch names]
#### Do we need separate detector IDs for DetectorPulses and AnalysedPulses?
- Analysed pulses come in two flavours: _Fast_ & _Slow_, detector pulses collase the two, by definition.
- It's reasonable to think the code should accommodate asking for SiL1-F in the context of a DetectorPulse, but asking for SiL1 from an AnalysedPulse is ambiguous.
- Conclude slightly different IDs _are_ needed
- It would be good to provide enumerated forms, and not use strings (for that way lies madness)
  Suggest maybe an enumeration-like class that could do things like (ignore names, scope -  diddn;'t think too hard about them):

``` C++
// ID is short int; MASK srdd (16 bit). 
// s(4bit)  is reserved for slow/fast.
// r(4bit) is reserved for extensions, normally 0.
// dd(8bit) is for detector ID.  
enum SlowFast_t { DontCare = (0x0 << 12),
  Slow = (0x1 << 12)
  Fast = (0x2 << 12)
};
enum Detector_t { SiL1 = 1,
 SiL2,
 SiR1
 //...
};

struct: ChannelId {
public:
ChannelId(Detector_t det, SlowFast_t sf = DontCare) : fID(det | sf) {}
//String-taking constuctor would be useful too for reading branch names
short SlowFast(){return fID & 0xF000}
short Detector(){return fID & 0x00FF} 

bool operator=();
bool operator<();
// etc if neeeded;
const char* str(); // May need static buffer in implementaion.
//Alternatively have ostream operators (& istream?)
//Be careful about operator const char*, it can be used to form inequalites

private:
UShort_t fID;
}
```
#### Generator like interface

We decided that the nicest interface would be to present python-style generators.
So for instance if I want to loop over all slow AnalysedPulses, I create a little functor(-like) object that is configured to only return slow AnalysedPulses.  Asking this for the next entry will return the relevant `const vector<TAnalysedPulse*>*` until no more fit the bill, then it returns 0x0.  The interface could use a Next() method or possibly overload the prefix ++. This avoids us having to generate temporary containers of vector<XxxPulses>, but allows list-like returns and does not expose our guts. Example interface using prefix ++:

``` C++
SomeFunctor SiL_list("AnalysedPulses", "SiL", "desiredGenerator"); 
// n.b. string literals are placeholders, 
// e.g.  second argument is likely a ChannelID
// There should be defaults for these that correspond to
// 'I don't care, give me everything'

while (( vector<TAnalysedPulse*>* vec = ++SiL_list )){
  //do stuff with vec.
} 
```
#### Temporary lists that do not get saved

This is to answer a use case where a module wants to modify an existing container/branch, and we don't want to save both. Example use case: _we want to re-order the TPulseIslands for a particular detector because they do not appear time ordered in the input_

The navigator can provide a 'temporaries' container-container that does not get written to file at the end of the event.  This could be searched after the normal containers, unless a dedicated search of temporaries is done.
- [**TODO** is this the best logic for search order? Perhaps temporaries first? OR always under user control?]
- [**TODO** does method _N_ do `EventNavigator::AdoptTemporary(...)`, or does method _N+1_ do `EventNavigator::DemoteToTemporaty(...)`?]

**Comment by jrquirk** [comment]
This was so hard to digest I needed to take a Tums after reading. I have a couple of clarification questions. Some are probably redundant, stemming from a fundamental misunderstanding of an earlier part of the post.
- A sub-class is a derived class?
- You say branch-name on file, what is saved to file?
- What is a 'kind of output'?
- You say we know the generator type, then say generator->pulse_type is ambiguous, but I thought each generator make a single kind of pulse?
- How do you propose examining the type of an object in a container?
- What is a python-like generator?
- If an entire vector is of `TXxxPulse*` that are actually `TSpecialiZedXxxPulse`, why store it like that in the first place?
- Won't the user always care which methods were used... We're not grandmothers reading email, we're trying to do analysis
- What does the chain look like? Is it Ben's flow-chart?
- What is config_name? And if this is the structure of the file, doesn't it get rid of the ambiguity mentioned earlier?

We should have that workshop soon...

**Comment by litchfld** [comment]
I'll deal with the polymorphic pulse questions now...

> A sub-class is a derived class?

 Yup.

> What is a 'kind of output'?

In this context it's a particular subclass of a pulse. Here's a concrete example: Suppose we have a couple of generators that return the same additional information, say perhaps gradient at threshold, and we have a class to record that:

``` C++
class TGradientAnalysedPulse: public TAnalysedPulse {
//...
}
```

Then maybe more than one generator produces output in this form.  If two (or more) generators produce the same kind of output, perhaps I want to compare them.  So we might want to be able to find all the containers of TAnalysedPulse\* that are actually pointing to TGradientAnalysedPulse. It's not 100% clear to me that people -would- _should_ want to do that, but i'm not confident enough to rule it out.

> You say we know the generator type, then say generator->pulse_type is ambiguous, but I thought each generator make a single kind of pulse?

Yes it is the other way, pulse_type->generator, that might be ambiguous. See above.

> How do you propose examining the type of an object in a container?

Well something like this:

``` C++
//--- pls ignore dodgy variable names ---
vector<TAnalysedPulse*> vec_anaPulse;
//...
if ( dynamic_cast<TXxxAnalysedPulse*>(vec_anaPulse[0]) ) {
//check for an exact type
}
std::type_info tinf = typeid(vec_anaPulse[0]) // For comparison to something else
```

But it would probably get wrapped up in some user interface if we actually need it a lot

> If an entire vector is of TXxxPulse\* that are actually TSpecialiZedXxxPulse, why store it like that in the first place?

We probably would have to.  Once things are in memory we need a generic way to track and find them at request. The simplest way to achieve this is to have them stored as `map<some_identifier, vector<TAnalysedPulse*> >`, `map<some_identifier, vector<TDetectorPulse*> >`, etc.  It's not impossible to arrange that everything is stored in an exactly correct container, but it's much harder, especially if you don't want to update the navigator each time a new pulse type is added.

**Comment by litchfld** [comment]
PS. Reading this again:

> You say we know the generator type, then say generator->pulse_type is ambiguous, but I thought each generator make a single kind of pulse?

I should add that just because we know what specialised kind of pulse is produced by a particular generator, the program does not, so in some sense it is ambiguous even if there is in truth a 1-to-1 mapping. Unless we ensure there is a discovery mechanism.

**Comment by litchfld** [comment]
>    You say branch-name on file, what is saved to file?

The plan is for each stage of processing is a new TTree; then they can be aligned as friends, or exist independently. (This is what ROOT developers say is the intended mechanism...)
On each tree there are several branches: each detector channel (slow or fast) is a separate branch. So the GE-F banks will be on a particular branch.  In addition it is supposed to be possible to run several generators (max_bin, template, ...) on the same set of data, so the branch must also be identified by the generator that produced it.  Finally, the generators can be configured in different ways, so that must be stored too, which is what `config_name` is for.  Hopefully the generators can provide a ConfigName() method that either pretty prints out their parameters, or returns a nice short descriptive name. 

> What is a python-like generator?

Something like this http://en.wikipedia.org/wiki/Generator_%28computer_science%29  Here a container would probably work, but I want to hide the implementation because I'm not 100% certain a container is appropriate & safe... Pythons xrange vs range are a simple models of the concept.

>  Won't the user always care which methods were used... We're not grandmothers reading email, we're trying to do analysis

Probably.  But not for everything - generating plot 'booklets' for comparison for example. 

>  What does the chain look like? Is it Ben's flow-chart?

I'm not sure exactly what 'Ben's flow-chart' is, but I think so. The idea is that it will be possible to say, process all files with modules for creating TAnalysedPulses, save the result then work only on the output. This is a necessity with large datasets where the conversion of raw data is a time consuming business. It's not so vital for us, but it makes it plausible that everyone could have a local copy of all the data.

>  What is config_name? And if this is the structure of the file, doesn't it get rid of the ambiguity mentioned earlier?

Its the exact configuration of a generator instance, see above.

**Comment by jrquirk** [comment]
Thank you Phil, the clarifications have been helpful.

I remember a discussion at the collaboration meeting about the form of TAnalysedPulse, and what information it would include and how new information should be added at different stages of the analysis. It seems implicit here you guys have decided on saving new information via deriving a new class with the fields you want. Is this right?

**Comment by benkrikler** [comment]
> What does the chain look like? Is it Ben's flow-chart?

Yes, it looks like the chain we were proposing back at Fermilab and before:  Analyse waveforms => (TAPs) => Pair up fast and slow channels => (TDPs) => Make muon events => (TMEs).

**Comment by litchfld** [comment]
> It seems implicit here you guys have decided on saving new information via deriving a new class with the fields you want. Is this right?

Yup.  That seems the most straightforward way to do it.  OO purists object to using `dynamic_cast<>` but i'm not an OO purist. :)  Also a registry (_meaning here: any 'key' => 'value' container that circumvents strong typing_) is very inefficient in C++ so is not good for datum objects.

**Comment by jrquirk** [comment]
That was definitely one of the choice possibilities we discussed. I'm glad it's settled.

Can this issue be closed?
