### ISSUE TITLE
How to specify the data set you want to look at?

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#46]
Hi,

It seems pretty much a given that we will use a few different generators for analysing different banks (e.g. for fast and slow pulses)

But i'm not sure what people actually expect to do? I put a strawman where you get an iterable object that gets AnalysedPulses from SiL `SiL#-S, SiL#-F, etc...)`, produced with a particular generator.

`SomeFunctor SiL_list("AnalysedPulses", "SiL", "desiredGenerator");`

But how to actually create a description of all these? Should it be a text list or vector of enums, or do we need some more complicated logic?  

And does everything need to specify a detector-generator pair? Schematically:
`(SiL1-S && BensCleverGenertaor) || (SiL1-F && AndysAwesomeGenerator)`
or can we use a list of detectors and a list of generators, eg:
`(SiL1-S || SiL1-F) && (BensCleverGenertaor || AndysAwesomeGenerator)`

Or even a mix of the two?  I'd prefer to keep the generators and sources independent, since that's much easier to code, but i don't know if that is good enough. 

Finally do we need to support specifying particular generator configurations?

**Comment by benkrikler** [comment]
I guess you're asking from the point of view of the interface to the functor / python style generator for iterating (we need to get a good name for it, cause it clashes with our pulse generators.  I'm suggesting looper for now )?  I think we go so far with simple specifications for what to loop over (all fast, all slow, all from one generator etc) but finer graining, such as your examples we leave for each user to implement within the loop.

That said, some of this work is related to the ID classes I've started working on. In there, `(SiL1-S || SiL1-F)` is taken care of as type `IDs::channel("SiL1","*")` or `IDs::channel(kSiL1,kAnySlowFast)`.  Similarly to your thinking, I've currently got two separate classes for generators and channels and was now going to write a wrapper class that contains both (probably to be called a `source`). 

I could imagine, that for the first example (and to extend it to larger requests), we pass a vector of sources to the looper which it would then use to serve up all possible pulse lists.  But I think that would be getting carried away at this point. I don't think there're enough use cases to require anything too difficult and we can always extend things when we get there, if we need it.

**Comment by jrquirk** [comment]
@litchfld 

> But how to actually create a description of all these? Should it be a text list or vector of enums, or do we need some more complicated logic?

So you're saying in the implementation, what this object is looping over? I would think a text list is easier than enums because you wouldn't have to recompile the code every time you added a generator. But I'm not entirely sure what "create a description" means.

> `(SiL1-S && BensCleverGenertaor) || (SiL1-F && AndysAwesomeGenerator)`
> `(SiL1-S || SiL1-F) && (BensCleverGenertaor || AndysAwesomeGenerator)`

Will we be treating two different channels on equal footing like that? The only thing I can think of is the thin silicon, but only grouped together if it's the same amplifier (fast or slow) and the same side. And it seems like you've already taken that into account at this point with `SiL1-S`. So that probably answers your question

> But i'm not sure what people actually expect to do?

Also, what's a source?

> I'd prefer to keep the generators and sources independent

@benkrikler 

> we need to get a good name for it

Please God yes. Iterator is fine, looper is fine. Generator is for python and confusing and functor speaks more to the implementation than the actual purpose.

Also, the same question to you about the purpose of or'ing a bunch of banks.

**Comment by benkrikler** [comment]
> Also, what's a source?
> 
> >  I'd prefer to keep the generators and sources independent

In Phill's use of the word source, he's referring to a single detector channel and therefore 1 midas bank.  Perhaps I've confused things by suggesting we actually use source to mean a source of TAPs or TDPs which is a combination of a detector channel with a particular configuration of an AnalysedPulseGenerator or DetectorPulseGenerator.

---

As for naming this mechanism to loop over all sources (source as in my definition just above), iterator is mis-leading, this won't be used as an std container's iterator whereas generator is the correct python terminology, but we're using that already.  Looper's not a great name I admit, but at least it's different..

---

> Also, the same question to you about the purpose of or'ing a bunch of banks.

I'm not sure what question that is... You mean this one:

> Will we be treating two different channels on equal footing like that?

It seems possible to me, though I'm not sure how often it will come up in reality.  If we want to compare the performance of a particular generator is one possible example.

**Comment by litchfld** [comment]
> > Also, what's a source?
> > 
> > > I'd prefer to keep the generators and sources independent
> 
> In Phill's use of the word source, he's referring to a single detector channel and therefore 1 midas bank. Perhaps I've confused things by suggesting we actually use source to mean a source of TAPs or TDPs which is a combination of a detector channel with a particular configuration of an AnalysedPulseGenerator or DetectorPulseGenerator.

No, I like your usage better. I picked up source from the "definitions.h" file, and perhaps I misunderstood the intent.  So _channel_ can mean a single readout channel (so there are one or two per _detector_), and _source_ is the combination of channel and generator.  Works for me, does it make everyone else happy?

**Comment by litchfld** [comment]
> >    `(SiL1-S && BensCleverGenertaor) || (SiL1-F && AndysAwesomeGenerator)`   `(SiL1-S || SiL1-F) && (BensCleverGenertaor || AndysAwesomeGenerator)`
> 
> Will we be treating two different channels on equal footing like that? The only thing I can think of is the thin silicon, but only grouped together if it's the same amplifier (fast or slow) and the same side. And it seems like you've already taken that into account at this point with SiL1-S. So that probably answers your question

I think so. We will probably find that we want to treat most fast channels in one way, most slow channels in another, and a handful of channels as special cases (perhaps they have crazy pile up, or intermediate length pulses, or maybe use a transistor-reset preamp)  They will still always be handled as different banks, but one call could select all the banks a particular generator wanted to work on.

**Comment by litchfld** [comment]
> That said, some of this work is related to the ID classes I've started working on. In there, (SiL1-S || SiL1-F) is taken care of as type IDs::channel("SiL1","*") or IDs::channel(kSiL1,kAnySlowFast). Similarly to your thinking, I've currently got two separate classes for generators and channels and was now going to write a wrapper class that contains both (probably to be called a source). 

Cool, thinking overnight that seemed the best basis for any kind of logical operations. We can probably co-opt that for making masks with if we find the need.  So, we don't have to work it out now, but that answers the basic how of making it extensible.

**Comment by jrquirk** [comment]
@litchfld 

> I think so. We will probably find that we want to treat most fast channels in one way, most slow channels in another...

I think I get this now. So like if we had an extra step to go through for slow pulses that wasn't there for fast pulses.

**Comment by litchfld** [comment]
OK this is pretty much in place with Ben's new ID classes. Further changes are being opened up as new issues.
