### ISSUE TITLE
Template implementaion files

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#47]
Any preference about what we call them?  I'd probably go for .tpl or maybe_tpl.h, but if there is a standard in place i should follow that.

**Comment by jrquirk** [comment]
What is a template implementation file?

**Comment by benkrikler** [comment]
@litchfld, do you mean template as in an example of how to implement something or as in the implementation of a template class (as in `template <typename T>` etc)?

In both situations there is no agreed convention, although in the first case there are 'template' (as in example) modules in the rootana/scripts/templates directory which are used to generate skeleton modules and example code in rootana/src/examples.

If it's the second version, I'm familiar with the Geant4 convention of `.icc` (I suppose the `i` is for inline) but either of your suggestions sound good.

**Comment by litchfld** [comment]
@benkrikler 
Yes in the sense of: 
`C++ template<T> MyClass::DoSummat(const T&)`
I went with '.tpl', since we don't want people naively thinking they should #include the file, and '.cpp' has special meaning to the makefile.  There is a .cpp file that makes 3 real classes from the template, so most people just need to include the header '.h' file, and from there making any new classes from the template is a linker error (a.k.a. coded warning you may be doing something too funky).

**Comment by litchfld** [comment]
@jrquirk 

> What is a template implementation file?

Basically it's the '.cpp' file for a `template<typename T>` class (or function). It gets a bit weird because until you make a real class with an type in place of T the compiler doesn't know what assembly code to generate from the '.cpp' file.

See here for a good explanation:  http://www.parashift.com/c++-faq-lite/templates-defn-vs-decl.html

**Comment by litchfld** [comment]
Okay, looks like I'm making up our conventions as I go along then.  I'll close this, although discussion can continue.
