### ISSUE TITLE
Picture Books Tweaks

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#49]
Hi Everyone!

Put any tweaks (or even removals if you don't want the unnormalised plots) you want made to the picture books here. These are more aesthetic changes that we can do and mean we can remake the picture books without doing another production run. These changes will be made in ROOT macros so I'm sure you'll have some sort of idea as to what's possible and what's frustratingly not.

For the new DAQ plots:
- Threshold plots: Add a minimum on the z-axis (currently 0) so that it is easier to see changes made
- Livetime: Set the z-axis to be 0 to 1 to maintain a visual consistency between datasets (red is good)
- Pedestals: Different z-axis range (log?) because the Ge-F pedestal is overpowering everything else

**Comment by benkrikler** [comment]
We now have the number of entries labelled on each plot which is great, but you could take off the plot name from the statistics box, which is illegible and doesn't add anything aside from clutter.  

Also, I think ROOT has (or had) some funny known bug with the number of entries.  If you use SetBinContents then it would only add on 1 to the number of entries rather than the change in that bin contents.  I'm not sure if we suffer from this, but we should look out for it...

**Comment by AndrewEdmonds11** [comment]
From the source code [here](http://root.cern.ch/root/html534/src/TH1F.cxx.html#INDv2B):

```
void TH1F::SetBinContent(Int_t bin, Double_t content)
{
   // Set bin content
   // see convention for numbering bins in TH1::GetBin
   // In case the bin number is greater than the number of bins and
   // the timedisplay option is set or the kCanRebin bit is set,
   // the number of bins is automatically doubled to accommodate the new bin

   fEntries++;
   fTsumw = 0;
   if (bin < 0) return;
   if (bin >= fNcells-1) {
      if (fXaxis.GetTimeDisplay()) {
         while (bin >=  fNcells-1)  LabelsInflate();
      } else {
         if (!TestBit(kCanRebin)) {
            if (bin == fNcells-1) fArray[bin] = Float_t (content);
            return;
         }
         while (bin >= fNcells-1)  LabelsInflate();
      }
   }
   fArray[bin] = Float_t (content);
}
```

So, it's still there but I don't think this is a major problem and only means we have to be careful how we interpret the number of entries to mean.

If we were putting particles into a histogram and to save time we used SetBinContent(2112, 400) instead of calling Fill(400) each time then that would be a problem if we were expecting the number of entries to be the number of particles.

I can't think clearly what we're expecting the number of entries to be in our plots through but it's something to keep in mind.

I have also just grepped for SetBinContent, AddBinContent and BinContent in src/data_quality and they are only used for the hDQ_DigitizerOverflow_Fraction and hDQ_DigitizerOverflow_FractionByEvent histograms. So I don't _think_ this is a problem...

**Comment by litchfld** [comment]
Arguably that's not a bug, just that it isn't clear what one is using the "histogram" for if calling SetBinContent().  You can fix it by calling SetEntries() after setting all the bins.

**Comment by benkrikler** [comment]
It certainly confused the hell out of me the first time I saw it.  But as long as we're aware of it then there's no issue and it doesn't sound like we use this approach much anyway.

**Comment by AndrewEdmonds11** [comment]
Another thing I think we should add is to put the dataset into the title of the histograms so that it's immediately obvious which one we're looking at

**Comment by AndrewEdmonds11** [comment]
So, this is what I've changed:
     - set the lower limit on the z-axis of the normalised plots to 10^-7
     - set the lower limit on the z-axis of the FADC threshold plots to 1000
     - set the z-axis limit of the DAQLivetime plots go from 0 to 1
     - set the pedestals plot to be log-z
     - taken off plot name from statistics box
     - added dataset to histogram title

I will close this now but reopen if you want something tweaking.

New picture books will be compiled now.

**Comment by AndrewEdmonds11** [comment]
As promised, the new picture books are now on drop box and I've sent the plots to Ben to put on the web page

**Comment by benkrikler** [comment]
New plots are online.... They're looking good Andy and Joe!
