### ISSUE TITLE
Problems with input / output root files

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#5]
Rootana seems to be having difficulties reading in and writing out root files.

No TPIs are being found in the input file and there seems to be issues adding directories to the output file. 

I don't understand what's going wrong so this is purposefully vague.  As I hone in on the issue I'll describe it better...

**Comment by AndrewEdmonds11** [comment]
Is this still on your feature/BK_extend_modules_management or are you having this problem on develop as well?

**Comment by benkrikler** [comment]
The problem seems to be on develop as well.  

I've just pushed a fix which makes sure we check for TPIs before we call a generator.  If no TPIs were there to analyse, the MaxBinAPGenerator would  seg fault on my system, so the only contents of the output file was the AnalysePulses and nothing from ExportPulse.  

Hopefully that should be partially fixed now.  Does it help you?

**Comment by AndrewEdmonds11** [comment]
Nope, it's still trying to write to the tree file on BK_extend_modules_management. And on develop it now just tells me that there were no TPIs for some detectors.

**Comment by benkrikler** [comment]
I've only pushed to develop.  I'm going to fix it there first then merge into the other branch.

The fact it is telling you there are no TPIs is good.  Before it should have been seg faulting or doing other undefined things for you at that point, now at least it's catching it and complaining.  The problem we now need to find is why there are no TPIs for those detectors...

Do you at least see an ExportPulse directory when you run on develop?

**Comment by benkrikler** [comment]
I just checked in my version and I do see an ExportPulse directory and it does contain a histogram of a pulse.  Writing out to the file seems to be ok.  We're also able to read pulses in because I could draw a pulse there.  

Is it possible some detectors really didn't take data on these runs?  I'm using run 3329 to test with.

**Comment by AndrewEdmonds11** [comment]
The reason that there are no TPIs might just be because there were none for that detector for that MIDAS event (for me they are the fast Si channels...).

Yes, I see the ExportPulse directory.

Wasn't there already a check for no TPIs in some of the modules? I'm looking at lines like this in some modules: 

```
// Get the TPIs
thePulseIslands = it->second;
if (thePulseIslands.size() == 0) continue; // no pulses here...
```

Do we need to standardise this?

**Comment by benkrikler** [comment]
Yeah, I just checked properly:

```
List of TPIs for 'SiR2-F' contains 2 pulses.
List of TPIs for 'SiR2-S' contains 4 pulses.
List of TPIs for 'SiR2-F' contains 5 pulses.
List of TPIs for 'SiR2-F' contains 5 pulses.
List of TPIs for 'SiR2-S' contains 3 pulses.
List of TPIs for 'SiR2-F' contains 5 pulses.
List of TPIs for 'SiR2-F' contains 5 pulses.
List of TPIs for 'SiR2-S' was empty
List of TPIs for 'SiR2-F' contains 4 pulses.
List of TPIs for 'SiR2-F' contains 4 pulses.
List of TPIs for 'SiR2-S' contains 5 pulses.
List of TPIs for 'SiR2-F' contains 6 pulses.
List of TPIs for 'SiR2-F' contains 6 pulses.
List of TPIs for 'SiR2-S' contains 7 pulses.
List of TPIs for 'SiR2-F' contains 4 pulses.
```

Some events just don't contain any TPIs....  I think we can close this then..

Every module should have something like you suggest to check they're getting the data they expect.  It might be TPIs, TAPs, TDPs or anything else though, and it's always going to be buried within the code so it might be hard to standardize on a module-by-module basis.  We can however let the Generators off from having to check things by making sure the Module that calls that Generator  does the check for them.  That's what now happens in MakeAnalysedPulses and having learnt my lesson I'll make sure it's the same in MakeDetectorPulses and MakeMuonEvents.
