### ISSUE TITLE
Online trend plots for production 2

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#50]
I've uploaded most of the new trend plots from alcapana production 2.0: 
http://www.hep.ph.ic.ac.uk/~bek07/alcap/trend_plots/production_2/by_detector.shtml

I know it's rough and ready, but I certainly find it helpful for comparing the distributions...
Feel free to log any problems or suggestions here.  I'd welcome all feedback to be honest.

**Comment by jrquirk** [comment]
The only buttons on the left that work for me are the Dataset ones. Detector and Norm do not. It's worth noting that the Detector buttons didn't work in the last iteration either, but I just didn't mention it.

I tried Chromium and Firefox.

**Comment by benkrikler** [comment]
That's weird.  They all work fine for me on firefox.  There was previously a bug with the detectors, but i fixed that and it didn't affect the arrows or the loop buttons.  

Are you sure you're looking at plots that are affected by the detectors and normalisation controls?
You need to scroll down a way now, there's a lot of plots...

**Comment by jrquirk** [comment]
> You need to scroll down a way now, there's a lot of plots...

I guess I am like a grandmother reading email. This was the issue.

**Comment by benkrikler** [comment]
That's cool, thanks for letting me know....

**Comment by benkrikler** [comment]
Andy just gave me the Al50a_without-NDet2 and the SiR2-1pct datasets which are also up now.

**Comment by benkrikler** [comment]
The new Al50b plots have been added.  I'm going to close this, but feel free to add requests or bugs...

**Comment by benkrikler** [comment]
You can use http://www.hep.ph.ic.ac.uk/~bek07/alcap/trend_plots/production_2/one_plot.shtml
To go through one plot at a time, normalised  vs. unormalised
