### ISSUE TITLE
Will all entries be written out?

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#51]
Is it conceivable that we would, after processing an entry, decide not to write it out?  I've been assuming the answer is 'no' on the basis that there are potentially many muon events per entry, but I'd like to confirm that.

**Comment by AndrewEdmonds11** [comment]
Did we ever get an answer for this? (If you can't tell I'm trying to tidy up our issues while rootana is exporting all silicon pulses for me :) )

**Comment by jrquirk** [comment]
I think the answer to the subject line is "yes," at least in our experience so far.

**Comment by AndrewEdmonds11** [comment]
Cool.
