### ISSUE TITLE
TPI Pulse Candidates

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#57]
In the plan in issue #7, we have a function that will take a TPI and try and find any pile up pulses that might mean they need to be treated differently by our TAP generator (for example we will not add it to the template if there is more than one candidate pulse).

In the past we have implemented this in two ways:
- (Mine): be given a TPI\* and return a vector of TPI\* of all the candidates
- (John's): be given a TPI\* and store the start and stop locations of the candidates (correct me if I'm wrong John)

I think the first way would be good because then generators do not need to be changed drastically to use this (they would just need to call the function and have a second loop through the candidates).

However, the second way would be better for speed since you may not want to use the candidates.

So, I've thought of a way to combine the two:
- We have a class called `PulseCandidates` which will contain some sort of array of start and stop locations (in terms of sample number)
- These start and stop locations will be filled when `PulseCandidates` is constructed(?) or when we ask it to
- We can then ask for the number of pulse candidates `int PulseCandidates::GetNPulseCandidates()` or the TPIs themselves `std::vector<TPulseIsland*> PulseCandidates::GetPulseCandidates()`

Does this make sense? Can anyone see any problems? (I should rename one of these pulse candidates)

**Comment by jrquirk** [comment]
This is a good idea.

**Comment by AndrewEdmonds11** [comment]
As of the above commit, this is now implemented. However, there is one thing left to do and that is to work out how to pick values for the "rise" and "fall" parameters for the PulseCandidateFinder.

If the change in the sample value is greater than "rise" then a candidate pulse is started and if the change is greater than "fall" the candidate pulse is stopped. At the moment, they're hard-coded but in John's original code he calculated them based on the pulse:

```
int pPol = gSetup->GetTriggerPolarity(bank);
double pPed = (double)gSetup->GetPedestal(bank);
double pMax = std::pow(2.,(double)(gSetup->GetNBits(bank))) - 1.;
double pThresh = (pPol > 0 ? (pMax - pPed) / 2. : pPed / 2.);
...
std::vector<PrePulse> prepulses = PrePulse::FindPrePulses(pulse, pThresh/2., pThresh/4.);
```

Is this good enough?

**Comment by jrquirk** [comment]
I think half maximum is good. But it's obvious I think that because, well, that's what I did.

There could also be a parameters passed to it from configuration options, percentage of maximum on rise and fall to trigger recording of a candidate? Or the actual sample values themselves?

**Comment by AndrewEdmonds11** [comment]
So to decide what parameter we should use for the rise parameter, I've written a new module called `CandidatePulseFinder_InvestigateParameters` (is there a better name?) that just uses the `CandidatePulseFinder` and plots the difference in the samples.

Here is the plot of the positive differences only from run 2808:
![run2808_sampledifferences](https://cloud.githubusercontent.com/assets/1848575/3228897/c857f938-f08c-11e3-9dbd-a69732681c9a.gif)

There is a clear bump there which I think is for when we have a pulse. Is this correct?

I don't want to spend too long on this at the moment so I think that, for the time being, if we just have a "rise" parameter and remove the "fall" parameter. Then just have the end of the pulse being when samples go below pedestal.

The only effect of this is that we don't get pulses that have overlapped but we can look into that later.

**Comment by AndrewEdmonds11** [comment]
From this plot I've selected pulse candidates if the "rise" is greater than 300. I've then exported TPIs that have 0, 1 or greater than 1 pulse candidate found in the first event of run 2808.

For greater than 1 pulse candidate: only 1 out of the 5 TPIs actually had more than one pulse
For 1 candidate pulses: everything seems OK but I didn't check every pulse
For 0 candidate pulses: we find there are a lot of pulses being thrown out (e.g. Ge-S where it rises slowly and no two samples are separated by 300 ADC counts or when the total peak is less than 300 ADC counts)

There are two options here:
- move to just looking at the absolute height above pedestal of the sample
- see if we can specify a "rise" parameter on a channel by channel basis by making the above plot but splitting up the channels

**Comment by AndrewEdmonds11** [comment]
Using the code in this commit (729a3169ea1b0ff9ae3d650a6586204f1f608ed6), I plotted the above difference plot on a channel by channel basis and found that this lump can only really be seen in the muSc channel and there are no lumps in the others.

This could just be because there aren't enough TPIs in one run to see it but I will move to using the absolute height above pedestal instead

**Comment by litchfld** [comment]
We just discussed this upstairs, but here for posterity:
- I think an absolute rise from pedestal (threshold cut) would probably work better than a difference between two adjacent bins, which is effectively a gradient.  Slow pulses inevitably will have a lower gradient than fast or scintillator pulses.  That said, I'd imagine a 2D cut using both gradient and threshold could be more powerful, but perhaps that is more work than you need.
- I wonder if a cut at 1/2-way to saturation (half maximum) is too high for a threshold cut.  The top 20% or so of an ADC's range is often a bit non-linear so taking only pulses that go over half-max might produce a noticeable shape bias. 
- This almost certainly needs to be tuned on a channel by channel (or at least groups of channels) basis.  The gradient on a fast pulse will be very different than for a slow pulse, and the best absolute thresholds will depend on the charge deposited and amplifier gains, which will likely vary between detectors.

**Comment by jrquirk** [comment]
@AndrewEdmonds11 

> there are no lumps in the others

The muSc had the most consistent energy deposition of any of the detectors. Only muons and electrons with a tight momentum spread went through it. Since you're looking at the gradient, the actual pulse height will have an effect, and all other pulses have a spread of pulse heights and therefore a spread of gradients. Only the muSc, muScA, and SiR when in target position you can expect to have lumps from that logic.

> (e.g. Ge-S where it rises slowly and no two samples are separated by 300 ADC counts or when the total peak is less than 300 ADC counts)

This is a conversation about candidate pulses which initially came up in the context of template fitting, so let me take this time to point out, while scintillator pulses might be great for template fitting because they have a time constant or two characterizing them and a consistent shape, the Ge-S shape may have more parameters, some based on actual physics. The position of where the gamma strikes in the detector can change the shape of the pulse, for instance, so whether or not a template is a good idea for the Ge-S pulses is less obvious, and PulseCandidates may be created with different methods by the same reasoning.

@litchfld 

> I think an absolute rise from pedestal (threshold cut) would probably work better than a difference between two adjacent bins, which is effectively a gradient. Slow pulses inevitably will have a lower gradient than fast or scintillator pulses.

This may be the case, but why do you think that? Why would how a slow channel works effect how we find pulses in a fast channel? If we actually care enough to choose the right method we should take a run and see which pulses get correctly tagged and which get missed. I chose the gradient because I was looking at the muSc scintillator and was wary of pile-up since it was a hot channel. For other channels, like a silicon fast channel, I would agree because we haven't seen much pileup in those (if we get a signal at all). But again, we'd have to look to be confident.

> I wonder if a cut at 1/2-way to saturation (half maximum) is too high for a threshold cut. The top 20% or so of an ADC's range is often a bit non-linear so taking only pulses that go over half-max might produce a noticeable shape bias.

We can choose other regions, like 50%-80%, or 30%-70%, or whatever. I've never heard of this non-linearity, but we can try erring on the side of caution. We can also email Fred Gray to ask about the FADCs and CAEN about the CAENs.

**Comment by AndrewEdmonds11** [comment]
So my naive thinking was that finding more than one pulse on an island was independent of the channel we are looking at and so we can have one PulseCandidateFinder class that can be used by all generators that want it. 

Have I been thinking wrong and that this cannot be generalised?

**Comment by jrquirk** [comment]
Identifying a pulse candidate is a different beast for all channels maybe, but just the parameters and method used for finding it. The rise and fall parameters can be set, and if people want to use the derivative method you can just write the code for identifying a pulse that passes a threshold and then there can be a call to take the derivative of a pulse before using this same method.

Does that make sense? What I mean is that I think the generalization is fine.

**Comment by AndrewEdmonds11** [comment]
You mean you think "the generalisation is fine" in the sense that it's OK to have it in one class?

In my mind, finding peaks is quite standard but now I've just realised that knowing how many samples to take before and after _would_ be shape specific.

**Comment by jrquirk** [comment]
Yes, I think having everything in one class is good.

And yes, it will be shape specific. But you can account for that. I don't completely understand why these are conflicting ideas.

**Comment by AndrewEdmonds11** [comment]
It's not that they're conflicting ideas, it's just that I hadn't thought about it before.

So in `PulseCandidateFinder` we'll need different algorithms for:
- fast pulses
- slow pulses

which will be the deriviative and absolute values that we've talked about. But then there would be different rise and fall parameters for each individual channel.

Ok, so here's a plan:

``` c++
PulseCandidateFinder::PulseCandidateFinder(TPulseIsland* pulse): fPulseIsland(pulse) {
   std::string bankname = fPulseIsland->GetBankName();

  if (bankname == "Ge-S") { // I'm guessing that the EventNavigator will have a nice way of knowing what the channels are called so we don't have to hard-code every single one
    FindPulseCandidates_Slow(value_1, value_2);
  }
  else if (bankname == "Ge-F") {
    FindPulseCandidates_Fast(value_1, value_2);
  }
  // etc...
}
```

Does this make sense?

**Comment by jrquirk** [comment]
That makes perfect sense. Additionally, it looks like a good way to do it.

**Comment by litchfld** [comment]
> >    I think an absolute rise from pedestal (threshold cut) would probably work better than a difference between two adjacent bins, which is effectively a gradient. Slow pulses inevitably will have a lower gradient than fast or scintillator pulses.
> 
> This may be the case, but why do you think that? Why would how a slow channel works effect how we find pulses in a fast channel? 

Because I thought the slow channels were tuned to have more samples per pulse, and the typical height is pretty much fixed by the bit depth of the ADC.  I guess it's not certain but the example pulses Andy was showing me seemed to fit that assumption. 

> I chose the gradient because I was looking at the muSc scintillator and was wary of pile-up since it was a hot channel.

Err... now i'm confused. I though you used the threshold method Andy gave in that code snippet?

**Comment by benkrikler** [comment]
I was about to post this cause I thought you were looking at just identifying fast and slow channels in the `if...else if... else` block but then I realised that you're setting values for each channel.

Still, for publicity of these classes I'm going to post it:

You can use the recent `channel` ID class to do this without the massive if else block you're building.The following code block would achieve the same thing:

``` c++
IDs::channel aChannel = fPulseIsland->GetBankName();
if (aChannel==IDs::Fast) {
/* do something*/
} else if( aChannel==IDs::Slow){
/* do something else*/
} else {
/*currently nothing should reach here if you're dealing with TPIs*/
}
```

Given what you're actually trying to do (and mainly still for publicity), you can also use the class to use a switch block, which would probably be more performant if this is sitting the main event loop:

``` c++
IDs::channel aChannel = fPulseIsland->GetBankName();
switch(aChannel.GetDetectorEnum()){
   case kGe:
      /*...do something ...*/
      break;
   case kSiR1_1:
      /*...do something ...*/
      break;
   /*...etc ...*/
}
```

**Comment by AndrewEdmonds11** [comment]
Thanks, Ben. I knew there was something like that flying around so it's good to see how it works.

For the DetectorEnum, does it differentiate between Ge-F and Ge-S? Or will I have to combine it with the IDs::Fast and IDs::Slow?

**Comment by benkrikler** [comment]
Oh yeah, I forgot that part.  The detector enum just does the detector part so you would need another nested section I guess, that might make this approach less pleasant after all (@litchfield, could we reimplement things to avoid this?).

The `channel` class has a second enum for fast and slow which you would use in a similar way to the above detector switch blosk.  Alternatively just use the `if(aChannel==IDs::Fast){...}else{...}`  construct from above.

Another point:  Are you writing the module to receive these values from the Modules file?  I'd set defaults in the code, but allow the option to play with them in the config file.

**Comment by jrquirk** [comment]
@litchfld 

> Err... now i'm confused. I though you used the threshold method Andy gave in that code snippet?

I think I used the gradient method. But I had used a few. I also used two different threshold methods. One was a constant threshold up and down, another was a constant threshold on the rise, but a constant fraction threshold on the fall. You can see it [here](https://github.com/alcap-org/AlcapDAQ/blob/feature/JQ_template_pulse_fitting/analyzer/rootana/src/PrePulse.cpp) (it's a small, simple file; the enumerated FindMethods are what I want to draw attentions to).

**Comment by AndrewEdmonds11** [comment]
Ok, so this is now implemented but the only thing needed is to select the parameters for each detector which I will open a new issue for.

I will merge this branch (feature/new_template_tap_generator) into develop and start a new one for each individual object/module I add so that I don't get too far behind develop.

This feature adds the following:
- PulseCandidateFinder - the class we use to find candidate pulses on a TPI. This can be used by any generator in the following way:

``` c++
// Loop through all the pulses
for (PulseIslandList::iterator pulseIter = thePulseIslands.begin(); pulseIter != thePulseIslands.end(); ++pulseIter) {
  // Create the pulse candidate finder and find the pulse candidates on this pulse island
  PulseCandidateFinder* pulse_candidate_finder = new PulseCandidateFinder(*pulseIter);

  // At the moment you can get the number of candidate pulses or the pulses themselves as TPIs
  int n_candidates = pulse_candidate_finder->GetNPulseCandidates();
  std::vector<TPulseIsland*> pulse_candidates = pulse_candidate_finder->GetPulseCandidates();
}
```

There are currently two algorithms used:
- one for slow pulses (looks to see if a sample goes above a certain value)
- one for fast pulses (looks for a sudden rise in sample value)

Other things that will be merged in are:
- PulseCandidateFinder_InvestigateParameters - a module we can use to plot the parameters used in the above algorithms to decide which cuts to make
- TemplateArchive - a class that handles reading TH1Fs to and from the template file (pretty much complete)
- TemplateCreator - a module that will create our templates. This is still in development but, at the moment, it just uses the PulseCandidateFinder on each pulse and exports (via ExportPulse) any that have 0 pulse candidates.
