### ISSUE TITLE
Missing Al50(b) Run (3731)

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#58]
Hi @thnam and @benkrikler 

While looking into this odd DAQ livetime greater than 1 problem in the Al50(b) picture book I noticed that there's a missing run in the final tranche (run 3731).

You both ran part 2 of this dataset and neither of you seem to have it. Do we know what happened?

**Comment by benkrikler** [comment]
I've just had a look and there's no tree or hist file.  It's definitely within the run range from the Al50b_pt2 though.  There's no log files either so it seems it never went to the batch system even....

**Comment by benkrikler** [comment]
Same story in Nam's directory...

**Comment by AndrewEdmonds11** [comment]
So from issue #59, I think the problem is that there isn't a MIDAS file because there was a CAEN crash. Although, I haven't check the archive yet

**Comment by benkrikler** [comment]
I tried to just run on 3731 and got this error from the batch script:

```
Downloading run 3731...
--2014-06-05 13:40:14--  ftp://archivftp.psi.ch/mu2e/run2013/run03731.mid
           => “run03731.mid”
Resolving archivftp.psi.ch... 192.33.120.36
Connecting to archivftp.psi.ch|192.33.120.36|:21... connected.
Logging in as mucap ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /archiv/project/mucap/mu2e/run2013 ... done.
==> SIZE run03731.mid ... done.
==> PASV ... done.    ==> RETR run03731.mid ... 
No such file “run03731.mid”.
```

What you're saying about #59 seems correct...

**Comment by jrquirk** [comment]
It's missing from the archive definitely

![missing_file](https://cloud.githubusercontent.com/assets/5143258/3333879/3a338d52-f7f8-11e3-877d-9e25873346c4.png)

I'll check with Peter et. al.

**Comment by jrquirk** [comment]
The run doesn't exist.

> Hi John,
> 
> Peter has passed on the request for file from the alcap data disk. I have mounted it in a machine at UW, but unfortunately not our webserver, where alcap folks have ssh access. I can arrange for this, but in the end it's probably better to have the files hosted on the PSI archive or some other dedicated file server. For now, I've attached a text file that lists the contents of the disk (ls -l \* in the root directory). Feel free to ask me to stage individual files until I can see about mounting the disk publicly. 
> 
> You'll notice that run03731.mid is missing from this disk- I guess maybe that run # got skipped over by the DAQ.
> 
> Michael
