### ISSUE TITLE
What is PulseID in ExportPulse::AddToExportList()?

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#61]
@benkrikler, what is the PulseID that we are supposed to give to ExportPulse::AddToExportList? Is it just the position of the pulse in the vector?

**Comment by benkrikler** [comment]
Yeah, although if #53 ever get's resolved that may change.

**Comment by AndrewEdmonds11** [comment]
Ok, so it doesn't seem to be saving anything to the output file. Am I doing something wrong? This is in a loop through some TPulseIslands. It compiles and runs fine but there's no pulses plotted in the output.

```
ExportPulse::Instance()->AddToExportList(detname, pulseIter - thePulseIslands.begin());
```

**Comment by benkrikler** [comment]
Are you running with ExportPulse in the module file?  And are you checking in the ExportPulse directory of the root file?

Also, what's the value of detname?

**Comment by AndrewEdmonds11** [comment]
Yes, it's in the module file:

```
export_pulse = ExportPulse
```

Does it need it's own section?

Yes, I'm looking in the ExportPulse directory of the ROOT file.

I get detname from TSetupData when I'm looping through the banks.

**Comment by benkrikler** [comment]
No it doesn't need a section of it's own.  

I'll double check that it works ok for me then.

**Comment by benkrikler** [comment]
I've added the following code to MaxBinAPGenerator.cpp at line 37:

``` cpp
      if(ExportPulse::Instance()){
         ExportPulse::Instance()->AddToExportList(GetChannel(),1);
      }
```

Then when I run with `debug=all`, I get the following outptut:

```
Plotting pulse 1 for event 1, detector 'SiR2-F' [Pulse_Nb81_SiR2-F_1_1]
Plotting pulse 1 for event 1, detector 'SiR2-S' [Pulse_Nb80_SiR2-S_1_1]
Plotting pulse 2 for event 1, detector 'SiR2-S' [Pulse_Nb80_SiR2-S_1_2]
Plotting pulse 1 for event 2, detector 'SiR2-F' [Pulse_Nb81_SiR2-F_2_1]
Plotting pulse 1 for event 2, detector 'SiR2-S' [Pulse_Nb80_SiR2-S_2_1]
Plotting pulse 1 for event 3, detector 'SiR2-F' [Pulse_Nb81_SiR2-F_3_1]
Plotting pulse 1 for event 3, detector 'SiR2-S' [Pulse_Nb80_SiR2-S_3_1]
Plotting pulse 1 for event 4, detector 'SiR2-F' [Pulse_Nb81_SiR2-F_4_1]
Plotting pulse 1 for event 4, detector 'SiR2-S' [Pulse_Nb80_SiR2-S_4_1]
Plotting pulse 1 for event 5, detector 'SiR2-F' [Pulse_Nb81_SiR2-F_5_1]
Skipping out of range pulse: 1 on detector 'SiR2-S
Plotting pulse 1 for event 6, detector 'SiR2-F' [Pulse_Nb81_SiR2-F_6_1]
Plotting pulse 1 for event 6, detector 'SiR2-S' [Pulse_Nb80_SiR2-S_6_1]
Plotting pulse 1 for event 7, detector 'SiR2-F' [Pulse_Nb81_SiR2-F_7_1]
Plotting pulse 1 for event 7, detector 'SiR2-S' [Pulse_Nb80_SiR2-S_7_1]
Plotting pulse 1 for event 8, detector 'SiR2-F' [Pulse_Nb81_SiR2-F_8_1]
Plotting pulse 1 for event 8, detector 'SiR2-S' [Pulse_Nb80_SiR2-S_8_1]
Plotting pulse 1 for event 9, detector 'SiR2-F' [Pulse_Nb81_SiR2-F_9_1]
Plotting pulse 1 for event 9, detector 'SiR2-S' [Pulse_Nb80_SiR2-S_9_1]
```

And If I open the root file and change into ExportPulse I see the histograms.

Can you try this and see what you get?

**Comment by benkrikler** [comment]
And whilst I don't have the documentation up on the wiki for these parts yet, I'll make a few comments here:
- You should always check ExportPulse::Instance() isn't returning NULL.  Your code above will seg fault if you take ExportPulse out of the module file.
- All TVAnalysedPulseGenerators know what channel they are analysing.  You can get this string with the `GetChannel()` member method of the pulse generator.

**Comment by AndrewEdmonds11** [comment]
So I don't have GetChannel() since I started the branch a few days ago. I changed it to specify "Ge-F" and it didn't work. 

I'll rebase now and see if it's something like that which is the problem.

**Comment by AndrewEdmonds11** [comment]
After rebasing and only running MakeAnalysedPulses and ExportPulse and adding your code. It still doesn't work.

I also tried moving the ExportPulse line above all the other modules in the modules file.

**Comment by benkrikler** [comment]
Can you push your branch so I can take a look?

**Comment by benkrikler** [comment]
If I replace GetChannel() with "Ge-F" in my code I can see everything fine, so I'm not sure what the difference between our code is.

**Comment by AndrewEdmonds11** [comment]
So I've just pushed. It's the feature/new_template_tap_generator branch

**Comment by benkrikler** [comment]
And what file am I looking at and where?

**Comment by AndrewEdmonds11** [comment]
Well, I'm just running your change. So MaxBinAPGenerator.cpp

**Comment by AndrewEdmonds11** [comment]
Oh and this is my modules file:

``` cfg
## AN EXAMPLE CONFIG MODULES FILE ##
# comments start with a hash (#) and blank lines are ignored
# comments that occur after an option and on the same line give undefined behaviour (may or may not work)

#### start of global options ######
# Options given before a section header are considered 'global' and are
# treated directly by the modules manager

# the 'debug' option makes the modules parser output extra info.
# if 'debug=all' is given then every module is passed the 'debug' option
debug=all
#### end of global options ######

#### start of modules list ######
# The MODULES section must exist and should contain a list of all the modules we want to run with
# This section is handled slightly differently to the others as the option key
# gives an alias for the module that can then be used later on in this file.
# The value (the word after the equals sign) is then the module to actually
# use (ie. the class name for the implementation of that module).
# You can give arguments directy after the class name (if the module supports
# it) or else give options in a section that starts with that modules alias
# Using aliases means we can have multiple instance of a module
[ MODULES ]
#template_creator = TemplateCreator
analyse_pulses = MakeAnalysedPulses
detector_pulses = MakeDetectorPulses
export_pulse = ExportPulse
#### end of modules list ######

####### begin of module specific options ######
# each subsequent section lists the options for each module named above

[ analyse_pulses ]
# specify the channels to analyse as a whitespace separated list.  If the word
# 'all' appears in the list, the list is left blank or the option not given
# at all then all channels are analysed.
analyse_channels=all
#analyse_channels=SiR2-S SiR2-F
# You can provide a default generator to use for fast and slow channels
default_fast_generator=MaxBin
default_slow_generator=MaxBin
# If you want to request a specific type of generator for a channel then give
# the channel name as the key and the generator as the value
#muSc=Template

# if a section is given but the name doesnt correspond to a module, then its
# contents is ignored.  This means long modules lists can have modules
# commented out easily and the rest of the file can be left alone
[ignored_section]
# options are formed by key-value pairs, separated by an equals sign.
option3=8

####### end of module specific options ######
```

**Comment by benkrikler** [comment]
So I've checked out your branch, compiled and used the config file you've posted and I see things working correctly.

I'll try again with a full make clean; make, but I'm not sure how to help if I can't reproduce the problem.. Can you post the output you get maybe?

**Comment by benkrikler** [comment]
I can confirm that after rebuilding everything, it's all working fine for me.  I tend to use -n 10 to allow me to quickly just check with 10 events.  I've switched it off and things still look ok.

**Comment by AndrewEdmonds11** [comment]
So after a bit of couting everywhere. It seems that it's getting to the AddToExportList function but not MakePlot.

However, at the moment, I just run for one event for testing:
`./rootana -n 1 -m andyModule.txt -i /unix/muons/alcap/data/tree/tree02808.root -o output.root`
but when I run for two events it's fine.

Does that make things clearer?

**Comment by benkrikler** [comment]
Great! We're getting somewhere.  So this does seem to be a bug and I'm able to reproduce it.

My guess is there's a problem with the loop logic, but I'll need to check...

**Comment by benkrikler** [comment]
I think this is solved. The trouble was that we looped over modules in alphabetical order, so ExportPulse ran before the other ones had run, and with the subsequent event loaded in place.  Now we follow the order specified in the config file.

 Could you double check for me that this works and then we can close this?

**Comment by AndrewEdmonds11** [comment]
Yep, as of this rebase (8792195759ea7a26f59ff1c569661e259686c42c), rootana now exports pulses if you use one event.

Thanks, Ben.
