### ISSUE TITLE
Normalise Y-Axis of IslandCounter

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#65]
In my notes from today's meeting I've written: "BU Island Lengths - Normalise y-axis". Looking at this plot, I can't remember why:
![hdq_islandlength_musc_cabu_normalised_trendplot](https://cloud.githubusercontent.com/assets/1848575/3203475/43446c88-ed9c-11e3-88a9-af9f32575a71.png)

I thought it was because we were worried that drops in the muon beam might be showing up but I can't work it if this is the right plot.

**Comment by jrquirk** [comment]
It was the number of TPIs plot, not the length plot

**Comment by jrquirk** [comment]
The Y-Axis would need to be normalized to the muon rate, maybe not just the number of muons. If all the runs are the same length timewise it doesn't make a difference.

**Comment by benkrikler** [comment]
Maybe you meant for the UH length plots with the germanium which had different y-axes between normalised and un-normalised versions?

**Comment by AndrewEdmonds11** [comment]
Yes, it was the number of TPIs. Thanks, John.

Ben, the problem you're talking about is issue #43, I think

**Comment by AndrewEdmonds11** [comment]
So, to clarify, it's the y-axis of this trend plot (i.e. the x-axis of the individual run plot) that needs changing.

![hdq_islandcounter_musc_cabu_normalised_trendplot](https://cloud.githubusercontent.com/assets/1848575/3214427/9b5db76c-efae-11e3-849b-d1764d3bb901.png)

**Comment by AndrewEdmonds11** [comment]
This one was quite difficult to do because there's not a simple Scale() function for the x-axis, so I had to go the round about way and fill in a new histogram with the scaled values. This means we now have three histograms, one with no normalisation, one with the y-axis normalised and one with both axes normalised.
