### ISSUE TITLE
ExportPulse exporting two copies of pulses and pulses that weren't requested

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#66]
I wrote a module with the following ProcessEntry

```
int PlotLongGeSPulses::ProcessEntry(TGlobalData* gData,TSetupData *setup){
  std::map<std::string, std::vector<TPulseIsland*> >& TPIMap = gData->fPulseIslandToChannelMap;

  for (std::map<std::string, std::vector<TPulseIsland*> >::iterator i = TPIMap.begin(); i != TPIMap.end(); ++i) {
    // Slow and fast pulses for the Germanium should be exactly the same, so we'll just look through the slow
    if (setup->GetDetectorName(i->first) == "Ge-S") {
      std::vector<TPulseIsland*>& TPIs= i->second;
      for (unsigned int j = 0; j < TPIs.size(); ++j) {
    // Only look at long islands
    if (TPIs[j]->GetPulseLength() > 5000) {
      if (ExportPulse::Instance()) {
        ExportPulse::Instance()->AddToExportList("Ge-S", j);
        ExportPulse::Instance()->AddToExportList("Ge-F", j);
      }
    }
      }
    }
  }
  return 0;
}
```

The goal is look at just the long pulses in the germanium. The good news is that at least some of the long pulses are getting saved, if not all of them. There are two issues

![multi_saves_and_length](https://cloud.githubusercontent.com/assets/5143258/3205039/04fc7c62-edb1-11e3-95d1-d1b684ee93a7.png)

On the left you can see two saves of each pulse. On the right you'll notice the pulse length (of a slow pulse; which is the condition in our loop) is markedly less than 5000.

I'm working on the feature branch JQ_tries_to_export_some_pulses. The command I'm running is

```
./rootana -i ~/data/tree/tree02900.root -o out02900.root -m src/makeGePulses.txt -n 100
```

**Comment by benkrikler** [comment]
I think this is solved.  Could you double check for me and then we can close this?

**Comment by jrquirk** [comment]
Works great! Thank you.
