### ISSUE TITLE
Agree on TAP contents

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#70]
We've discussed this before but I want to nail down what a TAP will really contain.  

The general approach is now finalised, so to extend whatever we agree here we would expect derived classes of TAPs to be written which would contain generator specific values.  This issue is just to agree the fundamental properties we consider all TAPs will want.

Current data members of a TAP are:
- Amplitude
- Time
- Integral
- Energy
- Channel name
- Algorithm
- ID for the parent TPI

I'm in favour of removing the Channel name and Algorithm fields as this information will now be contained in the head of each list (as the key in the map containing the pulse list).

Things I can see that we may want to add:
- Pedestal
- Trigger timestamp
- Length of original TPI

Is there anything else we can think of that's independent of the generator used to make the TAP?

**Comment by AndrewEdmonds11** [comment]
So I guess the criteria for adding things are that they are common to all channels and that there is one obvious definition that we can use as a base.

I think pedestal and length qualify for these. But is trigger timestamp something that is defined for FADCs? For the CAENs, if I've understood everything we've seen so far, it is just the timestamp we are given.

Also, this brings the question of how people writing generators can specify only filling some of these contents. e.g. For the template TAP generator, I'd be happy having the length being defined elsewhere without me needing to worry about it

**Comment by jrquirk** [comment]
Trigger Time Stamp for the CAENs is shifted in the process raw. The TimeStamp now corresponds to the tick of the first bin (give-or-take a bin for the BU CAEN whose trigger clock has some uncertainty). But the timestamp is useful for pairing up the fast and slow germanium pulses into detector pulses when they were both on the UH CAEN since they will have _exactly_ the same timestamp. But this might be specific to whichever generators are used for them.

> Also, this brings the question of how people writing generators can specify only filling some of these contents

Are we going to have default out-of-range values, like -99999? We've talked on this before, but I can't remember what was said.

> - Channel name

Detector or MIDAS bank? The detector name is useful, but that's probably what you mean since you say it'll be at the head of each list. The MIDAS bank will be useful sometimes, but if we can access the TPI via it's ID that should be okay. Same thing with other values stored in the TPI I think.

The values look good.

**Comment by AndrewEdmonds11** [comment]
So the timestamp we will now store in the TAP is the timestamp of the first sample in the TPI? Then I'm fine with adding it with the others.

**Comment by benkrikler** [comment]
Ok, thanks for clearing that up John.  I'll include a Trigger Timestamp field. 

> > - Channel name
> 
> Detector or MIDAS bank? 

So to be clear, when we say a channel in rootana, we're referring to a specific detector channel, such as SiR1_1-F, Ge-S or ScR.  We'll always be able to retrieve what midas bank that detector corresponded to, either through TSetupData or hopefully it's successor from somewhere in the event navigator.  Although you could go that way, you would not need to know the parent TPI to find the midas bank that resulted in a given TAP because the list of TAPs itself is identified by the Channel (and the generator). 

@AndrewEdmonds11:

>    Also, this brings the question of how people writing generators can specify only filling some of these contents

So I've been thinking about this for a while.  If we have physically meaningless default values for TAPs and known which TPI they each came from, then writing some method to copy over TPI values to the TAP would not be too difficult. But that still requires you to identify every TAP with the parent TPI that it came from.  There are a number of ways I could do something like this, but at the moment it's down to each generator to implement.  

Some possible solutions:
**Option 1.** Change the generators' main method `ProcessPulses(const PulseIslandList& input, AnalysedPulseList& output)` to be `ProcessPulse(const TPulseIsland* input, AnalysedPulseList& output)`.  At the moment, the generator is given the vector of all TPIs in the current event for that generator and should return a vector of the TAPs that it reconstructs.  The calling function would not, in general, be able to know which TAP came from which TPI automatically.  If we instead give one TPI at a time to a generator, then the calling function can set values for all TAPs coming out of it (such as parent TPI id, trigger timestamp, TPI length etc).
- Pros: Much simpler interface, less work for people writing Generators
- Cons: Change existing code.  Also, would any generators need more than one TPI at a time? Possibly an extra copying of a vector which could slow us down a bit.

**Option 2.**  We write a method like `CopyParentTPIValues(const TPI* parent, TAP* child)` which a generator calls after finding a TAP.  It would then set all TPI values for the TAP, (such as parent TPI id, trigger timestamp, TPI length etc).
- Pros: Not copying of vectors, keeps existing generator code as is.
- Cons: Need to guarantee each generator calls this method in the right place. 

I think my preference is for option 2.  What does everyone else think?

Of course, this only fills values obtainable directly from the TPI.  If your generator cannot produce a reconstructed value ( like how MaxBin doesn't find an integral), then that's another story and these solutions wouldn't help.  It also ties into:

@jrquirk:

> Are we going to have default out-of-range values, like -99999? We've talked on this before, but I can't remember what was said.

It's definitely a good idea.  Something nonsensical like -99999 so we can easily cut these pulses from any distributions.  For use in code, we can also add methods such as  `anAnalysedPulse->AmplitudeIsSet()` which returns bool if the TAP's amplitude is equal to this value.  That would protect us in case we change this value in future...

**Comment by benkrikler** [comment]
I've started to implement these changes.  We only have ints and doubles now that the channel name and generator have gone so I'm using a single default value of -999 for all fields.

The final list of data fields is:

``` cpp
  int fParentTPI;                                                       
  int fTPILength;                                                                  
  double fAmplitude;                                                               
  double fTime;                                                                    
  double fIntegral;                                                                
  double fEnergy;                                                                  
  double fPedestal;                                                                
  double fTriggerTime;
```

There are enough properties now though, that I'm only providing a default constructor and then getters and setters to each one, plus a `IsXXXSet()` method to return true if XXX is something other than the defaultValue, which allows us to change that value or provide different ones for each field without breaking analysis.

**Comment by litchfld** [comment]
> ... I'm using a single default value of -999 for all fields. 

Seems OK. Just to check: will things like amplitude be calibrated to be always positive? 

> Option 2. We write a method like `CopyParentTPIValues(const TPI* parent, TAP* child)` which a generator calls after finding a TAP. It would then set all TPI values for the TAP, (such as parent TPI id, trigger timestamp, TPI length etc).

That seems better to me. Could that method just be the normal TAP constructor? eg:

``` C++
TAnalysedPulse my_pulse* = new TAnalysedPulse(TPulseIsland* parent); //fills everyhing it can, sets other fields to default value. 
my_pulse->SetBlah(blah);
// ...blah blah...
// ...blah...
working_vector_of_TAPs.append_somehow(my_pulse);
```

**Comment by benkrikler** [comment]
> Seems OK. Just to check: will things like amplitude be calibrated to be always positive?

That's a convention we hadn't discussed before and I had not been working with.  It might make sense but I think sticking with the original polarity would make our interpretations easier.  Do others agree?  Do you mean though that we should increase -999 to be a larger offset?  I'll go with John's original -99999.

> Could that method just be the normal TAP constructor?

Well that sounds like a no-brainer!  Sorted then.  It would need a slightly different signature to your suggestion though, cause we cant get the TPI ID from the pulse on it's own (I just realised I made the same suggestion in my example for option 2, I think that's why option 1 originally appealed.  Being able to write functions like that is what motivated me to start issue #53 ).

Final form:

``` cpp
TAnalysedPulse my_pulse* = new TAnalysedPulse(int parentID, TPulseIsland* parent); 
my_pulse->SetBlah(blah);
// ...blah...
working_vector_of_TAPs.append_somehow(my_pulse)
```

**Comment by litchfld** [comment]
> > Seems OK. Just to check: will things like amplitude be calibrated to be always positive?
> 
> That's a convention we hadn't discussed before and I had not been working with. It might make sense but I think sticking with the original polarity would make our interpretations easier. Do others agree? Do you mean though that we should increase -999 to be a larger offset? I'll go with John's original -99999.

Yup, that's the issue. minus-(however many 9's take us out of the range of any ADC). Perhaps 4 is enough as well, do we have any fancy ADCs with more than 13 bits?

**Comment by AndrewEdmonds11** [comment]
I think the UH CAEN had 14 bits.

**Comment by thnam** [comment]
Yes, that is a CAEN V1724.

**Comment by benkrikler** [comment]
So I'll use -99999 which will cover everything (nods to John).  

I've just seen that TPulseIslands will only give the trigger stamp in clock ticks not in real time.  I can use the TPI's `GetClockTickInNs` methods to convert it, but that's implemented by going to TSetupData.  For now that's all I can do, but long term, should this be coming through the event navigator?

**Comment by benkrikler** [comment]
I'm going to make a bit of an executive call and put back the channel identifier field.  Sort of.  I'm going to actually add an `IDs::source` field. Probably.  Doing this gives us much more flexibility in our designs of interfaces and algorithms.

For instance, having removed the `fDetector` name  field (and corresponding getters and setters) Phill's [pulse correlation algorithm](http://alcap-org.github.io/doxygen/AlcapDAQ/develop/classMaxTimeDiffDPGenerator.html#a41bd22b57ce0b05f03e476e9e526e001) becomes much more complicated if we're to keep it general as it was designed. 

It also means in ExportPulses, where we store a list of TAnalysedPulses coming from any particular source in no particular order, I can make both my life and the users life much simpler because we only need to manage a single object and not something else to provide the extra information that helps identify this pulse.

I'm aware of arguments not to do this: mainly from the extra memory variables such as a string can take, whilst all TAPs within one list will all have the same value.   If we feel that this is a problem, then I would plan to take inspiration from the [flyweight pattern](https://en.wikipedia.org/wiki/Flyweight_pattern) and add a static hash table which maps an int to a a particular `ID::source`.  In reality then, what I would add is another int to the TAP class which should not be a headache from a file / memory size.  All of this would be wrapped up so that someone accessing the TAP would have no idea.

**Comment by benkrikler** [comment]
This was finalised with pull request #88 which has now been merged so I'm closing this ticket.
