### ISSUE TITLE
Can I rename FillHistBase.h?

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#76]
The name for the modules base class is currently 'FillHistBase' which is a hangover from the early rootana days.  It's a really awful name now though, cause so far, most of our modules do very little histogram filling.   Also, with this name being used already, if we really did want a module specialisation for just filling a histogram, this name would be useful.

It might cause a short bit of head-ache, but if everyone pushes there code into develop then I'd be able to do the complete renaming quite easily for us. It's probably only a few commits of work to get this done I reckon..

**Comment by AndrewEdmonds11** [comment]
I definitely support the renaming but the feature I'm working on at the moment (new_template_tap_generator) is incomplete so I'd rather not merge into develop just yet (although having said that, maybe I should be splitting it into small feature branches....). 

Anyway, if you let me know the commands you used (sed?) then I can rebase and then run it on the remaining modules (which presumably only exist on this branch)

**Comment by benkrikler** [comment]
Great!  I'll post the command here and let you know once it's done.

**Comment by benkrikler** [comment]
I've just put this change in.  The class is now known as BaseModule.

I used the following command to make the changes through all code, starting at rootana/src.

``` bash
shopt -s globstar
for i in **;do sed -i -e 's!FillHistBase!BaseModule!g' $i;done
```

I'll leave this open for a while longer in case we hit related bugs.

**Comment by AndrewEdmonds11** [comment]
So, I'm trying to do your renaming but apparently `bash: shopt: globstar: invalid shell option name`. What is the purpose of the first command and can I get around using it?

**Comment by benkrikler** [comment]
I guess you're using an older version of bash.  You could update it, or you could try something more like:

``` bash
for i in `grep -l 'FillHistBase' -R .`; do
      sed -i -e 's!FillHistBase!BaseModule!g' $i
done
```

The globstar option enables `**` which is a recursive glob.

**EDIT:** Added a missing semi-colon before `do` as spotted by Andy below.

**Comment by AndrewEdmonds11** [comment]
Done for the stuff on this feature branch. 

I did need a semicolon before "do" and I also replaced "!" with "/" but this one may not be important (I'd already changed it when I found the real error)

**Comment by benkrikler** [comment]
Oh yeah, sorry, the semi-colon is the problem.  sed will accept any characted after the s, so `s!match!replace!g` should work fine (and won't get in the way of path strings, which is why I use it).

[Updated answer in above message so it works]

**Comment by benkrikler** [comment]
I'm going to close this then, but if we encounter problems related to it then we can reopen this then.
