### ISSUE TITLE
Rootana: IDs::channel::GetDetectorEnum() takes a string as an argument?

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#79]
Hi @benkrikler 

I'm using this bit of code to get the name of the detector:

``` c++
IDs::channel theChannel = fPulseIsland->GetBankName();
if (theChannel == IDs::Fast) {

    int rise = 0; // the parameter for this algorithm
    switch(theChannel.GetDetectorEnum()) {
    case kGe:
      rise = 100;
      break;
    }

    FindPulseCandidates_Fast(rise);
  }
```

which doesn't work because `GetDetectorEnum()` is this:

``` c++
IDs::Detector_t IDs::channel::GetDetectorEnum(const std::string& det){
     const char* names[IDs::num_detector_enums]={ 
             "*", "Ge", "LiquidSc", "NDet", "NDet2", "ScGe", "ScL", "ScR", 
                "ScVe", "SiL1_1", "SiL1_2", "SiL1_3", "SiL1_4", "SiL2", 
                "SiR1_1", "SiR1_2", "SiR1_3", "SiR1_4", "SiR1_sum", "SiR2", 
                "MuSc", "MuScA" };
     for (int i=0;i<IDs::num_detector_enums;i++){
        if(det==names[i]) return (Detector_t)i;
     } 
     return kErrorDetector;
}
```

What's confusing is that I call this function on the IDs::channel object, but I also have to pass in the name of the detector.

I've just rebased to see if it's something that's been updated since my last rebase but it's still there. 

Could I get a clarification on how to use this?

**Comment by benkrikler** [comment]
That's embarrassing.  I gave you the wrong method, or rather, I've named these methods badly.
Replace, `GetDetectorEnum()` which is a static method to convert a string to the corresponding enum, with, `Detector()` which returns the detector enum for the current channel.

I should probably rename these methods:
- `GetDetectorEnum` -> `StringToDetectorEnum`
- `Detector` -> `GetDetectorEnum`

**Comment by AndrewEdmonds11** [comment]
Ok, I will rename it for the time being and then no doubt ask you this same question again after you've renamed and I've rebased
