### ISSUE TITLE
IDs::Channel::str() returning "Unknown-*"

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#81]
Hi again @benkrikler. I'm trying to use this function in IDs::Channel:

``` c++
std::string IDs::channel::str()const{
   std::string output=GetDetectorString(this->fDetector);
   output+=GetSlowFastString(this->fSlowFast);
   return output;
}
```

so that I can put the channel name in a histogram title like so:

``` c++
IDs::channel theChannel = fPulseIsland->GetBankName();
...
...
std::stringstream histtitle;
histtitle << "Plot of " << parameter_name << " for " << theChannel.str() << " for Run " << 2808;
histogram->SetTitle(histtitle.str().c_str());
```

However, it always seems to return "Unknown-*". Any ideas?

**Comment by benkrikler** [comment]
You're getting the bank name for the pulse island.  You need to use the detector name as `IDs::channel` has no idea about the bank name. We can open a new feature request and I'll add it in at some point if you want.

What are you trying to write?  Can you get the name from the header of the list or do you need to query every pulse individually?

**Comment by AndrewEdmonds11** [comment]
So I should be doing:

``` c++
std::string detname = TSetupData::Instance()->GetDetectorName(fPulseIsland->GetBankName);
IDs::channel theChannel = detname
```

?

In which case, I don't need this and will just use the detector name in histtitle. I just thought that the idea of this IDs stuff was to have a consistent way of getting bank names, detector names, whether it's fast or slow etc.

**Comment by benkrikler** [comment]
They were written with the event navigator in mind, to be used as the key in maps of channel to pulse lists.  In that sense the original intention was never to replace TSetupData's functionality directly.  

I'll extend the 'set by string' methods to first check for a detector name and if it fails, check for a bank name.

**Comment by benkrikler** [comment]
Phill and I spoke about this briefly last week.  His feeling is that the task of obtaining the midas bank that held a given detector channel should be handled elsewhere than the Channel ID.  For now this means we will still need to use TSetupData, but long term something like a Setup Navigator will take this over.

As a result, I'm closing this, though feel free to comment or reopen if you feel this is pressing.

(It's also worth pointing out that issue #101 has made other changes to `IDs::channel` that related to this, namely assigning it from a string).

**Comment by litchfld** [comment]
Yes,  FTR my argument is that Detector <-> Bank Name is a database lookup, and should be mediated by a class representing a DB lookup.  It's possible that Channel ID could wrap this up, but then the difference is just down to function call semanitcs, and I think the form 

``` C++
std::string SomeUtility::BankName(IDs::channel); 
```

is easier to maintain.
