### ISSUE TITLE
Not sure about these operators

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#82]
I just noiticed that in some of the ID classes we have equality operators, e.g. from https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/framework/IdChannel.h#L84 that do not use simple boolean logic, e.g.:

``` C++
inline bool IDs::channel::operator==(const IDs::channel& rhs)const{
    return (fDetector==kAnyDetector || rhs.fDetector==kAnyDetector || fDetector==rhs.fDetector) 
    && (fSlowFast==kAnySlowFast || rhs.fSlowFast==kAnySlowFast || fSlowFast==rhs.fSlowFast) ;
}
```

This is convenient, but I've seen stuff like this cause errors before.
The problem is the wildcards `kAnyDetector`. If I have three Channel IDs:

``` C++
IDs::channel A(kGe,kSlow);
IDs::channel B(kAnyDetector,kSlow);
IDs::channel C(kScL,kSlow);

if (A==B && B==C){
// "Therefore A==C so i can do..."   <==Wrong!
// ...blah..
} 
```

Of course this is an obvious example, and few people would be that dumb (i'm likely one of the few), but it becomes less obvious if you are, say, doing double-loops over channels.  I'd suggest using `operator==()` only for exact semantic equality, and some other function to denote wildcard matching.

TBC with concrete suggestion

**Comment by benkrikler** [comment]
I see what you mean.  If you've seen this be a problem before, then I'm happy to change it.

How about a `Matches` method:

``` c++
IDs::channel A(kGe,kSlow);
IDs::channel B(kAnyDetector,kSlow);
if(B.Matches(A)){
 //do something
}
```

Does this do enough to reduce the chance of  your problem arising?

[Edited the code block to put the method in an `if() block`]

**Comment by benkrikler** [comment]
And if we do go down that route, do we purposely break the symmetry of `A==B` => `B==A` ?

That would mean that:

``` c++
IDs::channel A(kGe,kSlow);
IDs::channel B(kAnyDetector,kSlow);
if(B.Matches(A))   cout<<"B does match A"<<endl;
else  cout<<"B does not match A"<<endl;

if(A.Matches(B))   cout<<"A does match B"<<endl;
else  cout<<"A does not match B"<<endl;
```

would give:

```
B does match A
A does not match B
```

Is that more or less intuitive do you think?

**Comment by litchfld** [comment]
So my suggestion would be redefine '==' for strict lexical equality:

``` C++
inline bool IDs::channel::operator==(const IDs::channel& rhs)const{
    return (fDetector==rhs.fDetector) &&  (fSlowFast==rhs.fSlowFast) ;
}
```

and then a function `Matches()` or `IsConsistent()` (name is not too critical) that implements the old equality function:

``` C++
inline bool IDs::channel::Matches(const IDs::channel& rhs)const{
    return (fDetector==kAnyDetector || rhs.fDetector==kAnyDetector || fDetector==rhs.fDetector) 
    && (fSlowFast==kAnySlowFast || rhs.fSlowFast==kAnySlowFast || fSlowFast==rhs.fSlowFast) ;
}
```

Random thoughts: Perhaps the bitwise logical operators _might_ have the right semantics, where detector, fast/slow, generator and config are treated like the bits somehow. But I haven't thought it through enough to be sure. Another possibility  is to have a channel mask class so logical evaluations can depend on type info, but again I haven't thought it through.  Probably we should just do the simple suggestion above (& similar for generators, sources) and come back if we run out of important things to do.

**Comment by litchfld** [comment]
I wrote that last post before I refreshed and saw your comments.  But I _think_ it's fine to keep it symmetric for `Matches()`. Both ways seem semantically OK:

> "Does _X_ fit in category _A_?"  vs "does category _A_ include _X_?". 

And as long as you aren't [one isn't] writing expressions that look like simple numerical equalities you're [one is] much more likely to think the semantics through and get it right.

**Comment by benkrikler** [comment]
Yeah I should have made it clearer that `Matches` would assume the current `operator==` implementation (with possible change of symmetry, though what you're saying there sounds reasonable as well).

As for replacing the enums with bit fields and using bitwise operators instead (or at least internally), the only advantage I could think of, was if it meant we could do:

```
Detector_t aDet;
SlowFast_t aSF;
switch(aDet+aSF){
   case kGe_F:
      break;
   case kGe_S:
      break;
   // etc
}
```

Basically, I'm wondering whether replacing things with bits would enable a single switch block in cases such as Andy's PrePulse finder ( #57 ).  I don't know if that would work though, and obviosuly we would want to wrap that up a bit better for people to use.

**Comment by benkrikler** [comment]
I also defined `IDs::source::operator==(const IDs::channel&)` and `IDs::source::operator==(const IDs::generator&)`.  They invoke `operator==` on the contained `channel` or `generator` ID respectively.

I think I will follow the replacements above and overload `IDs::source::Matches` to take either a `source`, `channel` or a `generator` ID.  The logic would be equivalent:  Matches will use pass true if one of the ids contains a `kAny` value or if the values are the same, whereas operator== will only return true if the two are identical.

**Comment by litchfld** [comment]
> As for replacing the enums with bit fields and using bitwise operators instead (or at least internally), the only advantage I could think of, was if it meant we could do

Ah sorry, I meant that the bitwise operators might have the same algebra and be a suitable candidate for overloading, not that we should reimplement the classes as wrapped bit fields (admittedly, that is what I would have done, so I'm naturally in favour _in principle_. But I don't think it matters enough to  change it)

> Matches will use pass true if one of the ids contains a `kAny` value or if the values are the same, whereas `operator==` will only return true if the two are identical.

How is 'identical' defined for say sources and channels?  It seems that's another can of worms you don't really want to have to worry about.  I'd just leave it with the `Matches()` and that should be fine for any sane use.  A user can always do `mySource.Channel() ==  myChannel` if that's what they want, and it makes intention more explicit.

**Comment by benkrikler** [comment]
Done as described above.  I also added `isFast` and `isSlow` methods so we don't need to do `==IDs::Fast` which would have had to become `.matches(IDs::Fast)`.
