### ISSUE TITLE
Rerun ODB Checker to get ODB Corrections Files

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#86]
Hi John!

Not sure if you've already done this but we'll need the new ODB corrections files done before we do the production run. Everything else should be set up by the time you wake up so just close this and then we should be ready to go

Cheers
Andy

**Comment by jrquirk** [comment]
I reran them last night. They're at merlin:~quirk_j/data/corr. Again, people can either run their own or link to mine. Not that I fixed a bug last night so a fresh `pull` and `make` need to be done on the odb_check as well.

**Comment by AndrewEdmonds11** [comment]
Thanks, John. The batch scripts have the CORRDIR (or whatever the variable is) set to look in your directory so we should be OK to go.

Expect an e-mail soon...
