### ISSUE TITLE
Are we making any changes to golden runs?

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#87]
Are we making any changes to the golden runs for the third alcapana production run?

I know there are things we are discussing and I guess it doesn't hurt to run with everything we have and sort it out for the rootana run.

**Comment by jrquirk** [comment]
I think there will be trimmings of the golden runs, but that we can do it (if we do in fact do this) after alcapana.

**Comment by AndrewEdmonds11** [comment]
Cool. That's what I though.

**Comment by benkrikler** [comment]
I just realised, run3731 doesn't seem to exist which gave us problems for production 2.  It's included in the Al50b-pt2 dataset which is allocated to @ajidaniel.  It seems to still be in the run ranges in the scripts.

**Comment by AndrewEdmonds11** [comment]
Did it give us problems running? I thought it just got skipped over and it's just that we didn't realise...

**Comment by benkrikler** [comment]
Wasn't that the dataset we had trouble wth though?  I thought it was due to this?

**Comment by AndrewEdmonds11** [comment]
What trouble?

**Comment by benkrikler** [comment]
I don't seem able to find the issue any more, but I thought it was related to why one dataset didn't seem to complete. If you think it's ok though then that's all fine....

**Comment by ajidaniel** [comment]
I think we were just plotting old data file (from production 1)  for  LLDQ version 2. John corrected it and produced new files (see related entry #111  in elog by John).
