### ISSUE TITLE
Container names in file

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#89]
So we have identifier for specific containers of XxxPulses of the form
`"\<detector\>::\<generator\>::\<generator_config\>"`, 
which is the output of  [IDs::source::str()](http://alcap-org.github.io/doxygen/AlcapDAQ/develop/classIDs_1_1source.html#a4cd834aa7242fd994872e3f9745284e3). 

Unfortunately this may do bad things on file because I intend to use the container names as branch names in the tree.  I found this (old) [post on roottalk](http://root.cern.ch/root/roottalk/roottalk02/1051.html) which says that `':'` characters are to be avoided.

From that post, I speculate the following character set is dangerous and should be avoided:

```
! ^ * & % ( ) [ ] { } + - / = < > " ' : .
```

I'm also fairly sure that spaces would be a nuisance.

I quite like the format as is, but it won't work for files. So we need an-on file alternative, even if we don't modify the displayed text and in-memory keys.  I wondered about putting an underscore as a replacement for `::`, but that prevents people from using underscores in generator configs. So let's consider some other options:
1. `__` (double underscore)
2. `_G_` (preceding generator) and `_C_` (preceding config)
3. `GG` and `CC`, similar to above
4. Some variant of these or something else.

What do people suggest/prefer?

**Comment by benkrikler** [comment]
Your list of dangerous characters ommits `:`, is that correct?  It also leaves out any of: `| \ # ~ ; % @ .`.  I think `#` would read quite well, as perhaps would `||` or `...`. 

I don't much like `CC` or `GG`, and `_C_` or `_G_` are only slightly better.

**Comment by litchfld** [comment]
Oops, missing out `:` was a mistake. [...]  A mistake that I have now rectified.

So, as for the other characters you mention, I didn't find any direct evidence for them being in use, so I didn't add them to the list as I went along.  I am a bit wary of them though, some more than others. Let me go through...
- `|` is a bitwise OR, and may or may not be okay. The logical or `||` can be used in a cut so I imagine that is unsafe.
- `\` is the standard string escape character so might interact badly with tty.
-  `#` doesn't normally have any meaning inside C++ strings, so is most likely of the ones you suggest to be fine.
- `~` is another C++ operator (bit inversion) and may or may not be okay.
- `;` is obviously a C++ endline which might not be a problem, but also used for `name;cycle` delimiting in ROOT files... i'm not sure if that's a potential issue. 
- `%` is of course used by sprintf and the like.  I can see this might lead us astray somewhere, although I can't easily imagine why anyone would be doing something so funky.  
  [edit: _Come to think of it, it's also the modulo operator which is used by TCut so almost certainly not allowed_] 
- `@`, like `#`, might well be fine (?)
- `.` is the 'normal' sub-branch delimiter so is particularly unlikely to work. I should add that to the list of definite 'no's.
- `?` maybe?
- `,` maybe?

I'll try `#` or `_#` out. I prefer the latter since a bigram is less likely to be used accidentally. `##` worries me, being the most magickal of preprocessor magicks.

**Comment by benkrikler** [comment]
I'm using the `#` symbol now.  This should also be easier to change cause I define a single const delimiter string in the IDs namespace (in `IdGenerator.h` I believe).  The generator configuration strings might need more thought as we'd need to consider how we handle funny characters in the options themselves.  Given the title of this issue I think this is finished, but we may need to revisit this or open a new issue to deal with the configuration strings.

**Comment by litchfld** [comment]
> The generator configuration strings might need more thought as we'd need to consider how we handle funny characters in the options themselves.

Easy, you ban them. Test for the presence of the banned delimiter when the module instantiates itself and if a verboten sting comes up you print an accusing message and terminate.  We ought to fix the delimiter soon though, if you change it, old files won't read in.

**Comment by benkrikler** [comment]
On second thoughts, using `#` might not have been the best choice:
- It's not valid c++ so we wont be able to use `IDs::source.str()` in histogram names and get the histograms back without going through `gROOT->Get(".......")` in interactive root.  Minor inconvenience, but inconvenient nonetheless.
- The modules file treats `#` as beginning a comment.  At the moment this only works if the hash is the first characted of the line but it still feels risky and it might be useful to be able to specify source strings in the modules file as an option to a particular module (eg, tell the PulseViewer module what source to draw TAPs from).
