### ISSUE TITLE
Merge PictureBooks in?

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#94]
Can I merge the picture book branch into develop?
@AndrewEdmonds11 @joegrange

**Comment by joegrange** [comment]
No objections here, but this is much more Andy's baby than mine.

**Comment by AndrewEdmonds11** [comment]
Yep, fine by me. It was branched off develop a long time ago but rebasing should be fine since all the changes are in it's own subdirectory.

**Comment by AndrewEdmonds11** [comment]
Done (72e305649e41d3acfb6a8cb3935536337a60b621)
