### ISSUE TITLE
C++ 11 anyone?

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#95]
I read this article: http://www.cplusplus.com/articles/EzywvCM9/
and got freaked out by how cool some of the new features look ( I know I'm shattering the cool guy image you all had of me ), plus there's the new containers and algorithms available in c++11.

Merlin has gcc 4.4.7 installed and according to [this article](https://gcc.gnu.org/projects/cxx0x.html), gcc 4.3 added support for c++11, so we're not ruled out by that.

There's no specific benefit that I'm thinking of though, I just wanted to canvas opinion...

**Comment by AndrewEdmonds11** [comment]
How will this affect the framework? Is it going to take a few weeks to add the things you want in? I'm just a bit mindful that we need to start doing physics and any major changes will delay us by longer than we expect.

However, I'm not against it being a long-term change. If you say the new features are cool, then the new features are cool (although now _you_ aren't :) )

**Comment by thnam** [comment]
@benkrikler I also don't see immediate advantage of using new features. Sure the C++11 way is nicer than what we have, but we will have a mixed bag of old and new code. Plus we will have several more things to learn and remember ...

**Comment by benkrikler** [comment]
It's just another distraction I guess.  If we come across some functionality that we really feel we need, then we can revisit this, until then, let's not bother.

To alleviate any concerns in case that ever happens, it would probably not have a big impact or require anyone to learn anything new at all.  Everything you already know would work still.  It might make some library code simpler, and it would make most of our lives easier (for instance, the `auto` variable would allow us to replace a few typedefs, meaning less typing and more flexibility to change list types without breaking things).  The only thing we would NEED to change, is to make sure we use gcc 4.3 or greater and set an extra compiler flag.  Given Merlin has this already though, I'm not sure if it's that much of a restriction.

Anyway, I'll close this for now, and if anyone finds a burning desire to use one of the new features, they can re-open this and describe why.

**Comment by litchfld** [comment]
I'd quite like to try out C++11, but this is not really a long-term code base, so the costs of transitioning is a pretty big factor. Remember costs will be larger when you include things like _person A_ trying out lambdas then _person B_ needing to learn them to debug something. As Andy says this is a tool for the physics, not a goal in itself.

In any case anyone (UCL, for example) who still uses SL5 probably has gcc 4.1.2, so that does sort of sink things.  And TBH, AlCap code has a long way to go before it looks like C++98.

**Comment by litchfld** [comment]
PS: I notice the article didn't mention lambdas. See  [here](http://en.cppreference.com/w/cpp/language/lambda) for example.
