### ISSUE TITLE
Select Parameters for CandidatePulseFinder

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#98]
When I closed issue #57, I mentioned that we still need to select the values of the parameters for the fast and slow algorithms.

Currently, we have a module called PulseCandidateFinder_InvestigateParameters that plots the distributions we need to look at (sample height above pedestal for the slow channels and sample differences for the fast channels).

e.g. muSc
![run2808_musc_sample-differences](https://cloud.githubusercontent.com/assets/1848575/3287584/e297318e-f559-11e3-8ee0-fa6db5d9adee.gif)

Here it's quite easy to see what the choice should be, however for other channels it's not so obvious:

![run2808_ndet_sample-differences](https://cloud.githubusercontent.com/assets/1848575/3287589/feb2da76-f559-11e3-89ea-896b3fb31139.gif)

![run2808_sir1-2-s_sample-height](https://cloud.githubusercontent.com/assets/1848575/3287590/02c5bcf0-f55a-11e3-8f8f-d78b52300949.gif)

For the second plot here, more stats may help but it's unclear (to me, anyway) how to improve things for the first one.

Anyone have any ideas about how to proceed?

**Comment by benkrikler** [comment]
How about looking at the difference of the squares of adjacent samples?  Here's my thought process:
- Weight the difference by the sample's distance to the pedestal (noisy samples near the pedestal would be suppressed).  
- You could do something like a_(a-b), but then why not weight by the average of the two samples which seems statistically more symmetric: (a+b)_(a-b), but that's just (a^2-b^2).

It also feels like looking at (a-b) / (a+b) might be interesting with the cut inverted, though I think this one might make no sense whatsoever.  It would probably perform better to noise though since the errors should cancel I think.

[edit: I should have said that a and b are adjacent samples...]

**Comment by jrquirk** [comment]
Make threshold cuts to stay away from noise and saturation like Phil said. There may be some non-obvious changes in the difference plot, but again a distribution without a peak doesn't seem like a bad sign. If the template idea is expected to work, perhaps it shouldn't matter too much.

You can always make multiple templates with different parameters and see how much the thresholds really matter.

**Comment by litchfld** [comment]
They had better not matter too much, otherwise the whole method is suspect! 
It doesn't need to be a very sophisticated or efficient cut here.  You just need a nice clean sample.

**Comment by AndrewEdmonds11** [comment]
I will make a presentation for the meeting tomorrow that will have a few more plots but here's a summary:

### Initial Estimates

I used the PulseCandidateFinder_InvestigateParameter module on run 2808 to get the parameter histograms and very roughly judged the values that we should use to be:

| Channel | Rise or Threshold | Channel | Rise or Threshold |
| --- | --- | --- | --- |
| muSc | 300 | SiR1-2-F | 60 |
| muScA | 100 | SiR1-3-F | 60 |
| NDet | 100 | SiR1-4-F | 40 |
| Ge-S | 500 | SiR2-S | 50 |
| Ge-F | 40 | SiR1-4-S | 40 |
| SiL2-S | 20 | SiR1-2-S | 30 |
| SiL2-F | 20 | SiL1-2-S | 150 |
| SiL1-1-S | 20 | SiR2-F | 20 |
| ScL | 20 | SiR1-1-S | 50 |
| ScR | 20 | SiL1-4-S | 40 |
| SiL1-1-F | 20 | SiR1-3-S | 40 |
| ScGe | 20 | SiL1-3-S | 20 |
| ScVe | 40 | SiL1-3-F | 20 |
| SiR1-1-F | 40 | SiL1-2-F | 20 |
| SiL1-4-F | 20 |  |  |

NB Enums not yet handled are: kErrorDetector, kAnyDetector, kLiquidSc, kNDet2, kSiR1_sum

### Exporting pulses from the first event of 2808

Next, I ran the TemplateCreator module (as of commit 3750bdc784b9154931d04513628bd7c68671aaff) on just the first event of run 2808, which exports (via ExportPulse) the full TPI waveform of any TPI which has more than 0 candidates found and also prints a message if it's more than 1.

(NB that this event might not have TPIs for all the channels, I should probably look in the first few events.)

### Checking TPIs with >1 Pulse Candidates

Here is the list of TPIs with greater than 1 pulse candidate and what I thought when I looked at them (I'll go through the plots tomorrow):

| Channel | Pulse # | No. of Pulse Candidates | Comment | Channel | Pulse # | No. of Pulse Candidates | Comment |
| --- | --- | --- | --- | --- | --- | --- | --- |
| SiL2-F | 0 | 8 | Just noise? | SiL1-1-F | 0 | 2 | Should be 1? |
| ScL | 2 | 3 | Should be 4? | ScVe | 8 | 2 | Correct |
|  | 3 | 2 | Correct |  | 12 | 2 | Correct |
|  | 20 | 3 | Correct |  | 20 | 2 | Correct |
|  | 29 | 2 | Correct |  | 30 | 2 | Correct |
| ScR | 34 | 2 | Don't know |  | 32 | 2 | Correct |
|  | 77 | 3 | Don't know |  | 2518 | 2 | Correct |
|  | 162 | 2 | Correct |  | SiL1-4-F | 0 | 19 |
|  | 249 | 3 | Should be 4? |  |  |  |  |
|  | 371 | 2 | Correct |  |  |  |  |
|  | 444 | 2 | Correct |  |  |  |  |
|  | 481 | 2 | Correct |  |  |  |  |
|  | 593 | 2 | Don't know |  |  |  |  |
|  | 687 | 3 | Should be 2? |  |  |  |  |

Then I looked through all the rest of the pulses to make sure that no noisy ones got through (for the "nice clean sample") and they were all fine (a few should maybe have 2 candidates and there was one ScGe pulse that had a very wide peak. Again, I'll show the plots tomorrow)

### Checking TPIs with 0 Pulse Candidates

I modified TemplateCreator so that it exported TPIs with 0 pulse candidates and looked through them, very briefly. The main points
- All Ge-Fs were noise (good)
- 9 out of 15 Ge-Ss were pulses
- At least 1 pulse (that I saw) in NDet, muSc and muScA
- I didn't see any pulses in NDet but I didn't check them all

### Conclusion

I think I'll need to modify the parameters slightly, I'll have a think about exactly how and then present tomorrow.

**Comment by AndrewEdmonds11** [comment]
Whoops. Didn't realise I already had this as an issue. This has now moved to issue #184.
